<br> </br>
TRUNCATE TABLE OMNI_SALES_GRP;
<br> </br>
TRUNCATE TABLE MASTER_SALES_ROUND_SP;
<br> </br>
TRUNCATE TABLE MASTER_SALES_ROUND;
<br> </br>
TRUNCATE TABLE ALLOCATION_CONTROL_PQ_SF;
<br>   
---run spar function create ALLOCATION_OMNI
-- input_file= 'omni_allocation_control'
-- master_file= 'omni_master_sales_final'
-- output_file = 'ALLOCATION_OMNI'

----insert allocation function
	 
/*OMNI_SALES_GRP*/
--Note need to fill  OR Populate data for "ALLOCATION_OMNI" table throguh spark SQL  generated file to snowflake below table 
--ALLOCATION_OMNI_SF_JOINED_WINDOWS
--ALLOCATION_OMNI table is generating from Spark SQL plesae  check the table before below Query to execute 
--ALLOCATION_OMNI is main table in below Query 
</br>
CREATE OR REPLACE TEMPORARY TABLE ALLOCATION_OMNI_SF_JOINED_WINDOWS
AS
WITH CTE AS (SELECT 
    "YEAR_PERIOD" AS "YEAR_PERIOD",
    "MERCH_YEAR" AS "MERCH_YEAR",
    cast("allocation_value" as varchar) AS "allocation_value",
    cast("tsc_delivery_flag" as varchar)AS "tsc_delivery_flag",
    "YEAR_QUARTER" AS "YEAR_QUARTER",
    "store_deliv_per_month" AS "store_deliv_per_month",
    "omni_orders_per_month" AS "omni_orders_per_month",
    COALESCE("store_deliv_per_month", 0) + COALESCE("omni_orders_per_month", 0) AS "total_orders"
  FROM (
    SELECT 
        "TENANT149_DATA_tsc_delivery_prepared_joined"."YEAR_PERIOD" AS "YEAR_PERIOD",
        "TENANT149_DATA_tsc_delivery_prepared_joined"."MERCH_YEAR" AS "MERCH_YEAR",
        "TENANT149_DATA_tsc_delivery_prepared_joined"."allocation_value" AS "allocation_value",
        "TENANT149_DATA_tsc_delivery_prepared_joined"."tsc_delivery_flag" AS "tsc_delivery_flag",
        "TENANT149_DATA_tsc_delivery_prepared_joined"."YEAR_QUARTER" AS "YEAR_QUARTER",
        cast("TENANT149_DATA_tsc_delivery_store_count_prepared_by_YEAR_QUARTER_prepared"."store_deliv_per_month" as varchar) AS "store_deliv_per_month",
        cast("tsc_delivery_orders"."OMS_ORDER_NO_distinct" as varchar) AS "omni_orders_per_month"
      FROM (SELECT 
                    "tsc_delivery_prepared"."YEAR_PERIOD" AS "YEAR_PERIOD",
                    "tsc_delivery_prepared"."MERCH_YEAR" AS "MERCH_YEAR",
                    "tsc_delivery_prepared".allocation_value AS "allocation_value",
                    "tsc_delivery_prepared".tsc_delivery_flag AS "tsc_delivery_flag",
                    "TENANT149_TENANT149_DATA_time_dimension_prepared_by_YEAR_PERIOD"."YEAR_QUARTER" AS "YEAR_QUARTER"
            FROM "TSC_DELIVERY_PREPARED" "tsc_delivery_prepared"
             LEFT JOIN (SELECT 
                   "YEAR_PERIOD" AS "YEAR_PERIOD",
                   "YEAR_QUARTER" AS "YEAR_QUARTER"
              FROM "TIME_DIMENSION_PREPARED" 
              GROUP BY "YEAR_PERIOD", "YEAR_QUARTER") "TENANT149_TENANT149_DATA_time_dimension_prepared_by_YEAR_PERIOD"
              ON "tsc_delivery_prepared"."YEAR_PERIOD" = "TENANT149_TENANT149_DATA_time_dimension_prepared_by_YEAR_PERIOD"."YEAR_PERIOD") "TENANT149_DATA_tsc_delivery_prepared_joined"
      LEFT JOIN (SELECT 
                    "YEAR_QUARTER",
                    Deliv_Count_sum,
                    count,
                    cast(Deliv_Count_sum / 3 as varchar) AS "store_deliv_per_month"
                  FROM "TSC_DELIVERY_STORE_COUNT_PREPARED_BY_YEAR_QUARTER" )"TENANT149_DATA_tsc_delivery_store_count_prepared_by_YEAR_QUARTER_prepared"
    ON "TENANT149_DATA_tsc_delivery_prepared_joined"."YEAR_QUARTER" =      
               "TENANT149_DATA_tsc_delivery_store_count_prepared_by_YEAR_QUARTER_prepared"."YEAR_QUARTER"
      LEFT JOIN (SELECT 
                 "YEAR_PERIOD" AS "YEAR_PERIOD",
                  COUNT( "OMS_ORDER_NO") AS "OMS_ORDER_NO_distinct"
                 FROM (
                        SELECT  *,
                                round(BOOKED_SALES_AMT,0) as SALES_ALLOCATE,
                                round(BOOKED_COST_AMT,0) as COST_ALLOCATE
                                FROM  omnichannel_sales)
                                GROUP BY "YEAR_PERIOD") "tsc_delivery_orders"
        ON "TENANT149_DATA_tsc_delivery_prepared_joined"."YEAR_PERIOD" = "tsc_delivery_orders"."YEAR_PERIOD"
    ) "withoutcomputedcols_query"
  )
  SELECT 
    "allocation_omni_sf"."ARTICLE_NO" AS "ARTICLE_NO",
    "allocation_omni_sf"."MERCH_YEAR" AS "MERCH_YEAR",
    "allocation_omni_sf".tsc_delivery_flag AS "tsc_delivery_flag",
    "allocation_omni_sf"."YEAR_PERIOD" AS "YEAR_PERIOD",
    "allocation_omni_sf"."OMS_ORDER_LINE_KEY" AS "OMS_ORDER_LINE_KEY",
    "allocation_omni_sf".roadie_flag AS "roadie_flag",
    "allocation_omni_sf"."ACCT_YEAR" AS "ACCT_YEAR",
    "allocation_omni_sf"."YEAR_WEEK" AS "YEAR_WEEK",
    "allocation_omni_sf"."OMS_ORDER_NO" AS "OMS_ORDER_NO",
    "allocation_omni_sf"."VENDOR_ID" AS "VENDOR_ID",
    "allocation_omni_sf"."OMS_ORDER_LINE_SCHEDULE_SHIP_NODE" AS "OMS_ORDER_LINE_SCHEDULE_SHIP_NODE",
    "allocation_omni_sf"."OMS_SHIP_NODE_DESC" AS "OMS_SHIP_NODE_DESC",
    "allocation_omni_sf"."ARTICLE_CAT_FULL" AS "ARTICLE_CAT_FULL",
    "allocation_omni_sf"."DEMAND_QTY" AS "DEMAND_QTY",
    "allocation_omni_sf"."DEMAND_SALES" AS "DEMAND_SALES",
    "allocation_omni_sf"."BOOKED_SALES_QTY" AS "BOOKED_SALES_QTY",
    "allocation_omni_sf"."BOOKED_SALES_AMT" AS "BOOKED_SALES_AMT",
    "allocation_omni_sf"."BOOKED_COST_AMT" AS "BOOKED_COST_AMT",
    "allocation_omni_sf"."SHIPPING_REVENUE" AS "SHIPPING_REVENUE",
    "allocation_omni_sf"."SHIPPING_DISC" AS "SHIPPING_DISC",
    "allocation_omni_sf"."ACTUAL_SHIPPING_REVENUE" AS "ACTUAL_SHIPPING_REVENUE",
    "allocation_omni_sf"."ORDER_LINE_TYPE" AS "ORDER_LINE_TYPE",
    "allocation_omni_sf"."SCAC" AS "SCAC",
    "allocation_omni_sf"."SHIP_NODE_TYPE" AS "SHIP_NODE_TYPE",
    "allocation_omni_sf"."YEAR_QUARTER" AS "YEAR_QUARTER",
    "allocation_omni_sf"."CHAIN_PROD" AS "CHAIN_PROD",
    "allocation_omni_sf"."ARTICLE_DESC" AS "ARTICLE_DESC",
    "allocation_omni_sf"."ARTICLE_FULL" AS "ARTICLE_FULL",
    "allocation_omni_sf"."ARTICLE_TYPE_NAME" AS "ARTICLE_TYPE_NAME",
    "allocation_omni_sf"."ARTICLE_TYPE_CODE" AS "ARTICLE_TYPE_CODE",
    "allocation_omni_sf"."ARTICLE_TYPE_FULL" AS "ARTICLE_TYPE_FULL",
    "allocation_omni_sf"."ARTICLE_LENGTH" AS "ARTICLE_LENGTH",
    "allocation_omni_sf"."ARTICLE_WIDTH" AS "ARTICLE_WIDTH",
    "allocation_omni_sf"."ARTICLE_HEIGHT" AS "ARTICLE_HEIGHT",
    "allocation_omni_sf"."ARTICLE_WEIGHT" AS "ARTICLE_WEIGHT",
    "allocation_omni_sf".total_weight AS "total_weight",
    "allocation_omni_sf"."ARTICLE_SIZE" AS "ARTICLE_SIZE",
    "allocation_omni_sf"."ARTICLE_COUNT" AS "ARTICLE_COUNT",
    "allocation_omni_sf"."ARTICLE_COLOR" AS "ARTICLE_COLOR",
    "allocation_omni_sf"."PARENT_ARTICLE_NO" AS "PARENT_ARTICLE_NO",
    "allocation_omni_sf"."PARENT_ARTICLE_DESC" AS "PARENT_ARTICLE_DESC",
    "allocation_omni_sf"."PARENT_ARTICLE_FULL" AS "PARENT_ARTICLE_FULL",
    "allocation_omni_sf"."PRIMARY_VENDOR_ID" AS "PRIMARY_VENDOR_ID",
    "allocation_omni_sf"."ARTICLE_CAT_CODE" AS "ARTICLE_CAT_CODE",
    "allocation_omni_sf"."ARTICLE_CAT_NAME" AS "ARTICLE_CAT_NAME",
    "allocation_omni_sf"."DEPT_CODE" AS "DEPT_CODE",
    "allocation_omni_sf"."DEPT_NAME" AS "DEPT_NAME",
    "allocation_omni_sf"."DEPT_FULL" AS "DEPT_FULL",
    "allocation_omni_sf"."LOB_NO" AS "LOB_NO",
    "allocation_omni_sf"."LOB_DESC" AS "LOB_DESC",
    "allocation_omni_sf"."LOB_FULL" AS "LOB_FULL",
    "allocation_omni_sf"."MAJ_DEPT_NO" AS "MAJ_DEPT_NO",
    "allocation_omni_sf"."MAJ_DEPT_DESC" AS "MAJ_DEPT_DESC",
    "allocation_omni_sf"."MAJ_DEPT_FULL" AS "MAJ_DEPT_FULL",
    "allocation_omni_sf"."BRAND_NAME" AS "BRAND_NAME",
    "allocation_omni_sf"."PVT_LABEL_DESC" AS "PVT_LABEL_DESC",
    "allocation_omni_sf"."VENDOR_NAME" AS "VENDOR_NAME",
    "allocation_omni_sf"."VENDOR_FULL" AS "VENDOR_FULL",
    "allocation_omni_sf"."PARENT_VENDOR_ID" AS "PARENT_VENDOR_ID",
    "allocation_omni_sf".omni_small_package_flag AS "omni_small_package_flag",
    "allocation_omni_sf"."SALES_ALLOCATE" AS "SALES_ALLOCATE",
    "allocation_omni_sf"."COST_ALLOCATE" AS "COST_ALLOCATE",
    "allocation_omni_sf".tsc_delivery_final AS "tsc_delivery_final",
    "allocation_omni_sf".omni_roadie_final AS "omni_roadie_final",
    "allocation_omni_sf".small_package_ltl_final AS "small_package_ltl_final",
    "allocation_omni_sf".omni_small_package_ltl_dropout_final AS "omni_small_package_ltl_dropout_final",
    "allocation_omni_sf".roadie_dropout_final AS "roadie_dropout_final",
    "allocation_omni_sf".multichannel_salvage AS "multichannel_salvage",
    "allocation_omni_sf".tsc_delivery_final_l2 AS "tsc_delivery_final_l2",
    "allocation_omni_sf".omni_small_package_ltl_dropout_final_l2 AS "omni_small_package_ltl_dropout_final_l2",
    "allocation_omni_sf".roadie_dropout_final_l2 AS "roadie_dropout_final_l2",
    "allocation_omni_sf".multichannel_salvage_l2 AS "multichannel_salvage_l2",
    "tsc_delivery_order_cost"."tsc_delivery_cost" AS "tsc_delivery_cost"
  FROM "ALLOCATION_OMNI" "allocation_omni_sf"
  LEFT JOIN (SELECT  *,
             CASE WHEN "total_orders" = 0 THEN 0 ELSE  "allocation_value"/"total_orders" END AS "tsc_delivery_cost"
             FROM CTE
             )"tsc_delivery_order_cost"
      ON ("allocation_omni_sf".tsc_delivery_flag = "tsc_delivery_order_cost"."tsc_delivery_flag")
      AND ("allocation_omni_sf"."YEAR_PERIOD" = "tsc_delivery_order_cost"."YEAR_PERIOD")
  ;

<br>  
--FINAL QUERY FOR OMNI_SALES_GRP
</br>
insert into "OMNI_SALES_GRP"
WITH CTE AS (
SELECT *, CASE WHEN COALESCE("total_weight_sum", 0) = 0 THEN 0 ELSE "total_weight" / NULLIF("total_weight_sum", 0) END AS "weight_share"
FROM (
SELECT 
    "ARTICLE_NO" AS "ARTICLE_NO",
    "MERCH_YEAR" AS "MERCH_YEAR",
    "tsc_delivery_flag" AS "tsc_delivery_flag",
    "YEAR_PERIOD" AS "YEAR_PERIOD",
    "OMS_ORDER_LINE_KEY" AS "OMS_ORDER_LINE_KEY",
    "roadie_flag" AS "roadie_flag",
    "ACCT_YEAR" AS "ACCT_YEAR",
    "YEAR_WEEK" AS "YEAR_WEEK",
    "OMS_ORDER_NO" AS "OMS_ORDER_NO",
    "VENDOR_ID" AS "VENDOR_ID",
    "OMS_ORDER_LINE_SCHEDULE_SHIP_NODE" AS "OMS_ORDER_LINE_SCHEDULE_SHIP_NODE",
    "OMS_SHIP_NODE_DESC" AS "OMS_SHIP_NODE_DESC",
    "ARTICLE_CAT_FULL" AS "ARTICLE_CAT_FULL",
    "DEMAND_QTY" AS "DEMAND_QTY",
    "DEMAND_SALES" AS "DEMAND_SALES",
    "BOOKED_SALES_QTY" AS "BOOKED_SALES_QTY",
    "BOOKED_SALES_AMT" AS "BOOKED_SALES_AMT",
    "BOOKED_COST_AMT" AS "BOOKED_COST_AMT",
    "SHIPPING_REVENUE" AS "SHIPPING_REVENUE",
    "SHIPPING_DISC" AS "SHIPPING_DISC",
    "ACTUAL_SHIPPING_REVENUE" AS "ACTUAL_SHIPPING_REVENUE",
    "ORDER_LINE_TYPE" AS "ORDER_LINE_TYPE",
    "SCAC" AS "SCAC",
    "SHIP_NODE_TYPE" AS "SHIP_NODE_TYPE",
    "YEAR_QUARTER" AS "YEAR_QUARTER",
    "CHAIN_PROD" AS "CHAIN_PROD",
    "ARTICLE_DESC" AS "ARTICLE_DESC",
    "ARTICLE_FULL" AS "ARTICLE_FULL",
    "ARTICLE_TYPE_NAME" AS "ARTICLE_TYPE_NAME",
    "ARTICLE_TYPE_CODE" AS "ARTICLE_TYPE_CODE",
    "ARTICLE_TYPE_FULL" AS "ARTICLE_TYPE_FULL",
    "ARTICLE_LENGTH" AS "ARTICLE_LENGTH",
    "ARTICLE_WIDTH" AS "ARTICLE_WIDTH",
    "ARTICLE_HEIGHT" AS "ARTICLE_HEIGHT",
    "ARTICLE_WEIGHT" AS "ARTICLE_WEIGHT",
    "total_weight" AS "total_weight",
    "ARTICLE_SIZE" AS "ARTICLE_SIZE",
    "ARTICLE_COUNT" AS "ARTICLE_COUNT",
    "ARTICLE_COLOR" AS "ARTICLE_COLOR",
    "PARENT_ARTICLE_NO" AS "PARENT_ARTICLE_NO",
    "PARENT_ARTICLE_DESC" AS "PARENT_ARTICLE_DESC",
    "PARENT_ARTICLE_FULL" AS "PARENT_ARTICLE_FULL",
    "PRIMARY_VENDOR_ID" AS "PRIMARY_VENDOR_ID",
    "ARTICLE_CAT_CODE" AS "ARTICLE_CAT_CODE",
    "ARTICLE_CAT_NAME" AS "ARTICLE_CAT_NAME",
    "DEPT_CODE" AS "DEPT_CODE",
    "DEPT_NAME" AS "DEPT_NAME",
    "DEPT_FULL" AS "DEPT_FULL",
    "LOB_NO" AS "LOB_NO",
    "LOB_DESC" AS "LOB_DESC",
    "LOB_FULL" AS "LOB_FULL",
    "MAJ_DEPT_NO" AS "MAJ_DEPT_NO",
    "MAJ_DEPT_DESC" AS "MAJ_DEPT_DESC",
    "MAJ_DEPT_FULL" AS "MAJ_DEPT_FULL",
    "BRAND_NAME" AS "BRAND_NAME",
    "PVT_LABEL_DESC" AS "PVT_LABEL_DESC",
    "VENDOR_NAME" AS "VENDOR_NAME",
    "VENDOR_FULL" AS "VENDOR_FULL",
    "PARENT_VENDOR_ID" AS "PARENT_VENDOR_ID",
    "omni_small_package_flag" AS "omni_small_package_flag",
    "SALES_ALLOCATE" AS "SALES_ALLOCATE",
    "COST_ALLOCATE" AS "COST_ALLOCATE",
    "tsc_delivery_final" AS "tsc_delivery_final",
    "omni_roadie_final" AS "omni_roadie_final",
    "small_package_ltl_final" AS "small_package_ltl_final",
    "omni_small_package_ltl_dropout_final" AS "omni_small_package_ltl_dropout_final",
    "roadie_dropout_final" AS "roadie_dropout_final",
    "multichannel_salvage" AS "multichannel_salvage",
    "tsc_delivery_final_l2" AS "tsc_delivery_final_l2",
    "omni_small_package_ltl_dropout_final_l2" AS "omni_small_package_ltl_dropout_final_l2",
    "roadie_dropout_final_l2" AS "roadie_dropout_final_l2",
    "multichannel_salvage_l2" AS "multichannel_salvage_l2",
    "total_weight_sum" AS "total_weight_sum",
    "tsc_delivery_cost_max" AS "tsc_delivery_cost"
  FROM (
    SELECT 
        "ARTICLE_NO" AS "ARTICLE_NO",
        "MERCH_YEAR" AS "MERCH_YEAR",
        "tsc_delivery_flag" AS "tsc_delivery_flag",
        "YEAR_PERIOD" AS "YEAR_PERIOD",
        "OMS_ORDER_LINE_KEY" AS "OMS_ORDER_LINE_KEY",
        "roadie_flag" AS "roadie_flag",
        "ACCT_YEAR" AS "ACCT_YEAR",
        "YEAR_WEEK" AS "YEAR_WEEK",
        "OMS_ORDER_NO" AS "OMS_ORDER_NO",
        "VENDOR_ID" AS "VENDOR_ID",
        "OMS_ORDER_LINE_SCHEDULE_SHIP_NODE" AS "OMS_ORDER_LINE_SCHEDULE_SHIP_NODE",
        "OMS_SHIP_NODE_DESC" AS "OMS_SHIP_NODE_DESC",
        "ARTICLE_CAT_FULL" AS "ARTICLE_CAT_FULL",
        "DEMAND_QTY" AS "DEMAND_QTY",
        "DEMAND_SALES" AS "DEMAND_SALES",
        "BOOKED_SALES_QTY" AS "BOOKED_SALES_QTY",
        "BOOKED_SALES_AMT" AS "BOOKED_SALES_AMT",
        "BOOKED_COST_AMT" AS "BOOKED_COST_AMT",
        "SHIPPING_REVENUE" AS "SHIPPING_REVENUE",
        "SHIPPING_DISC" AS "SHIPPING_DISC",
        "ACTUAL_SHIPPING_REVENUE" AS "ACTUAL_SHIPPING_REVENUE",
        "ORDER_LINE_TYPE" AS "ORDER_LINE_TYPE",
        "SCAC" AS "SCAC",
        "SHIP_NODE_TYPE" AS "SHIP_NODE_TYPE",
        "YEAR_QUARTER" AS "YEAR_QUARTER",
        "CHAIN_PROD" AS "CHAIN_PROD",
        "ARTICLE_DESC" AS "ARTICLE_DESC",
        "ARTICLE_FULL" AS "ARTICLE_FULL",
        "ARTICLE_TYPE_NAME" AS "ARTICLE_TYPE_NAME",
        "ARTICLE_TYPE_CODE" AS "ARTICLE_TYPE_CODE",
        "ARTICLE_TYPE_FULL" AS "ARTICLE_TYPE_FULL",
        "ARTICLE_LENGTH" AS "ARTICLE_LENGTH",
        "ARTICLE_WIDTH" AS "ARTICLE_WIDTH",
        "ARTICLE_HEIGHT" AS "ARTICLE_HEIGHT",
        "ARTICLE_WEIGHT" AS "ARTICLE_WEIGHT",
        "total_weight_1" AS "total_weight",
        "ARTICLE_SIZE" AS "ARTICLE_SIZE",
        "ARTICLE_COUNT" AS "ARTICLE_COUNT",
        "ARTICLE_COLOR" AS "ARTICLE_COLOR",
        "PARENT_ARTICLE_NO" AS "PARENT_ARTICLE_NO",
        "PARENT_ARTICLE_DESC" AS "PARENT_ARTICLE_DESC",
        "PARENT_ARTICLE_FULL" AS "PARENT_ARTICLE_FULL",
        "PRIMARY_VENDOR_ID" AS "PRIMARY_VENDOR_ID",
        "ARTICLE_CAT_CODE" AS "ARTICLE_CAT_CODE",
        "ARTICLE_CAT_NAME" AS "ARTICLE_CAT_NAME",
        "DEPT_CODE" AS "DEPT_CODE",
        "DEPT_NAME" AS "DEPT_NAME",
        "DEPT_FULL" AS "DEPT_FULL",
        "LOB_NO" AS "LOB_NO",
        "LOB_DESC" AS "LOB_DESC",
        "LOB_FULL" AS "LOB_FULL",
        "MAJ_DEPT_NO" AS "MAJ_DEPT_NO",
        "MAJ_DEPT_DESC" AS "MAJ_DEPT_DESC",
        "MAJ_DEPT_FULL" AS "MAJ_DEPT_FULL",
        "BRAND_NAME" AS "BRAND_NAME",
        "PVT_LABEL_DESC" AS "PVT_LABEL_DESC",
        "VENDOR_NAME" AS "VENDOR_NAME",
        "VENDOR_FULL" AS "VENDOR_FULL",
        "PARENT_VENDOR_ID" AS "PARENT_VENDOR_ID",
        "omni_small_package_flag" AS "omni_small_package_flag",
        "SALES_ALLOCATE" AS "SALES_ALLOCATE",
        "COST_ALLOCATE" AS "COST_ALLOCATE",
        "tsc_delivery_final" AS "tsc_delivery_final",
        "omni_roadie_final" AS "omni_roadie_final",
        "small_package_ltl_final" AS "small_package_ltl_final",
        "omni_small_package_ltl_dropout_final" AS "omni_small_package_ltl_dropout_final",
        "roadie_dropout_final" AS "roadie_dropout_final",
        "multichannel_salvage" AS "multichannel_salvage",
        "tsc_delivery_final_l2" AS "tsc_delivery_final_l2",
        "omni_small_package_ltl_dropout_final_l2" AS "omni_small_package_ltl_dropout_final_l2",
        "roadie_dropout_final_l2" AS "roadie_dropout_final_l2",
        "multichannel_salvage_l2" AS "multichannel_salvage_l2",
        SUM("total_weight_1") OVER (PARTITION BY "OMS_ORDER_NO", "tsc_delivery_flag") AS "total_weight_sum",
        MAX("tsc_delivery_cost") OVER (PARTITION BY "OMS_ORDER_NO", "tsc_delivery_flag") AS "tsc_delivery_cost_max"
      FROM (
            select  *,
              TRY_CAST("total_weight" AS NUMBER) AS "total_weight_1"
              from "ALLOCATION_OMNI_SF_JOINED_WINDOWS")dku
    ) "pristine_query")A
    )

    SELECT 
        "ARTICLE_NO" AS "ARTICLE_NO",
        "MERCH_YEAR" AS "MERCH_YEAR",
        "VENDOR_ID" AS "VENDOR_ID",
        "YEAR_PERIOD" AS "YEAR_PERIOD",
        "ARTICLE_DESC" AS "ARTICLE_DESC",
        "ARTICLE_SIZE" AS "ARTICLE_SIZE",
        "MAJ_DEPT_DESC" AS "MAJ_DEPT_DESC",
        "BRAND_NAME" AS "BRAND_NAME",
        "PARENT_VENDOR_ID" AS "PARENT_VENDOR_ID",
        "VENDOR_NAME" AS "VENDOR_NAME",
        "YEAR_QUARTER" AS "YEAR_QUARTER",
        "YEAR_WEEK" AS "YEAR_WEEK",
        "ARTICLE_FULL" AS "ARTICLE_FULL",
        "ARTICLE_CAT_CODE" AS "ARTICLE_CAT_CODE",
        "ARTICLE_CAT_NAME" AS "ARTICLE_CAT_NAME",
        "ARTICLE_CAT_FULL" AS "ARTICLE_CAT_FULL",
        "DEPT_CODE" AS "DEPT_CODE",
        "DEPT_NAME" AS "DEPT_NAME",
        "DEPT_FULL" AS "DEPT_FULL",
        "LOB_NO" AS "LOB_NO",
        "LOB_DESC" AS "LOB_DESC",
        "LOB_FULL" AS "LOB_FULL",
        "MAJ_DEPT_NO" AS "MAJ_DEPT_NO",
        "MAJ_DEPT_FULL" AS "MAJ_DEPT_FULL",
        "PVT_LABEL_DESC" AS "PVT_LABEL_DESC",
        "VENDOR_FULL" AS "VENDOR_FULL",
        "PRIMARY_VENDOR_ID" AS "PRIMARY_VENDOR_ID",
        "ORDER_LINE_TYPE" AS "ORDER_LINE_TYPE",
        "SCAC" AS "SCAC",
        "OMS_ORDER_LINE_SCHEDULE_SHIP_NODE" AS "OMS_ORDER_LINE_SCHEDULE_SHIP_NODE",
        SUM("BOOKED_SALES_QTY") AS "SALES_QTY",
        SUM("BOOKED_SALES_AMT") AS "SALES_AMT",
        SUM("BOOKED_COST_AMT") AS "COST_AMT",
        SUM("SHIPPING_REVENUE") AS "SHIPPING_REVENUE",
        SUM("SHIPPING_DISC") AS "SHIPPING_DISC_sum",
        SUM("ACTUAL_SHIPPING_REVENUE") AS "ACTUAL_SHIPPING_REVENUE",
        SUM("SALES_ALLOCATE") AS "SALES_ALLOCATE",
        SUM("COST_ALLOCATE") AS "COST_ALLOCATE",
        SUM("tsc_delivery_combined") AS "tsc_delivery_combined",
        SUM("omni_small_package_ltl_comb") AS "omni_small_package_ltl_comb",
        SUM("roadie_combined") AS "roadie_combined",
        SUM("multi_salvage_combined") AS "multi_salvage_combined"
    FROM (
    SELECT *, COALESCE("tsc_delivery", 0) AS "tsc_delivery_combined",
            COALESCE("small_package_ltl_final", 0) + COALESCE("omni_small_package_ltl_dropout_final", 0) +                 
            COALESCE("omni_small_package_ltl_dropout_final_l2", 0) AS "omni_small_package_ltl_comb",
            COALESCE("omni_roadie_final", 0) + COALESCE("roadie_dropout_final", 0) + COALESCE("roadie_dropout_final_l2", 0) AS "roadie_combined",
            COALESCE("multichannel_salvage", 0) + COALESCE("multichannel_salvage_l2", 0) AS "multi_salvage_combined"
            FROM (
    SELECT 
    "ARTICLE_NO",
    "MERCH_YEAR",
    "tsc_delivery_flag",
    "YEAR_PERIOD",
    "OMS_ORDER_LINE_KEY",
    "roadie_flag",
    "ACCT_YEAR",
    "YEAR_WEEK",
    "OMS_ORDER_NO",
    "VENDOR_ID",
    "OMS_ORDER_LINE_SCHEDULE_SHIP_NODE",
    "OMS_SHIP_NODE_DESC",
    "ARTICLE_CAT_FULL",
    "DEMAND_QTY",
    "DEMAND_SALES",
    "BOOKED_SALES_QTY",
    "BOOKED_SALES_AMT",
    "BOOKED_COST_AMT",
    "SHIPPING_REVENUE",
    "SHIPPING_DISC",
    "ACTUAL_SHIPPING_REVENUE",
    "ORDER_LINE_TYPE",
    "SCAC",
    "SHIP_NODE_TYPE",
    "YEAR_QUARTER",
    "CHAIN_PROD",
    "ARTICLE_DESC",
    "ARTICLE_FULL",
    "ARTICLE_TYPE_NAME",
    "ARTICLE_TYPE_CODE",
    "ARTICLE_TYPE_FULL",
    "ARTICLE_LENGTH",
    "ARTICLE_WIDTH",
    "ARTICLE_HEIGHT",
    "ARTICLE_WEIGHT",
    "total_weight",
    "ARTICLE_SIZE",
    "ARTICLE_COUNT",
    "ARTICLE_COLOR",
    "PARENT_ARTICLE_NO",
    "PARENT_ARTICLE_DESC",
    "PARENT_ARTICLE_FULL",
    "PRIMARY_VENDOR_ID",
    "ARTICLE_CAT_CODE",
    "ARTICLE_CAT_NAME",
    "DEPT_CODE",
    "DEPT_NAME",
    "DEPT_FULL",
    "LOB_NO",
    "LOB_DESC",
    "LOB_FULL",
    "MAJ_DEPT_NO",
    "MAJ_DEPT_DESC",
    "MAJ_DEPT_FULL",
    "BRAND_NAME",
    "PVT_LABEL_DESC",
    "VENDOR_NAME",
    "VENDOR_FULL",
    "PARENT_VENDOR_ID",
    "omni_small_package_flag",
    "SALES_ALLOCATE",
    "COST_ALLOCATE",
    "tsc_delivery_final",
    "omni_roadie_final",
    "small_package_ltl_final",
    "omni_small_package_ltl_dropout_final",
    "roadie_dropout_final",
    "multichannel_salvage",
    "tsc_delivery_final_l2",
    "omni_small_package_ltl_dropout_final_l2",
    "roadie_dropout_final_l2",
    "multichannel_salvage_l2",
    "total_weight_sum",
    "tsc_delivery_cost",
    "weight_share",
    COALESCE("weight_share", 0) * COALESCE("tsc_delivery_cost", 0) AS "tsc_delivery"
    FROM CTE )"dku__beforegrouping" 
    )FINAL 
    GROUP BY "ARTICLE_NO", "MERCH_YEAR", "VENDOR_ID", "YEAR_PERIOD", "ARTICLE_DESC", "ARTICLE_SIZE", "MAJ_DEPT_DESC", "BRAND_NAME", "PARENT_VENDOR_ID", "VENDOR_NAME", "YEAR_QUARTER", "YEAR_WEEK", "ARTICLE_FULL", "ARTICLE_CAT_CODE", "ARTICLE_CAT_NAME", "ARTICLE_CAT_FULL", "DEPT_CODE", "DEPT_NAME", "DEPT_FULL", "LOB_NO", "LOB_DESC", "LOB_FULL", "MAJ_DEPT_NO", "MAJ_DEPT_FULL", "PVT_LABEL_DESC", "VENDOR_FULL", "PRIMARY_VENDOR_ID", "ORDER_LINE_TYPE", "SCAC", "OMS_ORDER_LINE_SCHEDULE_SHIP_NODE";
 
  
<br>
  /*master_sales_round */
 --SALES_W_PAR_VENDOR_JOINED
</br>

CREATE OR REPLACE TEMPORARY TABLE "SALES_W_PAR_VENDOR_JOINED"
(
    "CO_CODE",
    "ARTICLE_NO",
    "SUM_TYPE_CODE",
    "VENDOR_ID",
    "PRICE_OVRD_FLAG",
    "SCAN_ITEM_FLAG",
    "PRICE_TYPE_CODE",
    "BUY_ONLINE_CODE",
    "MERCH_YEAR",
    "YEAR_WEEK",
    "YEAR_QUARTER",
    "YEAR_PERIOD",
    "ARTICLE_DESC",
    "ARTICLE_FULL",
    "ARTICLE_TYPE_NAME",
    "ARTICLE_TYPE_CODE",
    "ARTICLE_TYPE_FULL",
    "LABEL_TYPE_CODE",
    "UOM_CODE",
    "UOM_DESC",
    "UOM_FULL",
    "ARTICLE_LENGTH",
    "ARTICLE_WIDTH",
    "ARTICLE_HEIGHT",
    "ARTICLE_WEIGHT",
    "ARTICLE_SIZE",
    "ARTICLE_COUNT",
    "LOC_TYPE_CODE",
    "PRIMARY_VENDOR_ID",
    "ARTICLE_CAT_CODE",
    "ARTICLE_CAT_NAME",
    "ARTICLE_CAT_FULL",
    "DEPT_CODE",
    "DEPT_NAME",
    "DEPT_FULL",
    "LOB_NO",
    "LOB_DESC",
    "LOB_FULL",
    "MAJ_DEPT_NO",
    "MAJ_DEPT_DESC",
    "MAJ_DEPT_FULL",
    "BRAND_NAME",
    "PVT_LABEL_DESC",
    "VENDOR_NAME",
    "VENDOR_FULL",
    "VENDOR_CO_NAME",
    "REGION_CODE",
    "SALES_QTY",
    "SALES_AMT",
    "COST_AMT",
    "DISC_AMT",
    "OVRD_AMT",
    "TRANS_TAX_AMT",
    "GROSS_SALES",
    "PARENT_VENDOR_ID",
    "ORDER_LINE_TYPE",
    "SCAC",
    "OMS_ORDER_LINE_SCHEDULE_SHIP_NODE",
    "SHIPPING_REVENUE",
    "SHIPPING_DISC",
    "ACTUAL_SHIPPING_REVENUE",
    "SALES_ALLOCATE",
    "COST_ALLOCATE",
    "omni_tsc_delivery",
    "omni_small_package_ltl",
    "omni_roadie",
    "0mni_multi_salvage",
    "battery_cost",
    "battery_core_flag",
    "scandown_flag",
    "cash_discount_flag"
)as
WITH CTE AS (
SELECT 
    "CO_CODE" AS "CO_CODE",
    "ARTICLE_NO" AS "ARTICLE_NO",
    "SUM_TYPE_CODE" AS "SUM_TYPE_CODE",
    "VENDOR_ID" AS "VENDOR_ID",
    "PRICE_OVRD_FLAG" AS "PRICE_OVRD_FLAG",
    "SCAN_ITEM_FLAG" AS "SCAN_ITEM_FLAG",
    "PRICE_TYPE_CODE" AS "PRICE_TYPE_CODE",
    "BUY_ONLINE_CODE" AS "BUY_ONLINE_CODE",
    "MERCH_YEAR" AS "MERCH_YEAR",
    "YEAR_WEEK" AS "YEAR_WEEK",
    "YEAR_QUARTER" AS "YEAR_QUARTER",
    "YEAR_PERIOD" AS "YEAR_PERIOD",
    "ARTICLE_DESC" AS "ARTICLE_DESC",
    "ARTICLE_FULL" AS "ARTICLE_FULL",
    "ARTICLE_TYPE_NAME" AS "ARTICLE_TYPE_NAME",
    "ARTICLE_TYPE_CODE" AS "ARTICLE_TYPE_CODE",
    "ARTICLE_TYPE_FULL" AS "ARTICLE_TYPE_FULL",
    "LABEL_TYPE_CODE" AS "LABEL_TYPE_CODE",
    "UOM_CODE" AS "UOM_CODE",
    "UOM_DESC" AS "UOM_DESC",
    "UOM_FULL" AS "UOM_FULL",
    "ARTICLE_LENGTH" AS "ARTICLE_LENGTH",
    "ARTICLE_WIDTH" AS "ARTICLE_WIDTH",
    "ARTICLE_HEIGHT" AS "ARTICLE_HEIGHT",
    "ARTICLE_WEIGHT" AS "ARTICLE_WEIGHT",
    "ARTICLE_SIZE" AS "ARTICLE_SIZE",
    "ARTICLE_COUNT" AS "ARTICLE_COUNT",
    "LOC_TYPE_CODE" AS "LOC_TYPE_CODE",
    "PRIMARY_VENDOR_ID" AS "PRIMARY_VENDOR_ID",
    "ARTICLE_CAT_CODE" AS "ARTICLE_CAT_CODE",
    "ARTICLE_CAT_NAME" AS "ARTICLE_CAT_NAME",
    "ARTICLE_CAT_FULL" AS "ARTICLE_CAT_FULL",
    "DEPT_CODE" AS "DEPT_CODE",
    "DEPT_NAME" AS "DEPT_NAME",
    "DEPT_FULL" AS "DEPT_FULL",
    "LOB_NO" AS "LOB_NO",
    "LOB_DESC" AS "LOB_DESC",
    "LOB_FULL" AS "LOB_FULL",
    "MAJ_DEPT_NO" AS "MAJ_DEPT_NO",
    "MAJ_DEPT_DESC" AS "MAJ_DEPT_DESC",
    "MAJ_DEPT_FULL" AS "MAJ_DEPT_FULL",
    "BRAND_NAME" AS "BRAND_NAME",
    "PVT_LABEL_DESC" AS "PVT_LABEL_DESC",
    "VENDOR_NAME" AS "VENDOR_NAME",
    "VENDOR_FULL" AS "VENDOR_FULL",
    "VENDOR_CO_NAME" AS "VENDOR_CO_NAME",
    "REGION_CODE" AS "REGION_CODE",
    "SALES_QTY" AS "SALES_QTY",
    "SALES_AMT" AS "SALES_AMT",
    "COST_AMT" AS "COST_AMT",
    "DISC_AMT" AS "DISC_AMT",
    "OVRD_AMT" AS "OVRD_AMT",
    "TRANS_TAX_AMT" AS "TRANS_TAX_AMT",
    "gross_sales" AS "GROSS_SALES",
    "PARENT_VENDOR_ID" AS "PARENT_VENDOR_ID",
    NULL AS "ORDER_LINE_TYPE",
    NULL AS "SCAC",
    NULL AS "OMS_ORDER_LINE_SCHEDULE_SHIP_NODE",
    NULL AS "SHIPPING_REVENUE",
    NULL AS "SHIPPING_DISC",
    NULL AS "ACTUAL_SHIPPING_REVENUE",
    NULL AS "SALES_ALLOCATE",
    NULL AS "COST_ALLOCATE",
    NULL AS "omni_tsc_delivery",
    NULL AS "omni_small_package_ltl",
    NULL AS "omni_roadie",
    NULL AS "0mni_multi_salvage"
  FROM "SALES_W_PAR_VENDOR"
UNION ALL
SELECT 
    NULL AS "CO_CODE",
    "ARTICLE_NO" AS "ARTICLE_NO",
    NULL AS "SUM_TYPE_CODE",
    "VENDOR_ID" AS "VENDOR_ID",
    NULL AS "PRICE_OVRD_FLAG",
    NULL AS "SCAN_ITEM_FLAG",
    NULL AS "PRICE_TYPE_CODE",
    NULL AS "BUY_ONLINE_CODE",
    "MERCH_YEAR" AS "MERCH_YEAR",
    "YEAR_WEEK" AS "YEAR_WEEK",
    "YEAR_QUARTER" AS "YEAR_QUARTER",
    "YEAR_PERIOD" AS "YEAR_PERIOD",
    "ARTICLE_DESC" AS "ARTICLE_DESC",
    "ARTICLE_FULL" AS "ARTICLE_FULL",
    NULL AS "ARTICLE_TYPE_NAME",
    NULL AS "ARTICLE_TYPE_CODE",
    NULL AS "ARTICLE_TYPE_FULL",
    NULL AS "LABEL_TYPE_CODE",
    NULL AS "UOM_CODE",
    NULL AS "UOM_DESC",
    NULL AS "UOM_FULL",
    NULL AS "ARTICLE_LENGTH",
    NULL AS "ARTICLE_WIDTH",
    NULL AS "ARTICLE_HEIGHT",
    NULL AS "ARTICLE_WEIGHT",
    "ARTICLE_SIZE" AS "ARTICLE_SIZE",
    NULL AS "ARTICLE_COUNT",
    NULL AS "LOC_TYPE_CODE",
    "PRIMARY_VENDOR_ID" AS "PRIMARY_VENDOR_ID",
    "ARTICLE_CAT_CODE" AS "ARTICLE_CAT_CODE",
    "ARTICLE_CAT_NAME" AS "ARTICLE_CAT_NAME",
    "ARTICLE_CAT_FULL" AS "ARTICLE_CAT_FULL",
    "DEPT_CODE" AS "DEPT_CODE",
    "DEPT_NAME" AS "DEPT_NAME",
    "DEPT_FULL" AS "DEPT_FULL",
    "LOB_NO" AS "LOB_NO",
    "LOB_DESC" AS "LOB_DESC",
    "LOB_FULL" AS "LOB_FULL",
    "MAJ_DEPT_NO" AS "MAJ_DEPT_NO",
    "MAJ_DEPT_DESC" AS "MAJ_DEPT_DESC",
    "MAJ_DEPT_FULL" AS "MAJ_DEPT_FULL",
    "BRAND_NAME" AS "BRAND_NAME",
    "PVT_LABEL_DESC" AS "PVT_LABEL_DESC",
    "VENDOR_NAME" AS "VENDOR_NAME",
    "VENDOR_FULL" AS "VENDOR_FULL",
    NULL AS "VENDOR_CO_NAME",
    NULL AS "REGION_CODE",
    "SALES_QTY" AS "SALES_QTY",
    "SALES_AMT" AS "SALES_AMT",
    "COST_AMT" AS "COST_AMT",
    NULL AS "DISC_AMT",
    NULL AS "OVRD_AMT",
    NULL AS "TRANS_TAX_AMT",
    NULL AS "GROSS_SALES",
    "PARENT_VENDOR_ID" AS "PARENT_VENDOR_ID",
    "ORDER_LINE_TYPE" AS "ORDER_LINE_TYPE",
    "SCAC" AS "SCAC",
    "OMS_ORDER_LINE_SCHEDULE_SHIP_NODE" AS "OMS_ORDER_LINE_SCHEDULE_SHIP_NODE",
    "SHIPPING_REVENUE" AS "SHIPPING_REVENUE",
    "SHIPPING_DISC_sum" AS "SHIPPING_DISC",
    "ACTUAL_SHIPPING_REVENUE" AS "ACTUAL_SHIPPING_REVENUE",
    "SALES_ALLOCATE" AS "SALES_ALLOCATE",
    "COST_ALLOCATE" AS "COST_ALLOCATE",
    "tsc_delivery_combined" AS "omni_tsc_delivery",
    "omni_small_package_ltl_comb" AS "omni_small_package_ltl",
    "roadie_combined" AS "omni_roadie",
    "multi_salvage_combined" AS "0mni_multi_salvage"
  FROM "OMNI_SALES_GRP"
  WHERE ("ORDER_LINE_TYPE" = 'BODFS') OR ("ORDER_LINE_TYPE" = 'BOPIS')
  )
  SELECT DISTINCT
    "TENANT149_sales_w_par_vendor_stacked"."CO_CODE" AS "CO_CODE",
    "TENANT149_sales_w_par_vendor_stacked"."ARTICLE_NO" AS "ARTICLE_NO",
    "TENANT149_sales_w_par_vendor_stacked"."SUM_TYPE_CODE" AS "SUM_TYPE_CODE",
    "TENANT149_sales_w_par_vendor_stacked"."VENDOR_ID" AS "VENDOR_ID",
    "TENANT149_sales_w_par_vendor_stacked"."PRICE_OVRD_FLAG" AS "PRICE_OVRD_FLAG",
    "TENANT149_sales_w_par_vendor_stacked"."SCAN_ITEM_FLAG" AS "SCAN_ITEM_FLAG",
    "TENANT149_sales_w_par_vendor_stacked"."PRICE_TYPE_CODE" AS "PRICE_TYPE_CODE",
    "TENANT149_sales_w_par_vendor_stacked"."BUY_ONLINE_CODE" AS "BUY_ONLINE_CODE",
    "TENANT149_sales_w_par_vendor_stacked"."MERCH_YEAR" AS "MERCH_YEAR",
    "TENANT149_sales_w_par_vendor_stacked"."YEAR_WEEK" AS "YEAR_WEEK",
    "TENANT149_sales_w_par_vendor_stacked"."YEAR_QUARTER" AS "YEAR_QUARTER",
    "TENANT149_sales_w_par_vendor_stacked"."YEAR_PERIOD" AS "YEAR_PERIOD",
    "TENANT149_sales_w_par_vendor_stacked"."ARTICLE_DESC" AS "ARTICLE_DESC",
    "TENANT149_sales_w_par_vendor_stacked"."ARTICLE_FULL" AS "ARTICLE_FULL",
    "TENANT149_sales_w_par_vendor_stacked"."ARTICLE_TYPE_NAME" AS "ARTICLE_TYPE_NAME",
    "TENANT149_sales_w_par_vendor_stacked"."ARTICLE_TYPE_CODE" AS "ARTICLE_TYPE_CODE",
    "TENANT149_sales_w_par_vendor_stacked"."ARTICLE_TYPE_FULL" AS "ARTICLE_TYPE_FULL",
    "TENANT149_sales_w_par_vendor_stacked"."LABEL_TYPE_CODE" AS "LABEL_TYPE_CODE",
    "TENANT149_sales_w_par_vendor_stacked"."UOM_CODE" AS "UOM_CODE",
    "TENANT149_sales_w_par_vendor_stacked"."UOM_DESC" AS "UOM_DESC",
    "TENANT149_sales_w_par_vendor_stacked"."UOM_FULL" AS "UOM_FULL",
    "TENANT149_sales_w_par_vendor_stacked"."ARTICLE_LENGTH" AS "ARTICLE_LENGTH",
    "TENANT149_sales_w_par_vendor_stacked"."ARTICLE_WIDTH" AS "ARTICLE_WIDTH",
    "TENANT149_sales_w_par_vendor_stacked"."ARTICLE_HEIGHT" AS "ARTICLE_HEIGHT",
    "TENANT149_sales_w_par_vendor_stacked"."ARTICLE_WEIGHT" AS "ARTICLE_WEIGHT",
    "TENANT149_sales_w_par_vendor_stacked"."ARTICLE_SIZE" AS "ARTICLE_SIZE",
    "TENANT149_sales_w_par_vendor_stacked"."ARTICLE_COUNT" AS "ARTICLE_COUNT",
    "TENANT149_sales_w_par_vendor_stacked"."LOC_TYPE_CODE" AS "LOC_TYPE_CODE",
    "TENANT149_sales_w_par_vendor_stacked"."PRIMARY_VENDOR_ID" AS "PRIMARY_VENDOR_ID",
    "TENANT149_sales_w_par_vendor_stacked"."ARTICLE_CAT_CODE" AS "ARTICLE_CAT_CODE",
    "TENANT149_sales_w_par_vendor_stacked"."ARTICLE_CAT_NAME" AS "ARTICLE_CAT_NAME",
    "TENANT149_sales_w_par_vendor_stacked"."ARTICLE_CAT_FULL" AS "ARTICLE_CAT_FULL",
    "TENANT149_sales_w_par_vendor_stacked"."DEPT_CODE" AS "DEPT_CODE",
    "TENANT149_sales_w_par_vendor_stacked"."DEPT_NAME" AS "DEPT_NAME",
    "TENANT149_sales_w_par_vendor_stacked"."DEPT_FULL" AS "DEPT_FULL",
    "TENANT149_sales_w_par_vendor_stacked"."LOB_NO" AS "LOB_NO",
    "TENANT149_sales_w_par_vendor_stacked"."LOB_DESC" AS "LOB_DESC",
    "TENANT149_sales_w_par_vendor_stacked"."LOB_FULL" AS "LOB_FULL",
    "TENANT149_sales_w_par_vendor_stacked"."MAJ_DEPT_NO" AS "MAJ_DEPT_NO",
    "TENANT149_sales_w_par_vendor_stacked"."MAJ_DEPT_DESC" AS "MAJ_DEPT_DESC",
    "TENANT149_sales_w_par_vendor_stacked"."MAJ_DEPT_FULL" AS "MAJ_DEPT_FULL",
    "TENANT149_sales_w_par_vendor_stacked"."BRAND_NAME" AS "BRAND_NAME",
    "TENANT149_sales_w_par_vendor_stacked"."PVT_LABEL_DESC" AS "PVT_LABEL_DESC",
    "TENANT149_sales_w_par_vendor_stacked"."VENDOR_NAME" AS "VENDOR_NAME",
    "TENANT149_sales_w_par_vendor_stacked"."VENDOR_FULL" AS "VENDOR_FULL",
    "TENANT149_sales_w_par_vendor_stacked"."VENDOR_CO_NAME" AS "VENDOR_CO_NAME",
    "TENANT149_sales_w_par_vendor_stacked"."REGION_CODE" AS "REGION_CODE",
    "TENANT149_sales_w_par_vendor_stacked"."SALES_QTY" AS "SALES_QTY",
    "TENANT149_sales_w_par_vendor_stacked"."SALES_AMT" AS "SALES_AMT",
    "TENANT149_sales_w_par_vendor_stacked"."COST_AMT" AS "COST_AMT",
    "TENANT149_sales_w_par_vendor_stacked"."DISC_AMT" AS "DISC_AMT",
    "TENANT149_sales_w_par_vendor_stacked"."OVRD_AMT" AS "OVRD_AMT",
    "TENANT149_sales_w_par_vendor_stacked"."TRANS_TAX_AMT" AS "TRANS_TAX_AMT",
    "TENANT149_sales_w_par_vendor_stacked"."GROSS_SALES" AS "GROSS_SALES",
    "TENANT149_sales_w_par_vendor_stacked"."PARENT_VENDOR_ID" AS "PARENT_VENDOR_ID",
    "TENANT149_sales_w_par_vendor_stacked"."ORDER_LINE_TYPE" AS "ORDER_LINE_TYPE",
    "TENANT149_sales_w_par_vendor_stacked"."SCAC" AS "SCAC",
    "TENANT149_sales_w_par_vendor_stacked"."OMS_ORDER_LINE_SCHEDULE_SHIP_NODE" AS "OMS_ORDER_LINE_SCHEDULE_SHIP_NODE",
    "TENANT149_sales_w_par_vendor_stacked"."SHIPPING_REVENUE" AS "SHIPPING_REVENUE",
    "TENANT149_sales_w_par_vendor_stacked"."SHIPPING_DISC" AS "SHIPPING_DISC",
    "TENANT149_sales_w_par_vendor_stacked"."ACTUAL_SHIPPING_REVENUE" AS "ACTUAL_SHIPPING_REVENUE",
    "TENANT149_sales_w_par_vendor_stacked"."SALES_ALLOCATE" AS "SALES_ALLOCATE",
    "TENANT149_sales_w_par_vendor_stacked"."COST_ALLOCATE" AS "COST_ALLOCATE",
    "TENANT149_sales_w_par_vendor_stacked"."omni_tsc_delivery" AS "omni_tsc_delivery",
    "TENANT149_sales_w_par_vendor_stacked"."omni_small_package_ltl" AS "omni_small_package_ltl",
    "TENANT149_sales_w_par_vendor_stacked"."omni_roadie" AS "omni_roadie",
    "TENANT149_sales_w_par_vendor_stacked"."0mni_multi_salvage" AS "0mni_multi_salvage",
    "Battery_Core_core_cost_prepared"."Core_Cost" AS "battery_cost",
    "Battery_Core_core_cost_prepared"."battery_core_flag" AS "battery_core_flag",
    "TENANT149_DATA_scandowns_flag_clean_by_year_period_new"."scandown_flag" AS "scandown_flag",
    "cash_discounts_prepared_filtered_by_Vendor"."cash_discount_flag" AS "cash_discount_flag"
  FROM CTE "TENANT149_sales_w_par_vendor_stacked"
  LEFT JOIN (
    SELECT DISTINCT
        "Article" AS "Article",
        "Description" AS "Description",
        "Core_Cost" AS "Core_Cost",
        "Warranty" AS "Warranty",
        "Part_no" AS "Part_no",
        1 AS "battery_core_flag"
      FROM (
        SELECT  *
          FROM "BATTERY_CORE_CORE_COST_PREPARED" "Battery_Core_core_cost_prepared"
        ) "withoutcomputedcols_query"
    ) "Battery_Core_core_cost_prepared"
    ON "TENANT149_sales_w_par_vendor_stacked"."ARTICLE_NO" = "Battery_Core_core_cost_prepared"."Article"
  LEFT JOIN (
    SELECT 
        "year_period_new" AS "year_period_new",
        "year" AS "year",
        "Vendor_No" AS "Vendor_No",
        "article_int" AS "article_int",
        1 AS "scandown_flag"
      FROM (
            SELECT 
            "year_period_new" AS "year_period_new",
            LEFT("year_period_new",4) AS "year",
            "Vendor_No" AS "Vendor_No",
            "article_int" AS "article_int"
              FROM  "SCANDOWNS_FLAG_CLEAN" 
              GROUP BY "year_period_new", "year", "Vendor_No", "article_int" 
        ) "withoutcomputedcols_query"
    ) "TENANT149_DATA_scandowns_flag_clean_by_year_period_new"
    ON ("TENANT149_sales_w_par_vendor_stacked"."YEAR_PERIOD" = "TENANT149_DATA_scandowns_flag_clean_by_year_period_new"."year_period_new")
      AND ("TENANT149_sales_w_par_vendor_stacked"."ARTICLE_NO" = "TENANT149_DATA_scandowns_flag_clean_by_year_period_new"."article_int")
      AND ("TENANT149_sales_w_par_vendor_stacked"."VENDOR_ID" = "TENANT149_DATA_scandowns_flag_clean_by_year_period_new"."Vendor_No")
  LEFT JOIN (
    SELECT 
        "Vendor" AS "Vendor",
        "Fiscal Year" AS "Fiscal Year",
        1 AS "cash_discount_flag"
      FROM (
           SELECT 
          "VENDOR" AS "Vendor",
           "FISCAL_YEAR" AS "Fiscal Year"
           FROM "CASH_DISCOUNTS_PREPARED_FILTERED"
           WHERE "VENDOR" IS NOT NULL AND "FISCAL_YEAR" IS NOT NULL
           GROUP BY "VENDOR", "Fiscal Year" 
        ) "withoutcomputedcols_query"
    ) "cash_discounts_prepared_filtered_by_Vendor"
    ON ("TENANT149_sales_w_par_vendor_stacked"."VENDOR_ID" = "cash_discounts_prepared_filtered_by_Vendor"."Vendor")
      AND ("TENANT149_sales_w_par_vendor_stacked"."MERCH_YEAR" = "cash_discounts_prepared_filtered_by_Vendor"."Fiscal Year");


<br>
-- MASTER_SALES_ROUND_SP 
</br>
INSERT INTO "MASTER_SALES_ROUND_SP"(
    "CO_CODE",
    "ARTICLE_NO",
    "SUM_TYPE_CODE",
    "VENDOR_ID",
    "PRICE_OVRD_FLAG",
    "SCAN_ITEM_FLAG",
    "PRICE_TYPE_CODE",
    "BUY_ONLINE_CODE",
    "MERCH_YEAR",
    "YEAR_WEEK",
    "YEAR_QUARTER",
    "YEAR_PERIOD",
    "ARTICLE_DESC",
    "ARTICLE_FULL",
    "ARTICLE_TYPE_NAME",
    "ARTICLE_TYPE_CODE",
    "ARTICLE_TYPE_FULL",
    "LABEL_TYPE_CODE",
    "UOM_CODE",
    "UOM_DESC",
    "UOM_FULL",
    "ARTICLE_LENGTH",
    "ARTICLE_WIDTH",
    "ARTICLE_HEIGHT",
    "ARTICLE_WEIGHT",
    "ARTICLE_SIZE",
    "ARTICLE_COUNT",
    "LOC_TYPE_CODE",
    "PRIMARY_VENDOR_ID",
    "ARTICLE_CAT_CODE",
    "ARTICLE_CAT_NAME",
    "ARTICLE_CAT_FULL",
    "DEPT_CODE",
    "DEPT_NAME",
    "DEPT_FULL",
    "LOB_NO",
    "LOB_DESC",
    "LOB_FULL",
    "MAJ_DEPT_NO",
    "MAJ_DEPT_DESC",
    "MAJ_DEPT_FULL",
    "BRAND_NAME",
    "PVT_LABEL_DESC",
    "VENDOR_NAME",
    "VENDOR_FULL",
    "VENDOR_CO_NAME",
    "REGION_CODE",
    "SALES_QTY",
    battery_cost_total,
    "SALES_AMT",
    markdown_perc,
    markdown_flag,
    "COST_AMT",
    "DISC_AMT",
    "OVRD_AMT",
    "TRANS_TAX_AMT",
    "GROSS_SALES",
    "PARENT_VENDOR_ID",
    "ORDER_LINE_TYPE",
    "SCAC",
    "OMS_ORDER_LINE_SCHEDULE_SHIP_NODE",
    "SHIPPING_REVENUE",
    "SHIPPING_DISC",
    "ACTUAL_SHIPPING_REVENUE",
    omni_tsc_delivery,
    omni_small_package_ltl,
    omni_roadie,
    _0mni_multi_salvage,
    battery_cost,
    battery_core_flag,
    scandown_flag,
    cash_discount_flag,
     SALES_ALLOCATE,
      COST_ALLOCATE
)
WITH CTE AS (
    SELECT 
        *,
        CASE WHEN "GROSS_SALES" > 0 AND "SALES_AMT" > 0 AND "GROSS_SALES" < "SALES_AMT" THEN 0 ELSE CASE WHEN "GROSS_SALES" < 0 AND "SALES_AMT" < 0 THEN 0 ELSE CASE WHEN "markdown_perc" > 0.1 OR "markdown_perc" < -0.1 THEN 1 ELSE 0 END END END AS "markdown_flag"
      FROM (
        SELECT 
            "CO_CODE",
            "ARTICLE_NO",
            "SUM_TYPE_CODE",
            "VENDOR_ID",
            "PRICE_OVRD_FLAG",
            "SCAN_ITEM_FLAG",
            "PRICE_TYPE_CODE",
            "BUY_ONLINE_CODE",
            "MERCH_YEAR",
            "YEAR_WEEK",
            "YEAR_QUARTER",
            "YEAR_PERIOD",
            "ARTICLE_DESC",
            "ARTICLE_FULL",
            "ARTICLE_TYPE_NAME",
            "ARTICLE_TYPE_CODE",
            "ARTICLE_TYPE_FULL",
            "LABEL_TYPE_CODE",
            "UOM_CODE",
            "UOM_DESC",
            "UOM_FULL",
            "ARTICLE_LENGTH",
            "ARTICLE_WIDTH",
            "ARTICLE_HEIGHT",
            "ARTICLE_WEIGHT",
            "ARTICLE_SIZE",
            "ARTICLE_COUNT",
            "LOC_TYPE_CODE",
            "PRIMARY_VENDOR_ID",
            "ARTICLE_CAT_CODE",
            "ARTICLE_CAT_NAME",
            "ARTICLE_CAT_FULL",
            "DEPT_CODE",
            "DEPT_NAME",
            "DEPT_FULL",
            "LOB_NO",
            "LOB_DESC",
            "LOB_FULL",
            "MAJ_DEPT_NO",
            "MAJ_DEPT_DESC",
            "MAJ_DEPT_FULL",
            "BRAND_NAME",
            "PVT_LABEL_DESC",
            "VENDOR_NAME",
            "VENDOR_FULL",
            "VENDOR_CO_NAME",
            "REGION_CODE",
            "SALES_QTY",
            "SALES_AMT",
            "COST_AMT",
            "DISC_AMT",
            "OVRD_AMT",
            "TRANS_TAX_AMT",
            "GROSS_SALES",
            cast("PARENT_VENDOR_ID" as numeric) AS "PARENT_VENDOR_ID",
            "ORDER_LINE_TYPE",
            "SCAC",
            "OMS_ORDER_LINE_SCHEDULE_SHIP_NODE",
            "SHIPPING_REVENUE",
            "SHIPPING_DISC",
            "ACTUAL_SHIPPING_REVENUE",
            "SALES_ALLOCATE",
            "COST_ALLOCATE",
            "omni_tsc_delivery",
            "omni_small_package_ltl",
            "omni_roadie",
            "0mni_multi_salvage",
            "battery_cost",
            "battery_core_flag",
            "scandown_flag",
            "cash_discount_flag",
            ROUND(COALESCE("battery_cost", 0) * COALESCE("SALES_QTY", 0) * 0.85, 0) AS "battery_cost_total",
            CASE WHEN ("GROSS_SALES" = 0) OR "GROSS_SALES" IS NULL OR ("SALES_AMT" = 0) THEN 0 ELSE "GROSS_SALES" / NULLIF("SALES_AMT", 0) - 1 END AS 
            "markdown_perc"
          FROM "SALES_W_PAR_VENDOR_JOINED" )A
          )
  SELECT 
    "CO_CODE" AS "CO_CODE",
    "ARTICLE_NO" AS "ARTICLE_NO",
    "SUM_TYPE_CODE" AS "SUM_TYPE_CODE",
    "VENDOR_ID" AS "VENDOR_ID",
    "PRICE_OVRD_FLAG" AS "PRICE_OVRD_FLAG",
    "SCAN_ITEM_FLAG" AS "SCAN_ITEM_FLAG",
    "PRICE_TYPE_CODE" AS "PRICE_TYPE_CODE",
    "BUY_ONLINE_CODE" AS "BUY_ONLINE_CODE",
    "MERCH_YEAR" AS "MERCH_YEAR",
    "YEAR_WEEK" AS "YEAR_WEEK",
    "YEAR_QUARTER" AS "YEAR_QUARTER",
    "YEAR_PERIOD" AS "YEAR_PERIOD",
    "ARTICLE_DESC" AS "ARTICLE_DESC",
    "ARTICLE_FULL" AS "ARTICLE_FULL",
    "ARTICLE_TYPE_NAME" AS "ARTICLE_TYPE_NAME",
    "ARTICLE_TYPE_CODE" AS "ARTICLE_TYPE_CODE",
    "ARTICLE_TYPE_FULL" AS "ARTICLE_TYPE_FULL",
    "LABEL_TYPE_CODE" AS "LABEL_TYPE_CODE",
    "UOM_CODE" AS "UOM_CODE",
    "UOM_DESC" AS "UOM_DESC",
    "UOM_FULL" AS "UOM_FULL",
    "ARTICLE_LENGTH" AS "ARTICLE_LENGTH",
    "ARTICLE_WIDTH" AS "ARTICLE_WIDTH",
    "ARTICLE_HEIGHT" AS "ARTICLE_HEIGHT",
    "ARTICLE_WEIGHT" AS "ARTICLE_WEIGHT",
    "ARTICLE_SIZE" AS "ARTICLE_SIZE",
    "ARTICLE_COUNT" AS "ARTICLE_COUNT",
    "LOC_TYPE_CODE" AS "LOC_TYPE_CODE",
    "PRIMARY_VENDOR_ID" AS "PRIMARY_VENDOR_ID",
    "ARTICLE_CAT_CODE" AS "ARTICLE_CAT_CODE",
    "ARTICLE_CAT_NAME" AS "ARTICLE_CAT_NAME",
    "ARTICLE_CAT_FULL" AS "ARTICLE_CAT_FULL",
    "DEPT_CODE" AS "DEPT_CODE",
    "DEPT_NAME" AS "DEPT_NAME",
    "DEPT_FULL" AS "DEPT_FULL",
    "LOB_NO" AS "LOB_NO",
    "LOB_DESC" AS "LOB_DESC",
    "LOB_FULL" AS "LOB_FULL",
    "MAJ_DEPT_NO" AS "MAJ_DEPT_NO",
    "MAJ_DEPT_DESC" AS "MAJ_DEPT_DESC",
    "MAJ_DEPT_FULL" AS "MAJ_DEPT_FULL",
    "BRAND_NAME" AS "BRAND_NAME",
    "PVT_LABEL_DESC" AS "PVT_LABEL_DESC",
    "VENDOR_NAME" AS "VENDOR_NAME",
    "VENDOR_FULL" AS "VENDOR_FULL",
    "VENDOR_CO_NAME" AS "VENDOR_CO_NAME",
    "REGION_CODE" AS "REGION_CODE",
    "SALES_QTY" AS "SALES_QTY",
    "battery_cost_total" AS battery_cost_total,
    "SALES_AMT" AS "SALES_AMT",
    "markdown_perc" AS markdown_perc,
    "markdown_flag" AS markdown_flag,
    "COST_AMT" AS "COST_AMT",
    "DISC_AMT" AS "DISC_AMT",
    "OVRD_AMT" AS "OVRD_AMT",
    "TRANS_TAX_AMT" AS "TRANS_TAX_AMT",
    "GROSS_SALES" AS "GROSS_SALES",
    cast("PARENT_VENDOR_ID" as numeric) AS "PARENT_VENDOR_ID",
    "ORDER_LINE_TYPE" AS "ORDER_LINE_TYPE",
    "SCAC" AS "SCAC",
    "OMS_ORDER_LINE_SCHEDULE_SHIP_NODE" AS "OMS_ORDER_LINE_SCHEDULE_SHIP_NODE",
    "SHIPPING_REVENUE" AS "SHIPPING_REVENUE",
    "SHIPPING_DISC" AS "SHIPPING_DISC",
    "ACTUAL_SHIPPING_REVENUE" AS "ACTUAL_SHIPPING_REVENUE",
    "omni_tsc_delivery" AS omni_tsc_delivery,
    "omni_small_package_ltl" AS omni_small_package_ltl,
    "omni_roadie" AS omni_roadie,
    "0mni_multi_salvage" AS _0mni_multi_salvage,
    "battery_cost" AS battery_cost,
    "battery_core_flag" AS battery_core_flag,
    "scandown_flag" AS scandown_flag,
    "cash_discount_flag" AS cash_discount_flag,
    round("SALES_AMT",0) as SALES_ALLOCATE,
    round("COST_AMT",0) as COST_ALLOCATE
FROM CTE;

<br>
  --SALES_W_PAR_VENDOR_BATTERY_COST
</br>
  
CREATE OR REPLACE TEMPORARY TABLE "SALES_W_PAR_VENDOR_BATTERY_COST"
AS
SELECT 
    "CO_CODE" AS "CO_CODE",
    "ARTICLE_NO" AS "ARTICLE_NO",
    "SUM_TYPE_CODE" AS "SUM_TYPE_CODE",
    "VENDOR_ID" AS "VENDOR_ID",
    "PRICE_OVRD_FLAG" AS "PRICE_OVRD_FLAG",
    "SCAN_ITEM_FLAG" AS "SCAN_ITEM_FLAG",
    "PRICE_TYPE_CODE" AS "PRICE_TYPE_CODE",
    "BUY_ONLINE_CODE" AS "BUY_ONLINE_CODE",
    "MERCH_YEAR" AS "MERCH_YEAR",
    "YEAR_WEEK" AS "YEAR_WEEK",
    "YEAR_QUARTER" AS "YEAR_QUARTER",
    "YEAR_PERIOD" AS "YEAR_PERIOD",
    "ARTICLE_DESC" AS "ARTICLE_DESC",
    "ARTICLE_FULL" AS "ARTICLE_FULL",
    "ARTICLE_TYPE_NAME" AS "ARTICLE_TYPE_NAME",
    "ARTICLE_TYPE_CODE" AS "ARTICLE_TYPE_CODE",
    "ARTICLE_TYPE_FULL" AS "ARTICLE_TYPE_FULL",
    "LABEL_TYPE_CODE" AS "LABEL_TYPE_CODE",
    "UOM_CODE" AS "UOM_CODE",
    "UOM_DESC" AS "UOM_DESC",
    "UOM_FULL" AS "UOM_FULL",
    "ARTICLE_LENGTH" AS "ARTICLE_LENGTH",
    "ARTICLE_WIDTH" AS "ARTICLE_WIDTH",
    "ARTICLE_HEIGHT" AS "ARTICLE_HEIGHT",
    "ARTICLE_WEIGHT" AS "ARTICLE_WEIGHT",
    "ARTICLE_SIZE" AS "ARTICLE_SIZE",
    "ARTICLE_COUNT" AS "ARTICLE_COUNT",
    "LOC_TYPE_CODE" AS "LOC_TYPE_CODE",
    "PRIMARY_VENDOR_ID" AS "PRIMARY_VENDOR_ID",
    "ARTICLE_CAT_CODE" AS "ARTICLE_CAT_CODE",
    "ARTICLE_CAT_NAME" AS "ARTICLE_CAT_NAME",
    "ARTICLE_CAT_FULL" AS "ARTICLE_CAT_FULL",
    "DEPT_CODE" AS "DEPT_CODE",
    "DEPT_NAME" AS "DEPT_NAME",
    "DEPT_FULL" AS "DEPT_FULL",
    "LOB_NO" AS "LOB_NO",
    "LOB_DESC" AS "LOB_DESC",
    "LOB_FULL" AS "LOB_FULL",
    "MAJ_DEPT_NO" AS "MAJ_DEPT_NO",
    "MAJ_DEPT_DESC" AS "MAJ_DEPT_DESC",
    "MAJ_DEPT_FULL" AS "MAJ_DEPT_FULL",
    "BRAND_NAME" AS "BRAND_NAME",
    "PVT_LABEL_DESC" AS "PVT_LABEL_DESC",
    "VENDOR_NAME" AS "VENDOR_NAME",
    "VENDOR_FULL" AS "VENDOR_FULL",
    "VENDOR_CO_NAME" AS "VENDOR_CO_NAME",
    "REGION_CODE" AS "REGION_CODE",
    "SALES_QTY" AS "SALES_QTY",
    "battery_cost_total" AS "battery_cost_total",
    "SALES_AMT" AS "SALES_AMT",
    "markdown_perc" AS "markdown_perc",
    "markdown_flag" AS "markdown_flag",
    "COST_AMT" AS "COST_AMT",
    "DISC_AMT" AS "DISC_AMT",
    "OVRD_AMT" AS "OVRD_AMT",
    "TRANS_TAX_AMT" AS "TRANS_TAX_AMT",
    "GROSS_SALES" AS "GROSS_SALES",
    "PARENT_VENDOR_ID" AS "PARENT_VENDOR_ID",
    "ORDER_LINE_TYPE" AS "ORDER_LINE_TYPE",
    "SCAC" AS "SCAC",
    "OMS_ORDER_LINE_SCHEDULE_SHIP_NODE" AS "OMS_ORDER_LINE_SCHEDULE_SHIP_NODE",
    "SHIPPING_REVENUE" AS "SHIPPING_REVENUE",
    "SHIPPING_DISC" AS "SHIPPING_DISC",
    "ACTUAL_SHIPPING_REVENUE" AS "ACTUAL_SHIPPING_REVENUE",
    "omni_tsc_delivery" AS "omni_tsc_delivery",
    "omni_small_package_ltl" AS "omni_small_package_ltl",
    "omni_roadie" AS "omni_roadie",
    "0mni_multi_salvage" AS "0mni_multi_salvage",
    "battery_cost" AS "battery_cost",
    "battery_core_flag" AS "battery_core_flag",
    "scandown_flag" AS "scandown_flag",
    "cash_discount_flag" AS "cash_discount_flag"
  FROM (
    SELECT 
        "CO_CODE",
        "ARTICLE_NO",
        "SUM_TYPE_CODE",
        "VENDOR_ID",
        "PRICE_OVRD_FLAG",
        "SCAN_ITEM_FLAG",
        "PRICE_TYPE_CODE",
        "BUY_ONLINE_CODE",
        "MERCH_YEAR",
        "YEAR_WEEK",
        "YEAR_QUARTER",
        "YEAR_PERIOD",
        "ARTICLE_DESC",
        "ARTICLE_FULL",
        "ARTICLE_TYPE_NAME",
        "ARTICLE_TYPE_CODE",
        "ARTICLE_TYPE_FULL",
        "LABEL_TYPE_CODE",
        "UOM_CODE",
        "UOM_DESC",
        "UOM_FULL",
        "ARTICLE_LENGTH",
        "ARTICLE_WIDTH",
        "ARTICLE_HEIGHT",
        "ARTICLE_WEIGHT",
        "ARTICLE_SIZE",
        "ARTICLE_COUNT",
        "LOC_TYPE_CODE",
        "PRIMARY_VENDOR_ID",
        "ARTICLE_CAT_CODE",
        "ARTICLE_CAT_NAME",
        "ARTICLE_CAT_FULL",
        "DEPT_CODE",
        "DEPT_NAME",
        "DEPT_FULL",
        "LOB_NO",
        "LOB_DESC",
        "LOB_FULL",
        "MAJ_DEPT_NO",
        "MAJ_DEPT_DESC",
        "MAJ_DEPT_FULL",
        "BRAND_NAME",
        "PVT_LABEL_DESC",
        "VENDOR_NAME",
        "VENDOR_FULL",
        "VENDOR_CO_NAME",
        "REGION_CODE",
        "SALES_QTY",
        "SALES_AMT",
        "COST_AMT",
        "DISC_AMT",
        "OVRD_AMT",
        "TRANS_TAX_AMT",
        "GROSS_SALES",
        "PARENT_VENDOR_ID",
        "ORDER_LINE_TYPE",
        "SCAC",
        "OMS_ORDER_LINE_SCHEDULE_SHIP_NODE",
        "SHIPPING_REVENUE",
        "SHIPPING_DISC",
        "ACTUAL_SHIPPING_REVENUE",
        "SALES_ALLOCATE",
        "COST_ALLOCATE",
        "omni_tsc_delivery",
        "omni_small_package_ltl",
        "omni_roadie",
        "0mni_multi_salvage",
        "battery_cost",
        "battery_core_flag",
        "scandown_flag",
        "cash_discount_flag",
        "battery_cost_total",
        "markdown_perc",
        CASE WHEN "GROSS_SALES" > 0 AND "SALES_AMT" > 0 AND "GROSS_SALES" < "SALES_AMT" THEN 0 ELSE CASE WHEN "GROSS_SALES" < 0 AND "SALES_AMT" < 0 THEN 0 ELSE CASE WHEN "markdown_perc" > 0.1 OR "markdown_perc" < -0.1 THEN 1 ELSE 0 END END END AS "markdown_flag"
      FROM (
        SELECT 
            "CO_CODE",
            "ARTICLE_NO",
            "SUM_TYPE_CODE",
            "VENDOR_ID",
            "PRICE_OVRD_FLAG",
            "SCAN_ITEM_FLAG",
            "PRICE_TYPE_CODE",
            "BUY_ONLINE_CODE",
            "MERCH_YEAR",
            "YEAR_WEEK",
            "YEAR_QUARTER",
            "YEAR_PERIOD",
            "ARTICLE_DESC",
            "ARTICLE_FULL",
            "ARTICLE_TYPE_NAME",
            "ARTICLE_TYPE_CODE",
            "ARTICLE_TYPE_FULL",
            "LABEL_TYPE_CODE",
            "UOM_CODE",
            "UOM_DESC",
            "UOM_FULL",
            "ARTICLE_LENGTH",
            "ARTICLE_WIDTH",
            "ARTICLE_HEIGHT",
            "ARTICLE_WEIGHT",
            "ARTICLE_SIZE",
            "ARTICLE_COUNT",
            "LOC_TYPE_CODE",
            "PRIMARY_VENDOR_ID",
            "ARTICLE_CAT_CODE",
            "ARTICLE_CAT_NAME",
            "ARTICLE_CAT_FULL",
            "DEPT_CODE",
            "DEPT_NAME",
            "DEPT_FULL",
            "LOB_NO",
            "LOB_DESC",
            "LOB_FULL",
            "MAJ_DEPT_NO",
            "MAJ_DEPT_DESC",
            "MAJ_DEPT_FULL",
            "BRAND_NAME",
            "PVT_LABEL_DESC",
            "VENDOR_NAME",
            "VENDOR_FULL",
            "VENDOR_CO_NAME",
            "REGION_CODE",
            "SALES_QTY",
            "SALES_AMT",
            "COST_AMT",
            "DISC_AMT",
            "OVRD_AMT",
            "TRANS_TAX_AMT",
            "GROSS_SALES",
            "PARENT_VENDOR_ID",
            "ORDER_LINE_TYPE",
            "SCAC",
            "OMS_ORDER_LINE_SCHEDULE_SHIP_NODE",
            "SHIPPING_REVENUE",
            "SHIPPING_DISC",
            "ACTUAL_SHIPPING_REVENUE",
            "SALES_ALLOCATE",
            "COST_ALLOCATE",
            "omni_tsc_delivery",
            "omni_small_package_ltl",
            "omni_roadie",
            "0mni_multi_salvage",
            "battery_cost",
            "battery_core_flag",
            "scandown_flag",
            "cash_discount_flag",
            ROUND(COALESCE("battery_cost", 0) * COALESCE("SALES_QTY", 0) * 0.85, 0) AS "battery_cost_total",
            CASE WHEN ("GROSS_SALES" = 0) OR "GROSS_SALES" IS NULL OR ("SALES_AMT" = 0) THEN 0 ELSE "GROSS_SALES" / NULLIF("SALES_AMT", 0) - 1 END AS "markdown_perc"
          FROM "SALES_W_PAR_VENDOR_JOINED"  "input_table"
        ) "A"
    ) "B";

<br>
-- Final Query for MASTER_SALES_ROUND
</br>
insert into "MASTER_SALES_ROUND"
SELECT 
  CO_CODE,
  ARTICLE_NO,
  SUM_TYPE_CODE,
  VENDOR_ID,
  PRICE_OVRD_FLAG,
  SCAN_ITEM_FLAG,
  cast(PRICE_TYPE_CODE as varchar) as PRICE_TYPE_CODE,
  BUY_ONLINE_CODE,
  MERCH_YEAR,
  YEAR_WEEK,
  YEAR_QUARTER,
  YEAR_PERIOD,
  ARTICLE_DESC,
  ARTICLE_FULL,
  ARTICLE_TYPE_NAME,
  ARTICLE_TYPE_CODE,
  ARTICLE_TYPE_FULL,
  LABEL_TYPE_CODE,
  UOM_CODE,
  UOM_DESC,
  UOM_FULL,
  ARTICLE_LENGTH,
  ARTICLE_WIDTH,
  ARTICLE_HEIGHT,
  ARTICLE_WEIGHT,
  ARTICLE_SIZE,
  ARTICLE_COUNT,
  LOC_TYPE_CODE,
  PRIMARY_VENDOR_ID,
  ARTICLE_CAT_CODE,
  ARTICLE_CAT_NAME,
  ARTICLE_CAT_FULL,
  DEPT_CODE,
  DEPT_NAME,
  DEPT_FULL,
  LOB_NO,
  LOB_DESC,
  LOB_FULL,
  MAJ_DEPT_NO,
  MAJ_DEPT_DESC,
  MAJ_DEPT_FULL,
  BRAND_NAME,
  PVT_LABEL_DESC,
  VENDOR_NAME,
  VENDOR_FULL,
  VENDOR_CO_NAME,
  REGION_CODE,
  SALES_QTY,
  "battery_cost_total",
  SALES_AMT,
  "markdown_perc",
  "markdown_flag",
  COST_AMT,
  DISC_AMT,
  OVRD_AMT,
  TRANS_TAX_AMT,
  GROSS_SALES,
  PARENT_VENDOR_ID,
  ORDER_LINE_TYPE,
  SCAC,
  OMS_ORDER_LINE_SCHEDULE_SHIP_NODE,
  SHIPPING_REVENUE,
  SHIPPING_DISC,
  ACTUAL_SHIPPING_REVENUE,
  "omni_tsc_delivery",
  "omni_small_package_ltl",
  "omni_roadie",
  "0mni_multi_salvage",
  "battery_cost",
  "battery_core_flag",
  "scandown_flag",
  "cash_discount_flag",
  ROUND("SALES_AMT",0) as SALES_ALLOCATE,
  ROUND("COST_AMT",0) COST_ALLOCATE
FROM "SALES_W_PAR_VENDOR_BATTERY_COST";

<br>
-- ALLOCATION_CONTROL_PQ_SF
</br>
insert into ALLOCATION_CONTROL_PQ_SF
SELECT DISTINCT
    'Y' AS allocate_flag,
    CASE WHEN ALLOCATION_FILE ='battery_core_final' THEN 'BATTERY_CORE_ALLOCATE' 
     WHEN ALLOCATION_FILE ='mixing_center_final' THEN 'Mixing_Center_Credit_prep' 
     WHEN ALLOCATION_FILE ='new_store_discount_final' THEN 'TENANT149_DATA_new_store_discount_prepared_prepared_by_NSD_Sku' 
     WHEN ALLOCATION_FILE ='booth_rental_final' THEN 'booth_rental_final'
     WHEN ALLOCATION_FILE ='cash_discounts_by_flag_final' THEN 'cash_discounts_by_flag'
     WHEN ALLOCATION_FILE ='cash_discounts_w_vendor_final' THEN 'cash_discounts_w_vendor'
     WHEN ALLOCATION_FILE ='dc_shrink_final' THEN 'dc_shrink_allocate'
     WHEN ALLOCATION_FILE ='defectives_final' THEN 'defectives_allocate'
     WHEN ALLOCATION_FILE ='marketing_final' THEN 'marketing_allocate'
     WHEN ALLOCATION_FILE ='pdq_final' THEN 'pdq_allocate_filtered'
     WHEN ALLOCATION_FILE ='pop_final' THEN 'POP_ALLOCATE'
     WHEN ALLOCATION_FILE ='theft_final' THEN 'theft_allocate'
     WHEN ALLOCATION_FILE ='unsellables_final' THEN 'unsellables_allocate'
     WHEN ALLOCATION_FILE ='vendor_compliance_final' THEN 'vendor_compliance_allocate'
     WHEN ALLOCATION_FILE ='vf_defective_final' THEN 'vf_defective_allocate'
     WHEN ALLOCATION_FILE ='shrink_inventory_final' THEN 'shrink_allocate'
END AS ALLOCATION_FILE,
    "GROUP_BY_PERIOD_1",
	"GROUP_BY_PERIOD_2",
	"L2_GROUP_BY_PERIOD_1",
	"L2_GROUP_BY_PERIOD_2",
	"GROUP_BY_1",
	"GROUP_BY_2",
	"GROUP_BY_3",
	"GROUP_BY_4",
	"GROUP_BY_5",
	"L2_GROUP_BY_1",
	"L2_GROUP_BY_2",
	"L2_GROUP_BY_3" ,
	"L2_GROUP_BY_4",
	"ALLOCATE_BY",
	"ALLOCATION_TYPE" ,
	"ROLLUP_BY_1" ,
	"ROLLUP_BY_2" 
FROM  allocation_control
where allocate_flag ='Y';
