
 <br> </br>
INSERT INTO "PURCHASE_ORDER_LINE_W_CAL"
(
"STORE_NO"  ,
"CO_CODE"  ,
"ARTICLE_NO"  ,
"PO_NO"  ,
"PO_LINE_NO"  ,
"PO_DATE"  ,
"po_date_parsed"  ,
"DELIV_DATE"  ,
"deliv_date_parsed"  ,
"PO_TYPE_CODE"  ,
"VENDOR_ID"  ,
"VSR_CODE"  ,
"PO_LINE_CANCELLED_FLAG"  ,
"PO_LINE_ORDER_QTY"  ,
"PO_LINE_ISSUE_QTY"  ,
"PO_LINE_RCVD_QTY"  ,
"PO_LINE_UNIT_PRICE"  ,
"DC_NO"  ,
"PO_TRACKING_NO"  ,
"PO_LINE_TRACKING_NO"  ,
"CURRENT_REPL_TYPE_CODE"  ,
"FREIGHT_TYPE_CODE"  ,
"SHIP_START_DATE"  ,
"SHIP_END_DATE"  ,
"DELIV_START_DATE"  ,
"DELIV_END_DATE"  ,
"PO_LINE_UNIT_FREIGHT_AMT"  ,
"PO_LINE_MANUFACTURER"  ,
"PO_LINE_ORIGIN_COUNTRY_CODE"  ,
"PO_LINE_PORT_OF_ORIGIN"  ,
"PO_LINE_MIN_RCVD_DATE"  ,
"PO_LINE_MAX_RCVD_DATE"  ,
"PO_LINE_DELIVERED_FLAG"  ,
"PO_LINE_CONFIRMED_ON_BOARD_DATE"  ,
"PO_LINE_BOOKED_FOR_SHIPMENT_DATE"  ,
"PO_LINE_TRANSIT_RESN_CODE"  ,
"PO_LINE_MOVE_TYPE_CODE"  ,
"PO_LINE_AGENT_COMMISSION_RATE"  ,
"PO_LINE_AGENT_COMMISSION_AMT"  ,
"PO_LINE_ADDL_ARTICLE_NO"  ,
"PO_LINE_ADDL_ARTICLE_QTY"  ,
"PO_LINE_FACTORY_VENDOR_ID"  ,
"PO_LINE_STUFFING_LOC_VENDOR_ID"  ,
"PO_LINE_SOURCING_AGENT_VENDOR_ID"  ,
"PO_LINE_FREIGHT_FORWARDER_VENDOR_ID"  ,
"PO_LINE_LETTER_OF_CREDIT_NO"  ,
"PO_LINE_OPEN_ACCT_NO"  ,
"PO_LINE_ARTICLE_LENGTH"  ,
"PO_LINE_ARTICLE_WIDTH"  ,
"PO_LINE_ARTICLE_HEIGHT"  ,
"PO_LINE_ARTICLE_DIMENSIONS_UOM"  ,
"PO_LINE_ARTICLE_WEIGHT"  ,
"PO_LINE_ARTICLE_WEIGHT_UOM"  ,
"PO_TOTAL_WEIGHT"  ,
"PO_LINE_ARTICLE_VOLUME"  ,
"PO_LINE_ARTICLE_VOLUME_UOM"  ,
"PO_TOTAL_VOLUME"  ,
"HTS_CODE"  ,
"PO_LINE_DUTY_RATE"  ,
"PO_LINE_DUTY_AMT"  ,
"PO_LINE_ADDL_HTS_CODE_1"  ,
"PO_LINE_ADDL_DUTY_RATE_1"  ,
"PO_LINE_ADDL_DUTY_AMT_1"  ,
"PO_LINE_ADDL_HTS_CODE_2"  ,
"PO_LINE_ADDL_DUTY_RATE_2"  ,
"PO_LINE_ADDL_DUTY_AMT_2"  ,
"PO_HELD_FLAG"  ,
"PO_VENDOR_DOC_DATE"  ,
"cal_MERCH_YEAR"  ,
"cal_YEAR_WEEK"  ,
"cal_YEAR_QUARTER"  ,
"cal_YEAR_PERIOD"  
)
WITH PURCHASE_ORDER_LINE_DATE AS (
SELECT 
    "STORE_NO" AS "STORE_NO",
    "CO_CODE" AS "CO_CODE",
    "ARTICLE_NO" AS "ARTICLE_NO",
    "PO_NO" AS "PO_NO",
    "PO_LINE_NO" AS "PO_LINE_NO",
    "PO_DATE" AS "PO_DATE",
    To_varchar(Date_trunc('SECOND', Convert_timezone('UTC', 'UTC', ("PO_DATE"))), 'YYYY-MM-DD"T"HH24:MI:SS"."FF3"Z"') AS 
    "po_date_parsed",
    "DELIV_DATE" AS "DELIV_DATE",
    To_varchar(Date_trunc('SECOND', Convert_timezone('UTC', 'UTC', ("DELIV_DATE"))), 'YYYY-MM-DD"T"HH24:MI:SS"."FF3"Z"') AS 
    "deliv_date_parsed",
    "PO_TYPE_CODE" AS "PO_TYPE_CODE",
    "VENDOR_ID" AS "VENDOR_ID",
    "VSR_CODE" AS "VSR_CODE",
    "PO_LINE_CANCELLED_FLAG" AS "PO_LINE_CANCELLED_FLAG",
    "PO_LINE_ORDER_QTY" AS "PO_LINE_ORDER_QTY",
    "PO_LINE_ISSUE_QTY" AS "PO_LINE_ISSUE_QTY",
    "PO_LINE_RCVD_QTY" AS "PO_LINE_RCVD_QTY",
    "PO_LINE_UNIT_PRICE" AS "PO_LINE_UNIT_PRICE",
    "DC_NO" AS "DC_NO",
    "PO_TRACKING_NO" AS "PO_TRACKING_NO",
    "PO_LINE_TRACKING_NO" AS "PO_LINE_TRACKING_NO",
    "CURRENT_REPL_TYPE_CODE" AS "CURRENT_REPL_TYPE_CODE",
    "FREIGHT_TYPE_CODE" AS "FREIGHT_TYPE_CODE",
    "SHIP_START_DATE" AS "SHIP_START_DATE",
    "SHIP_END_DATE" AS "SHIP_END_DATE",
    "DELIV_START_DATE" AS "DELIV_START_DATE",
    "DELIV_END_DATE" AS "DELIV_END_DATE",
    "PO_LINE_UNIT_FREIGHT_AMT" AS "PO_LINE_UNIT_FREIGHT_AMT",
    "PO_LINE_MANUFACTURER" AS "PO_LINE_MANUFACTURER",
    "PO_LINE_ORIGIN_COUNTRY_CODE" AS "PO_LINE_ORIGIN_COUNTRY_CODE",
    "PO_LINE_PORT_OF_ORIGIN" AS "PO_LINE_PORT_OF_ORIGIN",
    "PO_LINE_MIN_RCVD_DATE" AS "PO_LINE_MIN_RCVD_DATE",
    "PO_LINE_MAX_RCVD_DATE" AS "PO_LINE_MAX_RCVD_DATE",
    "PO_LINE_DELIVERED_FLAG" AS "PO_LINE_DELIVERED_FLAG",
    "PO_LINE_CONFIRMED_ON_BOARD_DATE" AS "PO_LINE_CONFIRMED_ON_BOARD_DATE",
    "PO_LINE_BOOKED_FOR_SHIPMENT_DATE" AS "PO_LINE_BOOKED_FOR_SHIPMENT_DATE",
    "PO_LINE_TRANSIT_RESN_CODE" AS "PO_LINE_TRANSIT_RESN_CODE",
    "PO_LINE_MOVE_TYPE_CODE" AS "PO_LINE_MOVE_TYPE_CODE",
    "PO_LINE_AGENT_COMMISSION_RATE" AS "PO_LINE_AGENT_COMMISSION_RATE",
    "PO_LINE_AGENT_COMMISSION_AMT" AS "PO_LINE_AGENT_COMMISSION_AMT",
    "PO_LINE_ADDL_ARTICLE_NO" AS "PO_LINE_ADDL_ARTICLE_NO",
    "PO_LINE_ADDL_ARTICLE_QTY" AS "PO_LINE_ADDL_ARTICLE_QTY",
    "PO_LINE_FACTORY_VENDOR_ID" AS "PO_LINE_FACTORY_VENDOR_ID",
    "PO_LINE_STUFFING_LOC_VENDOR_ID" AS "PO_LINE_STUFFING_LOC_VENDOR_ID",
    "PO_LINE_SOURCING_AGENT_VENDOR_ID" AS "PO_LINE_SOURCING_AGENT_VENDOR_ID",
    "PO_LINE_FREIGHT_FORWARDER_VENDOR_ID" AS "PO_LINE_FREIGHT_FORWARDER_VENDOR_ID",
    "PO_LINE_LETTER_OF_CREDIT_NO" AS "PO_LINE_LETTER_OF_CREDIT_NO",
    "PO_LINE_OPEN_ACCT_NO" AS "PO_LINE_OPEN_ACCT_NO",
    "PO_LINE_ARTICLE_LENGTH" AS "PO_LINE_ARTICLE_LENGTH",
    "PO_LINE_ARTICLE_WIDTH" AS "PO_LINE_ARTICLE_WIDTH",
    "PO_LINE_ARTICLE_HEIGHT" AS "PO_LINE_ARTICLE_HEIGHT",
    "PO_LINE_ARTICLE_DIMENSIONS_UOM" AS "PO_LINE_ARTICLE_DIMENSIONS_UOM",
    "PO_LINE_ARTICLE_WEIGHT" AS "PO_LINE_ARTICLE_WEIGHT",
    "PO_LINE_ARTICLE_WEIGHT_UOM" AS "PO_LINE_ARTICLE_WEIGHT_UOM",
    "PO_TOTAL_WEIGHT" AS "PO_TOTAL_WEIGHT",
    "PO_LINE_ARTICLE_VOLUME" AS "PO_LINE_ARTICLE_VOLUME",
    "PO_LINE_ARTICLE_VOLUME_UOM" AS "PO_LINE_ARTICLE_VOLUME_UOM",
    "PO_TOTAL_VOLUME" AS "PO_TOTAL_VOLUME",
    "HTS_CODE" AS "HTS_CODE",
    "PO_LINE_DUTY_RATE" AS "PO_LINE_DUTY_RATE",
    "PO_LINE_DUTY_AMT" AS "PO_LINE_DUTY_AMT",
    "PO_LINE_ADDL_HTS_CODE_1" AS "PO_LINE_ADDL_HTS_CODE_1",
    "PO_LINE_ADDL_DUTY_RATE_1" AS "PO_LINE_ADDL_DUTY_RATE_1",
    "PO_LINE_ADDL_DUTY_AMT_1" AS "PO_LINE_ADDL_DUTY_AMT_1",
    "PO_LINE_ADDL_HTS_CODE_2" AS "PO_LINE_ADDL_HTS_CODE_2",
    "PO_LINE_ADDL_DUTY_RATE_2" AS "PO_LINE_ADDL_DUTY_RATE_2",
    "PO_LINE_ADDL_DUTY_AMT_2" AS "PO_LINE_ADDL_DUTY_AMT_2",
    "PO_HELD_FLAG" AS "PO_HELD_FLAG",
    "PO_VENDOR_DOC_DATE" AS "PO_VENDOR_DOC_DATE"
  FROM edw.VW_purchase_order_line  )
  SELECT  a.*, 
    B."MERCH_YEAR" AS "cal_MERCH_YEAR",
    B."YEAR_WEEK" AS "cal_YEAR_WEEK",
    B."YEAR_QUARTER" AS "cal_YEAR_QUARTER",
    B."YEAR_PERIOD" AS "cal_YEAR_PERIOD" 
FROM PURCHASE_ORDER_LINE_DATE a
  LEFT JOIN (    SELECT   "MERCH_YEAR" ,
                          "YEAR_WEEK" ,
                          "YEAR_QUARTER" ,
                          "YEAR_PERIOD"  ,
                           To_varchar(Date_trunc('SECOND', Convert_timezone('UTC', 'UTC', (DATE_FROM_PARTS(YEAR_,Month_,Day_)))), 'YYYY-MM-DD"T"HH24:MI:SS"."FF3"Z"') AS date
                  FROM (  SELECT 
                                 "MERCH_YEAR" ,
                                 "YEAR_WEEK" ,
                                 "YEAR_QUARTER" ,
                                 "YEAR_PERIOD"  ,
                                  LEFT(TIME_DIM_KEY,4) AS YEAR_,
                                  SUBSTRING(TIME_DIM_KEY,5,2) AS Month_,
                                  RIGHT(TIME_DIM_KEY,2) AS Day_
                           FROM   "EDW"."TIME_DIMENSION"  )A
                           )B
    ON (a."DELIV_DATE") = (B.date)
WHERE B."YEAR_PERIOD" BETWEEN '202306' AND '202406';
 
 <br> </br>
INSERT INTO  PURCHASE_ORDER_LINE_W_CAL_FILTERED_JOINED
(
"STORE_NO"  ,
"CO_CODE"  ,
"ARTICLE_NO"  ,
"PO_NO"  ,
"PO_LINE_NO"  ,
"PO_DATE"  ,
"po_date_parsed"  ,
"DELIV_DATE"  ,
"deliv_date_parsed"  ,
"PO_TYPE_CODE"  ,
"VENDOR_ID"  ,
"VSR_CODE"  ,
"PO_LINE_CANCELLED_FLAG"  ,
"PO_LINE_ORDER_QTY"  ,
"PO_LINE_ISSUE_QTY"  ,
"PO_LINE_RCVD_QTY"  ,
"PO_LINE_UNIT_PRICE"  ,
"DC_NO"  ,
"PO_TRACKING_NO"  ,
"PO_LINE_TRACKING_NO"  ,
"CURRENT_REPL_TYPE_CODE"  ,
"FREIGHT_TYPE_CODE"  ,
"SHIP_START_DATE"  ,
"SHIP_END_DATE"  ,
"DELIV_START_DATE"  ,
"DELIV_END_DATE"  ,
"PO_LINE_UNIT_FREIGHT_AMT"  ,
"PO_LINE_MANUFACTURER"  ,
"PO_LINE_ORIGIN_COUNTRY_CODE"  ,
"PO_LINE_PORT_OF_ORIGIN"  ,
"PO_LINE_MIN_RCVD_DATE"  ,
"PO_LINE_MAX_RCVD_DATE"  ,
"PO_LINE_DELIVERED_FLAG"  ,
"PO_LINE_CONFIRMED_ON_BOARD_DATE"  ,
"PO_LINE_BOOKED_FOR_SHIPMENT_DATE"  ,
"PO_LINE_TRANSIT_RESN_CODE"  ,
"PO_LINE_MOVE_TYPE_CODE"  ,
"PO_LINE_AGENT_COMMISSION_RATE"  ,
"PO_LINE_AGENT_COMMISSION_AMT"  ,
"PO_LINE_ADDL_ARTICLE_NO"  ,
"PO_LINE_ADDL_ARTICLE_QTY"  ,
"PO_LINE_FACTORY_VENDOR_ID"  ,
"PO_LINE_STUFFING_LOC_VENDOR_ID"  ,
"PO_LINE_SOURCING_AGENT_VENDOR_ID"  ,
"PO_LINE_FREIGHT_FORWARDER_VENDOR_ID"  ,
"PO_LINE_LETTER_OF_CREDIT_NO"  ,
"PO_LINE_OPEN_ACCT_NO"  ,
"PO_LINE_ARTICLE_LENGTH"  ,
"PO_LINE_ARTICLE_WIDTH"  ,
"PO_LINE_ARTICLE_HEIGHT"  ,
"PO_LINE_ARTICLE_DIMENSIONS_UOM"  ,
"PO_LINE_ARTICLE_WEIGHT"  ,
"PO_LINE_ARTICLE_WEIGHT_UOM"  ,
"PO_TOTAL_WEIGHT"  ,
"PO_LINE_ARTICLE_VOLUME"  ,
"PO_LINE_ARTICLE_VOLUME_UOM"  ,
"PO_TOTAL_VOLUME"  ,
"HTS_CODE"  ,
"PO_LINE_DUTY_RATE"  ,
"PO_LINE_DUTY_AMT"  ,
"PO_LINE_ADDL_HTS_CODE_1"  ,
"PO_LINE_ADDL_DUTY_RATE_1"  ,
"PO_LINE_ADDL_DUTY_AMT_1"  ,
"PO_LINE_ADDL_HTS_CODE_2"  ,
"PO_LINE_ADDL_DUTY_RATE_2"  ,
"PO_LINE_ADDL_DUTY_AMT_2"  ,
"PO_HELD_FLAG"  ,
"PO_VENDOR_DOC_DATE"  ,
"cal_MERCH_YEAR"  ,
"cal_YEAR_WEEK"  ,
"cal_YEAR_QUARTER"  ,
"cal_YEAR_PERIOD"  ,
"dest_Facility_Code" ,
"dest_Facility_Name" ,
"dest_Facility_Type" ,
"org_Facility_Code"  ,
"org_Facility_Name" ,
"org_Facility_Type" 
	 )
     SELECT    
	 DISTINCT  
    "purchase_order_line_w_cal_filtered"."STORE_NO" AS "STORE_NO",
    "purchase_order_line_w_cal_filtered"."CO_CODE" AS "CO_CODE",
    "purchase_order_line_w_cal_filtered"."ARTICLE_NO" AS "ARTICLE_NO",
    "purchase_order_line_w_cal_filtered"."PO_NO" AS "PO_NO",
    "purchase_order_line_w_cal_filtered"."PO_LINE_NO" AS "PO_LINE_NO",
    "purchase_order_line_w_cal_filtered"."PO_DATE" AS "PO_DATE",
    "purchase_order_line_w_cal_filtered"."po_date_parsed" AS "po_date_parsed",
    "purchase_order_line_w_cal_filtered"."DELIV_DATE" AS "DELIV_DATE",
    "purchase_order_line_w_cal_filtered"."deliv_date_parsed" AS "deliv_date_parsed",
    "purchase_order_line_w_cal_filtered"."PO_TYPE_CODE" AS "PO_TYPE_CODE",
    "purchase_order_line_w_cal_filtered"."VENDOR_ID" AS "VENDOR_ID",
    "purchase_order_line_w_cal_filtered"."VSR_CODE" AS "VSR_CODE",
    "purchase_order_line_w_cal_filtered"."PO_LINE_CANCELLED_FLAG" AS "PO_LINE_CANCELLED_FLAG",
    "purchase_order_line_w_cal_filtered"."PO_LINE_ORDER_QTY" AS "PO_LINE_ORDER_QTY",
    "purchase_order_line_w_cal_filtered"."PO_LINE_ISSUE_QTY" AS "PO_LINE_ISSUE_QTY",
    "purchase_order_line_w_cal_filtered"."PO_LINE_RCVD_QTY" AS "PO_LINE_RCVD_QTY",
    "purchase_order_line_w_cal_filtered"."PO_LINE_UNIT_PRICE" AS "PO_LINE_UNIT_PRICE",
    "purchase_order_line_w_cal_filtered"."DC_NO" AS "DC_NO",
    "purchase_order_line_w_cal_filtered"."PO_TRACKING_NO" AS "PO_TRACKING_NO",
    "purchase_order_line_w_cal_filtered"."PO_LINE_TRACKING_NO" AS "PO_LINE_TRACKING_NO",
    "purchase_order_line_w_cal_filtered"."CURRENT_REPL_TYPE_CODE" AS "CURRENT_REPL_TYPE_CODE",
    "purchase_order_line_w_cal_filtered"."FREIGHT_TYPE_CODE" AS "FREIGHT_TYPE_CODE",
    "purchase_order_line_w_cal_filtered"."SHIP_START_DATE" AS "SHIP_START_DATE",
    "purchase_order_line_w_cal_filtered"."SHIP_END_DATE" AS "SHIP_END_DATE",
    "purchase_order_line_w_cal_filtered"."DELIV_START_DATE" AS "DELIV_START_DATE",
    "purchase_order_line_w_cal_filtered"."DELIV_END_DATE" AS "DELIV_END_DATE",
    "purchase_order_line_w_cal_filtered"."PO_LINE_UNIT_FREIGHT_AMT" AS "PO_LINE_UNIT_FREIGHT_AMT",
    "purchase_order_line_w_cal_filtered"."PO_LINE_MANUFACTURER" AS "PO_LINE_MANUFACTURER",
    "purchase_order_line_w_cal_filtered"."PO_LINE_ORIGIN_COUNTRY_CODE" AS "PO_LINE_ORIGIN_COUNTRY_CODE",
    "purchase_order_line_w_cal_filtered"."PO_LINE_PORT_OF_ORIGIN" AS "PO_LINE_PORT_OF_ORIGIN",
    "purchase_order_line_w_cal_filtered"."PO_LINE_MIN_RCVD_DATE" AS "PO_LINE_MIN_RCVD_DATE",
    "purchase_order_line_w_cal_filtered"."PO_LINE_MAX_RCVD_DATE" AS "PO_LINE_MAX_RCVD_DATE",
    "purchase_order_line_w_cal_filtered"."PO_LINE_DELIVERED_FLAG" AS "PO_LINE_DELIVERED_FLAG",
    "purchase_order_line_w_cal_filtered"."PO_LINE_CONFIRMED_ON_BOARD_DATE" AS "PO_LINE_CONFIRMED_ON_BOARD_DATE",
    "purchase_order_line_w_cal_filtered"."PO_LINE_BOOKED_FOR_SHIPMENT_DATE" AS "PO_LINE_BOOKED_FOR_SHIPMENT_DATE",
    "purchase_order_line_w_cal_filtered"."PO_LINE_TRANSIT_RESN_CODE" AS "PO_LINE_TRANSIT_RESN_CODE",
    "purchase_order_line_w_cal_filtered"."PO_LINE_MOVE_TYPE_CODE" AS "PO_LINE_MOVE_TYPE_CODE",
    "purchase_order_line_w_cal_filtered"."PO_LINE_AGENT_COMMISSION_RATE" AS "PO_LINE_AGENT_COMMISSION_RATE",
    "purchase_order_line_w_cal_filtered"."PO_LINE_AGENT_COMMISSION_AMT" AS "PO_LINE_AGENT_COMMISSION_AMT",
    "purchase_order_line_w_cal_filtered"."PO_LINE_ADDL_ARTICLE_NO" AS "PO_LINE_ADDL_ARTICLE_NO",
    "purchase_order_line_w_cal_filtered"."PO_LINE_ADDL_ARTICLE_QTY" AS "PO_LINE_ADDL_ARTICLE_QTY",
    "purchase_order_line_w_cal_filtered"."PO_LINE_FACTORY_VENDOR_ID" AS "PO_LINE_FACTORY_VENDOR_ID",
    "purchase_order_line_w_cal_filtered"."PO_LINE_STUFFING_LOC_VENDOR_ID" AS "PO_LINE_STUFFING_LOC_VENDOR_ID",
    "purchase_order_line_w_cal_filtered"."PO_LINE_SOURCING_AGENT_VENDOR_ID" AS "PO_LINE_SOURCING_AGENT_VENDOR_ID",
    "purchase_order_line_w_cal_filtered"."PO_LINE_FREIGHT_FORWARDER_VENDOR_ID" AS "PO_LINE_FREIGHT_FORWARDER_VENDOR_ID",
    "purchase_order_line_w_cal_filtered"."PO_LINE_LETTER_OF_CREDIT_NO" AS "PO_LINE_LETTER_OF_CREDIT_NO",
    "purchase_order_line_w_cal_filtered"."PO_LINE_OPEN_ACCT_NO" AS "PO_LINE_OPEN_ACCT_NO",
    "purchase_order_line_w_cal_filtered"."PO_LINE_ARTICLE_LENGTH" AS "PO_LINE_ARTICLE_LENGTH",
    "purchase_order_line_w_cal_filtered"."PO_LINE_ARTICLE_WIDTH" AS "PO_LINE_ARTICLE_WIDTH",
    "purchase_order_line_w_cal_filtered"."PO_LINE_ARTICLE_HEIGHT" AS "PO_LINE_ARTICLE_HEIGHT",
    "purchase_order_line_w_cal_filtered"."PO_LINE_ARTICLE_DIMENSIONS_UOM" AS "PO_LINE_ARTICLE_DIMENSIONS_UOM",
    "purchase_order_line_w_cal_filtered"."PO_LINE_ARTICLE_WEIGHT" AS "PO_LINE_ARTICLE_WEIGHT",
    "purchase_order_line_w_cal_filtered"."PO_LINE_ARTICLE_WEIGHT_UOM" AS "PO_LINE_ARTICLE_WEIGHT_UOM",
    "purchase_order_line_w_cal_filtered"."PO_TOTAL_WEIGHT" AS "PO_TOTAL_WEIGHT",
    "purchase_order_line_w_cal_filtered"."PO_LINE_ARTICLE_VOLUME" AS "PO_LINE_ARTICLE_VOLUME",
    "purchase_order_line_w_cal_filtered"."PO_LINE_ARTICLE_VOLUME_UOM" AS "PO_LINE_ARTICLE_VOLUME_UOM",
    "purchase_order_line_w_cal_filtered"."PO_TOTAL_VOLUME" AS "PO_TOTAL_VOLUME",
    "purchase_order_line_w_cal_filtered"."HTS_CODE" AS "HTS_CODE",
    "purchase_order_line_w_cal_filtered"."PO_LINE_DUTY_RATE" AS "PO_LINE_DUTY_RATE",
    "purchase_order_line_w_cal_filtered"."PO_LINE_DUTY_AMT" AS "PO_LINE_DUTY_AMT",
    "purchase_order_line_w_cal_filtered"."PO_LINE_ADDL_HTS_CODE_1" AS "PO_LINE_ADDL_HTS_CODE_1",
    "purchase_order_line_w_cal_filtered"."PO_LINE_ADDL_DUTY_RATE_1" AS "PO_LINE_ADDL_DUTY_RATE_1",
    "purchase_order_line_w_cal_filtered"."PO_LINE_ADDL_DUTY_AMT_1" AS "PO_LINE_ADDL_DUTY_AMT_1",
    "purchase_order_line_w_cal_filtered"."PO_LINE_ADDL_HTS_CODE_2" AS "PO_LINE_ADDL_HTS_CODE_2",
    "purchase_order_line_w_cal_filtered"."PO_LINE_ADDL_DUTY_RATE_2" AS "PO_LINE_ADDL_DUTY_RATE_2",
    "purchase_order_line_w_cal_filtered"."PO_LINE_ADDL_DUTY_AMT_2" AS "PO_LINE_ADDL_DUTY_AMT_2",
    "purchase_order_line_w_cal_filtered"."PO_HELD_FLAG" AS "PO_HELD_FLAG",
    "purchase_order_line_w_cal_filtered"."PO_VENDOR_DOC_DATE" AS "PO_VENDOR_DOC_DATE",
    "purchase_order_line_w_cal_filtered"."cal_MERCH_YEAR" AS "cal_MERCH_YEAR",
    "purchase_order_line_w_cal_filtered"."cal_YEAR_WEEK" AS "cal_YEAR_WEEK",
    "purchase_order_line_w_cal_filtered"."cal_YEAR_QUARTER" AS "cal_YEAR_QUARTER",
    "purchase_order_line_w_cal_filtered"."cal_YEAR_PERIOD" AS "cal_YEAR_PERIOD",
    "TSC_facilities_final"."FACILITY_CODE" AS "dest_Facility_Code",
    "TSC_facilities_final"."FACILITY_NAME" AS "dest_Facility_Name",
    "TSC_facilities_final"."FACILITY_TYPE" AS "dest_Facility_Type",
    "TSC_facilities_final_2"."FACILITY_CODE" AS "org_Facility_Code",
    "TSC_facilities_final_2"."FACILITY_NAME" AS "org_Facility_Name",
    "TSC_facilities_final_2"."FACILITY_TYPE" AS "org_Facility_Type"
  FROM "PURCHASE_ORDER_LINE_W_CAL" "purchase_order_line_w_cal_filtered"
  LEFT JOIN "TSC_FACILITIES_FINAL" "TSC_facilities_final"
    ON "purchase_order_line_w_cal_filtered"."STORE_NO" = "TSC_facilities_final"."FACILITY_CODE"
  LEFT JOIN "TSC_FACILITIES_FINAL" "TSC_facilities_final_2"
    ON "purchase_order_line_w_cal_filtered"."VENDOR_ID" = "TSC_facilities_final_2"."FACILITY_CODE"
  WHERE UPPER("purchase_order_line_w_cal_filtered"."CO_CODE") = 'TSC'  AND "cal_YEAR_PERIOD" BETWEEN '202306'	AND '202406' ;
 
 <br> </br>

INSERT INTO  PURCHASE_ORDER_LINE_W_ARTICLE_PREPARED
(
"STORE_NO"  ,
"CO_CODE"  ,
"ARTICLE_NO"  ,
"PO_NO"  ,
"PO_LINE_NO"  ,
"PO_DATE"  ,
"po_date_parsed"  ,
"DELIV_DATE"  ,
"deliv_date_parsed"  ,
"PO_TYPE_CODE"  ,
"VENDOR_ID"  ,
"VSR_CODE"  ,
"PO_LINE_CANCELLED_FLAG"  ,
"PO_LINE_ORDER_QTY"  ,
"PO_LINE_ISSUE_QTY"  ,
"PO_LINE_RCVD_QTY"  ,
"PO_LINE_UNIT_PRICE"  ,
"DC_NO"  ,
"PO_TRACKING_NO"  ,
"PO_LINE_TRACKING_NO"  ,
"CURRENT_REPL_TYPE_CODE"  ,
"FREIGHT_TYPE_CODE"  ,
"SHIP_START_DATE"  ,
"SHIP_END_DATE"  ,
"DELIV_START_DATE"  ,
"DELIV_END_DATE"  ,
"PO_LINE_UNIT_FREIGHT_AMT"  ,
"PO_LINE_MANUFACTURER"  ,
"PO_LINE_ORIGIN_COUNTRY_CODE"  ,
"PO_LINE_PORT_OF_ORIGIN"  ,
"PO_LINE_MIN_RCVD_DATE"  ,
"PO_LINE_MAX_RCVD_DATE"  ,
"PO_LINE_DELIVERED_FLAG"  ,
"PO_LINE_CONFIRMED_ON_BOARD_DATE"  ,
"PO_LINE_BOOKED_FOR_SHIPMENT_DATE"  ,
"PO_LINE_TRANSIT_RESN_CODE"  ,
"PO_LINE_MOVE_TYPE_CODE"  ,
"PO_LINE_AGENT_COMMISSION_RATE"  ,
"PO_LINE_AGENT_COMMISSION_AMT"  ,
"PO_LINE_ADDL_ARTICLE_NO"  ,
"PO_LINE_ADDL_ARTICLE_QTY"  ,
"PO_LINE_FACTORY_VENDOR_ID"  ,
"PO_LINE_STUFFING_LOC_VENDOR_ID"  ,
"PO_LINE_SOURCING_AGENT_VENDOR_ID"  ,
"PO_LINE_FREIGHT_FORWARDER_VENDOR_ID"  ,
"PO_LINE_LETTER_OF_CREDIT_NO"  ,
"PO_LINE_OPEN_ACCT_NO"  ,
"PO_LINE_ARTICLE_LENGTH"  ,
"PO_LINE_ARTICLE_WIDTH"  ,
"PO_LINE_ARTICLE_HEIGHT"  ,
"PO_LINE_ARTICLE_DIMENSIONS_UOM"  ,
"PO_LINE_ARTICLE_WEIGHT"  ,
"PO_LINE_ARTICLE_WEIGHT_UOM"  ,
"PO_TOTAL_WEIGHT"  ,
"PO_LINE_ARTICLE_VOLUME"  ,
"PO_LINE_ARTICLE_VOLUME_UOM"  ,
"PO_TOTAL_VOLUME"  ,
"HTS_CODE"  ,
"PO_LINE_DUTY_RATE"  ,
"PO_LINE_DUTY_AMT"  ,
"PO_LINE_ADDL_HTS_CODE_1"  ,
"PO_LINE_ADDL_DUTY_RATE_1"  ,
"PO_LINE_ADDL_DUTY_AMT_1"  ,
"PO_LINE_ADDL_HTS_CODE_2"  ,
"PO_LINE_ADDL_DUTY_RATE_2"  ,
"PO_LINE_ADDL_DUTY_AMT_2"  ,
"PO_HELD_FLAG"  ,
"PO_VENDOR_DOC_DATE"  ,
"cal_MERCH_YEAR"  ,
"cal_YEAR_WEEK"  ,
"cal_YEAR_QUARTER"  ,
"cal_YEAR_PERIOD"  ,
"dest_Facility_Code" ,
"dest_Facility_Name" ,
"dest_Facility_Type" ,
"org_Facility_Code"  ,
"org_Facility_Name" ,
"org_Facility_Type" ,
"item_weight" ,
"ARTICLE_LENGTH" ,
"ARTICLE_WIDTH" ,
"ARTICLE_HEIGHT" ,
"ARTICLE_WEIGHT" 
)
SELECT      DISTINCT 
            "purchase_order_line_w_cal_filtered".*,
             COALESCE(("article"."ARTICLE_WEIGHT"),0)*COALESCE("purchase_order_line_w_cal_filtered"."PO_LINE_ORDER_QTY",0) AS "item_weight",
            "article"."ARTICLE_LENGTH" AS "ARTICLE_LENGTH",
			"article"."ARTICLE_WIDTH" AS "ARTICLE_WIDTH",
			"article"."ARTICLE_HEIGHT" AS "ARTICLE_HEIGHT",
			"article"."ARTICLE_WEIGHT" AS "ARTICLE_WEIGHT"
FROM PURCHASE_ORDER_LINE_W_CAL_FILTERED_JOINED "purchase_order_line_w_cal_filtered"
LEFT JOIN ARTICLE_W_SHP_DIM_PREP "article"
ON "purchase_order_line_w_cal_filtered"."ARTICLE_NO" = "article"."ARTICLE_NO"
WHERE "cal_YEAR_PERIOD" BETWEEN '202306'	AND '202406';

 <br> </br>
INSERT INTO PURCHASE_ORDER_LINE_W_ARTICLE_PREPARED_WINDOWS 
(
"STORE_NO"  ,
"CO_CODE"  ,
"ARTICLE_NO"  ,
"PO_NO"  ,
"PO_LINE_NO"  ,
"PO_DATE"  ,
"po_date_parsed"  ,
"DELIV_DATE"  ,
"deliv_date_parsed"  ,
"PO_TYPE_CODE"  ,
"VENDOR_ID"  ,
"VSR_CODE"  ,
"PO_LINE_CANCELLED_FLAG"  ,
"PO_LINE_ORDER_QTY"  ,
"PO_LINE_ISSUE_QTY"  ,
"PO_LINE_RCVD_QTY"  ,
"PO_LINE_UNIT_PRICE"  ,
"DC_NO"  ,
"PO_TRACKING_NO"  ,
"PO_LINE_TRACKING_NO"  ,
"CURRENT_REPL_TYPE_CODE"  ,
"FREIGHT_TYPE_CODE"  ,
"SHIP_START_DATE"  ,
"SHIP_END_DATE"  ,
"DELIV_START_DATE"  ,
"DELIV_END_DATE"  ,
"PO_LINE_UNIT_FREIGHT_AMT"  ,
"PO_LINE_MANUFACTURER"  ,
"PO_LINE_ORIGIN_COUNTRY_CODE"  ,
"PO_LINE_PORT_OF_ORIGIN"  ,
"PO_LINE_MIN_RCVD_DATE"  ,
"PO_LINE_MAX_RCVD_DATE"  ,
"PO_LINE_DELIVERED_FLAG"  ,
"PO_LINE_CONFIRMED_ON_BOARD_DATE"  ,
"PO_LINE_BOOKED_FOR_SHIPMENT_DATE"  ,
"PO_LINE_TRANSIT_RESN_CODE"  ,
"PO_LINE_MOVE_TYPE_CODE"  ,
"PO_LINE_AGENT_COMMISSION_RATE"  ,
"PO_LINE_AGENT_COMMISSION_AMT"  ,
"PO_LINE_ADDL_ARTICLE_NO"  ,
"PO_LINE_ADDL_ARTICLE_QTY"  ,
"PO_LINE_FACTORY_VENDOR_ID"  ,
"PO_LINE_STUFFING_LOC_VENDOR_ID"  ,
"PO_LINE_SOURCING_AGENT_VENDOR_ID"  ,
"PO_LINE_FREIGHT_FORWARDER_VENDOR_ID"  ,
"PO_LINE_LETTER_OF_CREDIT_NO"  ,
"PO_LINE_OPEN_ACCT_NO"  ,
"PO_LINE_ARTICLE_LENGTH"  ,
"PO_LINE_ARTICLE_WIDTH"  ,
"PO_LINE_ARTICLE_HEIGHT"  ,
"PO_LINE_ARTICLE_DIMENSIONS_UOM"  ,
"PO_LINE_ARTICLE_WEIGHT"  ,
"PO_LINE_ARTICLE_WEIGHT_UOM"  ,
"PO_TOTAL_WEIGHT"  ,
"PO_LINE_ARTICLE_VOLUME"  ,
"PO_LINE_ARTICLE_VOLUME_UOM"  ,
"PO_TOTAL_VOLUME"  ,
"HTS_CODE"  ,
"PO_LINE_DUTY_RATE"  ,
"PO_LINE_DUTY_AMT"  ,
"PO_LINE_ADDL_HTS_CODE_1"  ,
"PO_LINE_ADDL_DUTY_RATE_1"  ,
"PO_LINE_ADDL_DUTY_AMT_1"  ,
"PO_LINE_ADDL_HTS_CODE_2"  ,
"PO_LINE_ADDL_DUTY_RATE_2"  ,
"PO_LINE_ADDL_DUTY_AMT_2"  ,
"PO_HELD_FLAG"  ,
"PO_VENDOR_DOC_DATE"  ,
"cal_MERCH_YEAR"  ,
"cal_YEAR_WEEK"  ,
"cal_YEAR_QUARTER"  ,
"cal_YEAR_PERIOD"  ,
"dest_Facility_Code" ,
"dest_Facility_Name" ,
"dest_Facility_Type" ,
"org_Facility_Code"  ,
"org_Facility_Name" ,
"org_Facility_Type" ,
"item_weight" ,
"ARTICLE_LENGTH" ,
"ARTICLE_WIDTH" ,
"ARTICLE_HEIGHT" ,
"ARTICLE_WEIGHT" ,
"po_weight" 
)
SELECT DISTINCT *,
   SUM("item_weight") OVER (PARTITION BY "PO_NO") AS "po_weight"
FROM PURCHASE_ORDER_LINE_W_ARTICLE_PREPARED
WHERE "cal_YEAR_PERIOD" BETWEEN '202306'	AND '202406';
	   
 <br> </br>
INSERT INTO  SMALL_PACKAGE_ORDERS
(
"STORE_NO"  ,
"CO_CODE"  ,
"ARTICLE_NO"  ,
"PO_NO"  ,
"PO_LINE_NO"  ,
"PO_DATE"  ,
"po_date_parsed"  ,
"DELIV_DATE"  ,
"deliv_date_parsed"  ,
"PO_TYPE_CODE"  ,
"VENDOR_ID"  ,
"VSR_CODE"  ,
"PO_LINE_CANCELLED_FLAG"  ,
"PO_LINE_ORDER_QTY"  ,
"PO_LINE_ISSUE_QTY"  ,
"PO_LINE_RCVD_QTY"  ,
"PO_LINE_UNIT_PRICE"  ,
"DC_NO"  ,
"PO_TRACKING_NO"  ,
"PO_LINE_TRACKING_NO"  ,
"CURRENT_REPL_TYPE_CODE"  ,
"FREIGHT_TYPE_CODE"  ,
"SHIP_START_DATE"  ,
"SHIP_END_DATE"  ,
"DELIV_START_DATE"  ,
"DELIV_END_DATE"  ,
"PO_LINE_UNIT_FREIGHT_AMT"  ,
"PO_LINE_MANUFACTURER"  ,
"PO_LINE_ORIGIN_COUNTRY_CODE"  ,
"PO_LINE_PORT_OF_ORIGIN"  ,
"PO_LINE_MIN_RCVD_DATE"  ,
"PO_LINE_MAX_RCVD_DATE"  ,
"PO_LINE_DELIVERED_FLAG"  ,
"PO_LINE_CONFIRMED_ON_BOARD_DATE"  ,
"PO_LINE_BOOKED_FOR_SHIPMENT_DATE"  ,
"PO_LINE_TRANSIT_RESN_CODE"  ,
"PO_LINE_MOVE_TYPE_CODE"  ,
"PO_LINE_AGENT_COMMISSION_RATE"  ,
"PO_LINE_AGENT_COMMISSION_AMT"  ,
"PO_LINE_ADDL_ARTICLE_NO"  ,
"PO_LINE_ADDL_ARTICLE_QTY"  ,
"PO_LINE_FACTORY_VENDOR_ID"  ,
"PO_LINE_STUFFING_LOC_VENDOR_ID"  ,
"PO_LINE_SOURCING_AGENT_VENDOR_ID"  ,
"PO_LINE_FREIGHT_FORWARDER_VENDOR_ID"  ,
"PO_LINE_LETTER_OF_CREDIT_NO"  ,
"PO_LINE_OPEN_ACCT_NO"  ,
"PO_LINE_ARTICLE_LENGTH"  ,
"PO_LINE_ARTICLE_WIDTH"  ,
"PO_LINE_ARTICLE_HEIGHT"  ,
"PO_LINE_ARTICLE_DIMENSIONS_UOM"  ,
"PO_LINE_ARTICLE_WEIGHT"  ,
"PO_LINE_ARTICLE_WEIGHT_UOM"  ,
"PO_TOTAL_WEIGHT"  ,
"PO_LINE_ARTICLE_VOLUME"  ,
"PO_LINE_ARTICLE_VOLUME_UOM"  ,
"PO_TOTAL_VOLUME"  ,
"HTS_CODE"  ,
"PO_LINE_DUTY_RATE"  ,
"PO_LINE_DUTY_AMT"  ,
"PO_LINE_ADDL_HTS_CODE_1"  ,
"PO_LINE_ADDL_DUTY_RATE_1"  ,
"PO_LINE_ADDL_DUTY_AMT_1"  ,
"PO_LINE_ADDL_HTS_CODE_2"  ,
"PO_LINE_ADDL_DUTY_RATE_2"  ,
"PO_LINE_ADDL_DUTY_AMT_2"  ,
"PO_HELD_FLAG"  ,
"PO_VENDOR_DOC_DATE"  ,
"cal_MERCH_YEAR"  ,
"cal_YEAR_WEEK"  ,
"cal_YEAR_QUARTER"  ,
"cal_YEAR_PERIOD"  ,
"dest_Facility_Code" ,
"dest_Facility_Name" ,
"dest_Facility_Type" ,
"org_Facility_Code"  ,
"org_Facility_Name" ,
"org_Facility_Type" ,
"item_weight" ,
"ARTICLE_LENGTH" ,
"ARTICLE_WIDTH" ,
"ARTICLE_HEIGHT" ,
"ARTICLE_WEIGHT" ,
"po_weight" ,
"small_package_flag" 
)
SELECT DISTINCT *,
    CASE 
    WHEN "po_weight" < 150
    AND "PO_NO">=1010000000 AND "PO_NO"<=1049999999
    AND NOT (VENDOR_ID >=570000 AND  VENDOR_ID <=579999)
    AND PO_LINE_ORDER_QTY > 0
    AND FREIGHT_TYPE_CODE = 'FCT'
    THEN 1
    ELSE 0  
    END AS small_package_flag
FROM PURCHASE_ORDER_LINE_W_ARTICLE_PREPARED_WINDOWS
WHERE "cal_YEAR_PERIOD" BETWEEN '202306'	AND '202406';