<br> </br>

INSERT INTO SALES_W_HIERARCHY
( 
    "STORE_NO" ,
    "CO_CODE" ,
    "STORE_DIM_KEY" ,
    "TRANS_NO" ,
    "TRANS_SEQ_NO" ,
    "ARTICLE_NO" ,
    "ARTICLE_DIM_KEY" ,
    "CO_ARTICLE_DIM_KEY" ,
    "TIME_DIM_KEY" ,
    "EMPL_DIM_KEY" ,
    "TRANS_POSTAL_CODE" ,
    "TRANS_TS" ,
    "SUM_TYPE_CODE" ,
    "VENDOR_ID" ,
    "DC_NO" ,
    "REPL_TYPE_CODE" ,
    "PRICE_ZONE_CODE" ,
    "CURRENT_VENDOR_ID" ,
    "CURRENT_DC_NO" ,
    "CURRENT_REPL_TYPE_CODE" ,
    "SALE_REFUND_IND" ,
    "PRICE_OVRD_FLAG" ,
    "SCAN_ITEM_FLAG" ,
    "PRICE_TYPE_CODE" ,
    "EMPL_ID" ,
    "CUST_EMPL_ID" ,
    "EC_ID" ,
    "DISC_RESN_CODE" ,
    "OVRD_RESN_CODE" ,
    "RETURN_RESN_CODE" ,
    "TAX_EXEMPT_STATUS_CODE" ,
    "TAX_TYPE_CODE" ,
    "TRANS_TYPE_CODE" ,
    "TERM_NO" ,
    "UPC" ,
    "PROMO_NO" , 
    "TRANS_ARTICLE_COUNT" ,
    "TRANS_LINE_COUNT" ,
    "SALES_QTY" ,
    "UNIT_PRICE" ,
    "ORIG_UNIT_PRICE" ,
    "UNIT_COST" ,
    "SALES_AMT" ,
    "COST_AMT" ,
    "DISC_AMT" ,
    "OVRD_AMT" ,
    "TRANS_TAX_AMT" ,
    "ORIG_TRANS_NO" ,
    "TRANS_LINE_DESC" ,
    "VENDOR_PART_NO" ,
    "OMS_ORDER_NO" ,
    "LOYALTY_ID" ,
    "BUY_ONLINE_CODE" ,
    "CUST_DIM_KEY" ,
    "SAP_BP_ID" ,
    "RECORD_CREATE_TS" ,
    "DISC_CODE" ,
    "CAL_DATE" ,
    "MERCH_YEAR" ,
    "ACCT_YEAR" ,
    "YEAR_WEEK" ,
    "YEAR_QUARTER" ,
    "YEAR_PERIOD" ,
    "CHAIN_PROD" ,
    "ARTICLE_DESC" ,
    "ARTICLE_FULL" ,
    "ARTICLE_TYPE_NAME" ,
    "ARTICLE_TYPE_CODE" ,
    "ARTICLE_TYPE_FULL" ,
    "LABEL_TYPE_CODE" ,
    "UOM_CODE" ,
    "UOM_DESC" ,
    "UOM_FULL" , 
    "PLANOGRAM_NO" ,
    "PLANOGRAM_FACE" ,
    "PLANOGRAM_SEQ" ,
    "ARTICLE_CREATE_DATE" ,
    "ACCT_POOL_CODE" ,
    "ARTICLE_LENGTH" ,
    "ARTICLE_WIDTH" ,
    "ARTICLE_HEIGHT" ,
    "ARTICLE_WEIGHT" ,
    "ARTICLE_SIZE" ,
    "ARTICLE_COUNT" ,
    "ARTICLE_COLOR" ,
    "LOC_TYPE_CODE" ,
    "WORKSHEET_CYCLE" ,
    "PARENT_ARTICLE_NO" ,
    "PARENT_ARTICLE_DESC" ,
    "PARENT_ARTICLE_FULL" ,
    "POG_CAT_STRATEGY" ,
    "POG_KPI_WT_SALES" ,
    "POG_KPI_WT_PROFIT" ,
    "POG_KPI_WT_UNIT_MV" ,
    "PRIMARY_VENDOR_ID" ,
    "ARTICLE_WTY_START_DATE" ,
    "SPACE_PLANNER_NO" ,
    "ARTICLE_CAT_CODE" ,
    "ARTICLE_CAT_NAME" ,
    "ARTICLE_CAT_FULL" ,
    "DEPT_CODE" ,
    "DEPT_NAME" ,
    "DEPT_FULL" ,
    "LOB_NO" ,
    "LOB_DESC" , 
    "LOB_FULL" ,
    "MAJ_DEPT_NO" ,
    "MAJ_DEPT_DESC" ,
    "MAJ_DEPT_FULL" ,
    "DISPLAY_ARTICLE_FLAG" ,
    "SEASON_DESC" ,
    "ARTICLE_THEME_DESC" ,
    "BRAND_NAME" ,
    "PVT_LABEL_DESC" ,
    "ARTICLE_FREIGHT_START_DATE" ,
    "ARTICLE_FREIGHT_AMT" ,
    "ADDL_ARTICLE_NO" ,
    "ARTICLE_MIN_ADV_PRICE" ,
    "OLD_ARTICLE_NO" ,
    "MANUFACTURER_VENDOR_NAME" 
)
SELECT 
    "sls"."STORE_NO",
    "sls"."CO_CODE",
    "sls"."STORE_DIM_KEY",
    "sls"."TRANS_NO",
    "sls"."TRANS_SEQ_NO",
    "sls"."ARTICLE_NO",
    "sls"."ARTICLE_DIM_KEY",
    "sls"."CO_ARTICLE_DIM_KEY",
    "sls"."TIME_DIM_KEY",
    "sls"."EMPL_DIM_KEY",
    "sls"."TRANS_POSTAL_CODE",
    "sls"."TRANS_TS",
    "sls"."SUM_TYPE_CODE",
    "sls"."VENDOR_ID",
    "sls"."DC_NO",
    "sls"."REPL_TYPE_CODE",
    "sls"."PRICE_ZONE_CODE",
    "sls"."CURRENT_VENDOR_ID",
    "sls"."CURRENT_DC_NO",
    "sls"."CURRENT_REPL_TYPE_CODE",
    "sls"."SALE_REFUND_IND",
    "sls"."PRICE_OVRD_FLAG",
    "sls"."SCAN_ITEM_FLAG",
    "sls"."PRICE_TYPE_CODE",
    "sls"."EMPL_ID",
    "sls"."CUST_EMPL_ID",
    "sls"."EC_ID",
    "sls"."DISC_RESN_CODE",
    "sls"."OVRD_RESN_CODE",
    "sls"."RETURN_RESN_CODE",
    "sls"."TAX_EXEMPT_STATUS_CODE",
    "sls"."TAX_TYPE_CODE",
    "sls"."TRANS_TYPE_CODE",
    "sls"."TERM_NO",
    "sls"."UPC",
    "sls"."PROMO_NO",
    "sls"."TRANS_ARTICLE_COUNT",
    "sls"."TRANS_LINE_COUNT",
    "sls"."SALES_QTY",
    "sls"."UNIT_PRICE",
    "sls"."ORIG_UNIT_PRICE",
    "sls"."UNIT_COST",
    "sls"."SALES_AMT",
    "sls"."COST_AMT",
    "sls"."DISC_AMT",
    "sls"."OVRD_AMT",
    "sls"."TRANS_TAX_AMT",
    "sls"."ORIG_TRANS_NO",
    "sls"."TRANS_LINE_DESC",
    "sls"."VENDOR_PART_NO",
    "sls"."OMS_ORDER_NO",
    "sls"."LOYALTY_ID",
    "sls"."BUY_ONLINE_CODE",
    "sls"."CUST_DIM_KEY",
    "sls"."SAP_BP_ID",
    "sls"."RECORD_CREATE_TS",
    "sls"."DISC_CODE",
    "sls"."CAL_DATE",
    "sls"."MERCH_YEAR",
    "sls"."ACCT_YEAR",
    "sls"."YEAR_WEEK",
    "sls"."YEAR_QUARTER",
    "sls"."YEAR_PERIOD",
    "art"."CHAIN_PROD",
    "art"."ARTICLE_DESC",
    "art"."ARTICLE_FULL",
    "art"."ARTICLE_TYPE_NAME",
    "art"."ARTICLE_TYPE_CODE",
    "art"."ARTICLE_TYPE_FULL",
    "art"."LABEL_TYPE_CODE",
    "art"."UOM_CODE",
    "art"."UOM_DESC",
    "art"."UOM_FULL",
    "art"."PLANOGRAM_NO",
    "art"."PLANOGRAM_FACE",
    "art"."PLANOGRAM_SEQ",
    "art"."ARTICLE_CREATE_DATE",
    "art"."ACCT_POOL_CODE",
    "art"."ARTICLE_LENGTH",
    "art"."ARTICLE_WIDTH",
    "art"."ARTICLE_HEIGHT",
    "art"."ARTICLE_WEIGHT",
    "art"."ARTICLE_SIZE",
    "art"."ARTICLE_COUNT",
    "art"."ARTICLE_COLOR",
    "art"."LOC_TYPE_CODE",
    "art"."WORKSHEET_CYCLE",
    "art"."PARENT_ARTICLE_NO",
    "art"."PARENT_ARTICLE_DESC",
    "art"."PARENT_ARTICLE_FULL",
    "art"."POG_CAT_STRATEGY",
    "art"."POG_KPI_WT_SALES",
    "art"."POG_KPI_WT_PROFIT",
    "art"."POG_KPI_WT_UNIT_MV",
    "art"."PRIMARY_VENDOR_ID",
    "art"."ARTICLE_WTY_START_DATE",
    "art"."SPACE_PLANNER_NO",
    "art"."ARTICLE_CAT_CODE",
    "art"."ARTICLE_CAT_NAME",
    "art"."ARTICLE_CAT_FULL",
    "art"."DEPT_CODE",
    "art"."DEPT_NAME",
    "art"."DEPT_FULL",
    "art"."LOB_NO",
    "art"."LOB_DESC",
    "art"."LOB_FULL",
    "art"."MAJ_DEPT_NO",
    "art"."MAJ_DEPT_DESC",
    "art"."MAJ_DEPT_FULL",
    "art"."DISPLAY_ARTICLE_FLAG",
    "art"."SEASON_DESC",
    "art"."ARTICLE_THEME_DESC",
    "art"."BRAND_NAME",
    "art"."PVT_LABEL_DESC",
    "art"."ARTICLE_FREIGHT_START_DATE",
    "art"."ARTICLE_FREIGHT_AMT",
    "art"."ADDL_ARTICLE_NO",
    "art"."ARTICLE_MIN_ADV_PRICE",
    "art"."OLD_ARTICLE_NO",
    "art"."MANUFACTURER_VENDOR_NAME"
FROM SALES_W_CAL_FILTERED  "sls" 
LEFT JOIN ARTICLE_W_SHP_DIM_PREP "art" ON "sls"."ARTICLE_NO" = "art"."ARTICLE_NO"
WHERE "sls"."YEAR_PERIOD" BETWEEN '202306'	AND   '202406';
<br>  </br>

INSERT INTO SALES_W_VENDOR_PREP_TMP 
(
    "STORE_NO"  ,
    "CO_CODE"  ,
    "STORE_DIM_KEY"  ,
    "TRANS_NO"  ,
    "TRANS_SEQ_NO"  ,
    "ARTICLE_NO"  ,
    "ARTICLE_DIM_KEY"  ,
    "CO_ARTICLE_DIM_KEY"  ,
    "TIME_DIM_KEY"  ,
    "EMPL_DIM_KEY"  ,
    "TRANS_POSTAL_CODE"  ,
    "TRANS_TS"  ,
    "SUM_TYPE_CODE"  ,
    "VENDOR_ID"  ,
    "DC_NO"  ,
    "REPL_TYPE_CODE"  ,
    "PRICE_ZONE_CODE"  ,
    "CURRENT_VENDOR_ID"  ,
    "CURRENT_DC_NO"  ,
    "CURRENT_REPL_TYPE_CODE"  ,
    "SALE_REFUND_IND"  ,
    "PRICE_OVRD_FLAG"  ,
    "SCAN_ITEM_FLAG"  ,
    "PRICE_TYPE_CODE"  ,
    "EMPL_ID"  ,
    "CUST_EMPL_ID"  ,
    "EC_ID"  ,
    "DISC_RESN_CODE"  ,
    "OVRD_RESN_CODE"  ,
    "RETURN_RESN_CODE"  ,
    "TAX_EXEMPT_STATUS_CODE"  ,
    "TAX_TYPE_CODE"  ,
    "TRANS_TYPE_CODE"  ,
    "TERM_NO"  ,
    "UPC"  ,
    "PROMO_NO"  ,
    "TRANS_ARTICLE_COUNT"  ,
    "TRANS_LINE_COUNT"  ,
    "SALES_QTY"  ,
    "UNIT_PRICE"  ,
    "ORIG_UNIT_PRICE"  ,
    "UNIT_COST"  ,
    "SALES_AMT"  ,
    "COST_AMT"  ,
    "DISC_AMT"  ,
    "OVRD_AMT"  ,
    "TRANS_TAX_AMT"  ,
    "ORIG_TRANS_NO"  ,
    "TRANS_LINE_DESC"  ,
    "VENDOR_PART_NO"  ,
    "OMS_ORDER_NO"  ,
    "LOYALTY_ID"  ,
    "BUY_ONLINE_CODE"  ,
    "CUST_DIM_KEY"  ,
    "SAP_BP_ID"  ,
    "RECORD_CREATE_TS"  ,
    "DISC_CODE"  ,
    "CAL_DATE"  ,
    "MERCH_YEAR"  ,
    "ACCT_YEAR"  ,
    "YEAR_WEEK"  ,
    "YEAR_QUARTER"  ,
    "YEAR_PERIOD"  ,
    "CHAIN_PROD"  ,
    "ARTICLE_DESC"  ,
    "ARTICLE_FULL"  ,
    "ARTICLE_TYPE_NAME"  ,
    "ARTICLE_TYPE_CODE"  ,
    "ARTICLE_TYPE_FULL"  ,
    "LABEL_TYPE_CODE"  ,
    "UOM_CODE"  ,
    "UOM_DESC"  ,
    "UOM_FULL"  ,
    "PLANOGRAM_NO"  ,
    "PLANOGRAM_FACE"  ,
    "PLANOGRAM_SEQ"  ,
    "ARTICLE_CREATE_DATE"  ,
    "ACCT_POOL_CODE"  ,
    "ARTICLE_LENGTH"  ,
    "ARTICLE_WIDTH"  ,
    "ARTICLE_HEIGHT"  ,
    "ARTICLE_WEIGHT"  ,
    "ARTICLE_SIZE"  ,
    "ARTICLE_COUNT"  ,
    "ARTICLE_COLOR"  ,
    "LOC_TYPE_CODE"  ,
    "WORKSHEET_CYCLE"  ,
    "PARENT_ARTICLE_NO"  ,
    "PARENT_ARTICLE_DESC"  ,
    "PARENT_ARTICLE_FULL"  ,
    "POG_CAT_STRATEGY"  ,
    "POG_KPI_WT_SALES"  ,
    "POG_KPI_WT_PROFIT"  ,
    "POG_KPI_WT_UNIT_MV"  ,
    "PRIMARY_VENDOR_ID"  ,
    "ARTICLE_WTY_START_DATE"  ,
    "SPACE_PLANNER_NO"  ,
    "ARTICLE_CAT_CODE"  ,
    "ARTICLE_CAT_NAME"  ,
    "ARTICLE_CAT_FULL"  ,
    "DEPT_CODE"  ,
    "DEPT_NAME"  ,
    "DEPT_FULL"  ,
    "LOB_NO"  ,
    "LOB_DESC"  ,
    "LOB_FULL"  ,
    "MAJ_DEPT_NO"  ,
    "MAJ_DEPT_DESC"  ,
    "MAJ_DEPT_FULL"  ,
    "DISPLAY_ARTICLE_FLAG"  ,
    "SEASON_DESC"  ,
    "ARTICLE_THEME_DESC"  ,
    "BRAND_NAME"  ,
    "PVT_LABEL_DESC"  ,
    "ARTICLE_FREIGHT_START_DATE"  ,
    "ARTICLE_FREIGHT_AMT"  ,
    "ADDL_ARTICLE_NO"  ,
    "ARTICLE_MIN_ADV_PRICE"  ,
    "OLD_ARTICLE_NO"  ,
    "MANUFACTURER_VENDOR_NAME"  ,
    "VENDOR_COID"  ,
    "VENDOR_NAME"  ,
    "VENDOR_FULL"  ,
    "VENDOR_CO_NAME"  ,
    "REGION_CODE"  ,
    "VENDOR_TYPE_CODE"  ,
    "DATE_PARSED" )
SELECT 
    "sls"."STORE_NO",
    "sls"."CO_CODE",
    "sls"."STORE_DIM_KEY",
    "sls"."TRANS_NO",
    "sls"."TRANS_SEQ_NO",
    "sls"."ARTICLE_NO",
    "sls"."ARTICLE_DIM_KEY",
    "sls"."CO_ARTICLE_DIM_KEY",
    "sls"."TIME_DIM_KEY",
    "sls"."EMPL_DIM_KEY",
    "sls"."TRANS_POSTAL_CODE",
    "sls"."TRANS_TS",
    "sls"."SUM_TYPE_CODE",
    "sls"."VENDOR_ID",
    "sls"."DC_NO",
    "sls"."REPL_TYPE_CODE",
    "sls"."PRICE_ZONE_CODE",
    "sls"."CURRENT_VENDOR_ID",
    "sls"."CURRENT_DC_NO",
    "sls"."CURRENT_REPL_TYPE_CODE",
    "sls"."SALE_REFUND_IND",
    "sls"."PRICE_OVRD_FLAG",
    "sls"."SCAN_ITEM_FLAG",
    "sls"."PRICE_TYPE_CODE",
    "sls"."EMPL_ID",
    "sls"."CUST_EMPL_ID",
    "sls"."EC_ID",
    "sls"."DISC_RESN_CODE",
    "sls"."OVRD_RESN_CODE",
    "sls"."RETURN_RESN_CODE",
    "sls"."TAX_EXEMPT_STATUS_CODE",
    "sls"."TAX_TYPE_CODE",
    "sls"."TRANS_TYPE_CODE",
    "sls"."TERM_NO",
    "sls"."UPC",
    "sls"."PROMO_NO",
    "sls"."TRANS_ARTICLE_COUNT",
    "sls"."TRANS_LINE_COUNT",
    "sls"."SALES_QTY",
    "sls"."UNIT_PRICE",
    "sls"."ORIG_UNIT_PRICE",
    "sls"."UNIT_COST",
    "sls"."SALES_AMT",
    "sls"."COST_AMT",
    "sls"."DISC_AMT",
    "sls"."OVRD_AMT",
    "sls"."TRANS_TAX_AMT",
    "sls"."ORIG_TRANS_NO",
    "sls"."TRANS_LINE_DESC",
    "sls"."VENDOR_PART_NO",
    "sls"."OMS_ORDER_NO",
    "sls"."LOYALTY_ID",
    "sls"."BUY_ONLINE_CODE",
    "sls"."CUST_DIM_KEY",
    "sls"."SAP_BP_ID",
    "sls"."RECORD_CREATE_TS",
    "sls"."DISC_CODE",
    "sls"."CAL_DATE",
    "sls"."MERCH_YEAR",
    "sls"."ACCT_YEAR",
    "sls"."YEAR_WEEK",
    "sls"."YEAR_QUARTER",
    "sls"."YEAR_PERIOD",
    "sls"."CHAIN_PROD",
    "sls"."ARTICLE_DESC",
    "sls"."ARTICLE_FULL",
    "sls"."ARTICLE_TYPE_NAME",
    "sls"."ARTICLE_TYPE_CODE",
    "sls"."ARTICLE_TYPE_FULL",
    "sls"."LABEL_TYPE_CODE",
    "sls"."UOM_CODE",
    "sls"."UOM_DESC",
    "sls"."UOM_FULL",
    "sls"."PLANOGRAM_NO",
    "sls"."PLANOGRAM_FACE",
    "sls"."PLANOGRAM_SEQ",
    "sls"."ARTICLE_CREATE_DATE",
    "sls"."ACCT_POOL_CODE",
    "sls"."ARTICLE_LENGTH",
    "sls"."ARTICLE_WIDTH",
    "sls"."ARTICLE_HEIGHT",
    "sls"."ARTICLE_WEIGHT",
    "sls"."ARTICLE_SIZE",
    "sls"."ARTICLE_COUNT",
    "sls"."ARTICLE_COLOR",
    "sls"."LOC_TYPE_CODE",
    "sls"."WORKSHEET_CYCLE",
    "sls"."PARENT_ARTICLE_NO",
    "sls"."PARENT_ARTICLE_DESC",
    "sls"."PARENT_ARTICLE_FULL",
    "sls"."POG_CAT_STRATEGY",
    "sls"."POG_KPI_WT_SALES",
    "sls"."POG_KPI_WT_PROFIT",
    "sls"."POG_KPI_WT_UNIT_MV",
    "sls"."PRIMARY_VENDOR_ID",
    "sls"."ARTICLE_WTY_START_DATE",
    "sls"."SPACE_PLANNER_NO",
    "sls"."ARTICLE_CAT_CODE",
    "sls"."ARTICLE_CAT_NAME",
    "sls"."ARTICLE_CAT_FULL",
    "sls"."DEPT_CODE",
    "sls"."DEPT_NAME",
    "sls"."DEPT_FULL",
    "sls"."LOB_NO",
    "sls"."LOB_DESC",
    "sls"."LOB_FULL",
    "sls"."MAJ_DEPT_NO",
    "sls"."MAJ_DEPT_DESC",
    "sls"."MAJ_DEPT_FULL",
    "sls"."DISPLAY_ARTICLE_FLAG",
    "sls"."SEASON_DESC",
    "sls"."ARTICLE_THEME_DESC",
    "sls"."BRAND_NAME",
    "sls"."PVT_LABEL_DESC",
    "sls"."ARTICLE_FREIGHT_START_DATE",
    "sls"."ARTICLE_FREIGHT_AMT",
    "sls"."ADDL_ARTICLE_NO",
    "sls"."ARTICLE_MIN_ADV_PRICE",
    "sls"."OLD_ARTICLE_NO",
    "sls"."MANUFACTURER_VENDOR_NAME",
    "ven"."VENDOR_COID",
    "ven"."VENDOR_NAME",
    "ven"."VENDOR_FULL",
    "ven"."VENDOR_CO_NAME",
    "ven"."REGION_CODE",
    "ven"."VENDOR_TYPE_CODE",
 CAST(TO_TIMESTAMP_NTZ(CAST("sls"."TIME_DIM_KEY" AS VARCHAR),'YYYYMMDD') AS DATE) AS "DATE_PARSED"
FROM SALES_W_HIERARCHY "sls"
LEFT JOIN EDW.VW_VENDOR "ven" ON "sls"."VENDOR_ID" = "ven"."VENDOR_ID"
WHERE "sls"."YEAR_PERIOD" BETWEEN '202306'	AND   '202406';

<br> </br>

INSERT INTO  SALES_W_LIST_COST_WINDOWS_STG 
(
    "STORE_NO"  ,
    "CO_CODE"  ,
    "STORE_DIM_KEY"  ,
    "TRANS_NO"  ,
    "TRANS_SEQ_NO"  ,
    "ARTICLE_NO"  ,
    "ARTICLE_DIM_KEY"  ,
    "CO_ARTICLE_DIM_KEY"  ,
    "TIME_DIM_KEY"  ,
    "DATE_PARSED"  ,
    "EMPL_DIM_KEY"  ,
    "TRANS_POSTAL_CODE"  ,
    "TRANS_TS"  ,
    "SUM_TYPE_CODE"  ,
    "VENDOR_ID"  ,
    "DC_NO"  ,
    "REPL_TYPE_CODE"  ,
    "PRICE_ZONE_CODE"  ,
    "CURRENT_VENDOR_ID"  ,
    "CURRENT_DC_NO"  ,
    "CURRENT_REPL_TYPE_CODE"  ,
    "SALE_REFUND_IND"  ,
    "PRICE_OVRD_FLAG"  ,
    "SCAN_ITEM_FLAG"  ,
    "PRICE_TYPE_CODE"  ,
    "EMPL_ID"  ,
    "CUST_EMPL_ID"  ,
    "EC_ID"  ,
    "DISC_RESN_CODE"  ,
    "OVRD_RESN_CODE"  ,
    "RETURN_RESN_CODE"  ,
    "TAX_EXEMPT_STATUS_CODE"  ,
    "TAX_TYPE_CODE"  ,
    "TRANS_TYPE_CODE"  ,
    "TERM_NO"  ,
    "UPC"  ,
    "PROMO_NO"  ,
    "TRANS_ARTICLE_COUNT"  ,
    "TRANS_LINE_COUNT"  ,
    "SALES_QTY"  ,
    "UNIT_PRICE"  ,
    "ORIG_UNIT_PRICE"  ,
    "UNIT_COST"  ,
    "SALES_AMT"  ,
    "COST_AMT"  ,
    "DISC_AMT"  ,
    "OVRD_AMT"  ,
    "TRANS_TAX_AMT"  ,
    "ORIG_TRANS_NO"  ,
    "TRANS_LINE_DESC"  ,
    "VENDOR_PART_NO"  ,
    "OMS_ORDER_NO"  ,
    "LOYALTY_ID"  ,
    "BUY_ONLINE_CODE"  ,
    "CUST_DIM_KEY"  ,
    "SAP_BP_ID"  ,
    "RECORD_CREATE_TS"  ,
    "DISC_CODE"  ,
    "CAL_DATE"  ,
    "MERCH_YEAR"  ,
    "ACCT_YEAR"  ,
    "YEAR_WEEK"  ,
    "YEAR_QUARTER"  ,
    "YEAR_PERIOD"  ,
    "CHAIN_PROD"  ,
    "ARTICLE_DESC"  ,
    "ARTICLE_FULL"  ,
    "ARTICLE_TYPE_NAME"  ,
    "ARTICLE_TYPE_CODE"  ,
    "ARTICLE_TYPE_FULL"  ,
    "LABEL_TYPE_CODE"  ,
    "UOM_CODE"  ,
    "UOM_DESC"  ,
    "UOM_FULL"  ,
    "PLANOGRAM_NO"  ,
    "PLANOGRAM_FACE"  ,
    "PLANOGRAM_SEQ"  ,
    "ARTICLE_CREATE_DATE"  ,
    "ACCT_POOL_CODE"  ,
    "ARTICLE_LENGTH"  ,
    "ARTICLE_WIDTH"  ,
    "ARTICLE_HEIGHT"  ,
    "ARTICLE_WEIGHT"  ,
    "ARTICLE_SIZE"  ,
    "ARTICLE_COUNT"  ,
    "ARTICLE_COLOR"  ,
    "LOC_TYPE_CODE"  ,
    "WORKSHEET_CYCLE"  ,
    "PARENT_ARTICLE_NO"  ,
    "PARENT_ARTICLE_DESC"  ,
    "PARENT_ARTICLE_FULL"  ,
    "POG_CAT_STRATEGY"  ,
    "POG_KPI_WT_SALES"  ,
    "POG_KPI_WT_PROFIT"  ,
    "POG_KPI_WT_UNIT_MV"  ,
    "PRIMARY_VENDOR_ID"  ,
    "ARTICLE_WTY_START_DATE"  ,
    "SPACE_PLANNER_NO"  ,
    "ARTICLE_CAT_CODE"  ,
    "ARTICLE_CAT_NAME"  ,
    "ARTICLE_CAT_FULL"  ,
    "DEPT_CODE"  ,
    "DEPT_NAME"  ,
    "DEPT_FULL"  ,
    "LOB_NO"  ,
    "LOB_DESC"  ,
    "LOB_FULL"  ,
    "MAJ_DEPT_NO"  ,
    "MAJ_DEPT_DESC"  ,
    "MAJ_DEPT_FULL"  ,
    "DISPLAY_ARTICLE_FLAG"  ,
    "SEASON_DESC" ,
    "ARTICLE_THEME_DESC"  ,
    "BRAND_NAME"  ,
    "PVT_LABEL_DESC"  ,
    "ARTICLE_FREIGHT_START_DATE"  ,
    "ARTICLE_FREIGHT_AMT"  ,
    "ADDL_ARTICLE_NO"  ,
    "ARTICLE_MIN_ADV_PRICE"  ,
    "OLD_ARTICLE_NO"  ,
    "MANUFACTURER_VENDOR_NAME"  ,
    "VENDOR_COID"  ,
    "VENDOR_NAME"  ,
    "VENDOR_FULL"  ,
    "VENDOR_CO_NAME"  ,
    "REGION_CODE"  ,
    "VENDOR_TYPE_CODE"  ,
    "VENDOR_BASE_SHIPPING_QTY" ,
    "VENDOR_PLANNED_DELIV_DAYS"  ,
    "VENDOR_PRICE"  ,
    "VENDOR_ARTICLE_QUOTE_NO"  ,
    "VENDOR_ARTICLE_RETURN_AGREEMENT_CODE"  ,
    "VSR_CODE" ,
    "rownumber" 
)
SELECT 
    "slcal"."STORE_NO" ,
    "slcal"."CO_CODE" ,
    "slcal"."STORE_DIM_KEY" ,
    "slcal"."TRANS_NO" ,
    "slcal"."TRANS_SEQ_NO" ,
    "slcal"."ARTICLE_NO" ,
    "slcal"."ARTICLE_DIM_KEY" ,
    "slcal"."CO_ARTICLE_DIM_KEY" ,
    "slcal"."TIME_DIM_KEY" ,
    "slcal"."DATE_PARSED" ,
    "slcal"."EMPL_DIM_KEY" ,
    "slcal"."TRANS_POSTAL_CODE" ,
    "slcal"."TRANS_TS" ,
    "slcal"."SUM_TYPE_CODE" ,
    "slcal"."VENDOR_ID" ,
    "slcal"."DC_NO" ,
    "slcal"."REPL_TYPE_CODE" ,
    "slcal"."PRICE_ZONE_CODE" ,
    "slcal"."CURRENT_VENDOR_ID" ,
    "slcal"."CURRENT_DC_NO" ,
    "slcal"."CURRENT_REPL_TYPE_CODE" ,
    "slcal"."SALE_REFUND_IND" ,
    "slcal"."PRICE_OVRD_FLAG" ,
    "slcal"."SCAN_ITEM_FLAG" ,
    "slcal"."PRICE_TYPE_CODE" ,
    "slcal"."EMPL_ID" ,
    "slcal"."CUST_EMPL_ID" ,
    "slcal"."EC_ID" ,
    "slcal"."DISC_RESN_CODE" ,
    "slcal"."OVRD_RESN_CODE" ,
    "slcal"."RETURN_RESN_CODE" ,
    "slcal"."TAX_EXEMPT_STATUS_CODE" ,
    "slcal"."TAX_TYPE_CODE" ,
    "slcal"."TRANS_TYPE_CODE" ,
    "slcal"."TERM_NO" ,
    "slcal"."UPC" ,
    "slcal"."PROMO_NO" ,
    "slcal"."TRANS_ARTICLE_COUNT" ,
    "slcal"."TRANS_LINE_COUNT" ,
    "slcal"."SALES_QTY" ,
    "slcal"."UNIT_PRICE" ,
    "slcal"."ORIG_UNIT_PRICE" ,
    "slcal"."UNIT_COST" ,
    "slcal"."SALES_AMT" ,
    "slcal"."COST_AMT" ,
    "slcal"."DISC_AMT" ,
    "slcal"."OVRD_AMT" ,
    "slcal"."TRANS_TAX_AMT" ,
    "slcal"."ORIG_TRANS_NO" ,
    "slcal"."TRANS_LINE_DESC" ,
    "slcal"."VENDOR_PART_NO" ,
    "slcal"."OMS_ORDER_NO" ,
    "slcal"."LOYALTY_ID" ,
    "slcal"."BUY_ONLINE_CODE" ,
    "slcal"."CUST_DIM_KEY" ,
    "slcal"."SAP_BP_ID" ,
    "slcal"."RECORD_CREATE_TS" ,
    "slcal"."DISC_CODE" ,
    "slcal"."CAL_DATE" ,
    "slcal"."MERCH_YEAR" ,
    "slcal"."ACCT_YEAR" ,
    "slcal"."YEAR_WEEK" ,
    "slcal"."YEAR_QUARTER" ,
    "slcal"."YEAR_PERIOD" ,
    "slcal"."CHAIN_PROD" ,
    "slcal"."ARTICLE_DESC" ,
    "slcal"."ARTICLE_FULL" ,
    "slcal"."ARTICLE_TYPE_NAME" ,
    "slcal"."ARTICLE_TYPE_CODE" ,
    "slcal"."ARTICLE_TYPE_FULL" ,
    "slcal"."LABEL_TYPE_CODE" ,
    "slcal"."UOM_CODE" ,
    "slcal"."UOM_DESC" ,
    "slcal"."UOM_FULL" ,
    "slcal"."PLANOGRAM_NO" ,
    "slcal"."PLANOGRAM_FACE" ,
    "slcal"."PLANOGRAM_SEQ" ,
    "slcal"."ARTICLE_CREATE_DATE" ,
    "slcal"."ACCT_POOL_CODE" ,
    "slcal"."ARTICLE_LENGTH" ,
    "slcal"."ARTICLE_WIDTH" ,
    "slcal"."ARTICLE_HEIGHT" ,
    "slcal"."ARTICLE_WEIGHT" ,
    "slcal"."ARTICLE_SIZE" ,
    "slcal"."ARTICLE_COUNT" ,
    "slcal"."ARTICLE_COLOR" ,
    "slcal"."LOC_TYPE_CODE" ,
    "slcal"."WORKSHEET_CYCLE" ,
    "slcal"."PARENT_ARTICLE_NO" ,
    "slcal"."PARENT_ARTICLE_DESC" ,
    "slcal"."PARENT_ARTICLE_FULL" ,
    "slcal"."POG_CAT_STRATEGY" ,
    "slcal"."POG_KPI_WT_SALES" ,
    "slcal"."POG_KPI_WT_PROFIT" ,
    "slcal"."POG_KPI_WT_UNIT_MV" ,
    "slcal"."PRIMARY_VENDOR_ID" ,
    "slcal"."ARTICLE_WTY_START_DATE" ,
    "slcal"."SPACE_PLANNER_NO" ,
    "slcal"."ARTICLE_CAT_CODE" ,
    "slcal"."ARTICLE_CAT_NAME" ,
    "slcal"."ARTICLE_CAT_FULL" ,
    "slcal"."DEPT_CODE" ,
    "slcal"."DEPT_NAME" ,
    "slcal"."DEPT_FULL" ,
    "slcal"."LOB_NO" ,
    "slcal"."LOB_DESC" ,
    "slcal"."LOB_FULL" ,
    "slcal"."MAJ_DEPT_NO" ,
    "slcal"."MAJ_DEPT_DESC" ,
    "slcal"."MAJ_DEPT_FULL" ,
    "slcal"."DISPLAY_ARTICLE_FLAG" ,
    "slcal"."SEASON_DESC",
    "slcal"."ARTICLE_THEME_DESC" ,
    "slcal"."BRAND_NAME" ,
    "slcal"."PVT_LABEL_DESC" ,
    "slcal"."ARTICLE_FREIGHT_START_DATE" ,
    "slcal"."ARTICLE_FREIGHT_AMT" ,
    "slcal"."ADDL_ARTICLE_NO" ,
    "slcal"."ARTICLE_MIN_ADV_PRICE" ,
    "slcal"."OLD_ARTICLE_NO" ,
    "slcal"."MANUFACTURER_VENDOR_NAME" ,
    "slcal"."VENDOR_COID" ,
    "slcal"."VENDOR_NAME" ,
    "slcal"."VENDOR_FULL" ,
    "slcal"."VENDOR_CO_NAME" ,
    "slcal"."REGION_CODE" ,
    "slcal"."VENDOR_TYPE_CODE" ,
    "CVA"."VENDOR_BASE_SHIPPING_QTY",
    "CVA"."VENDOR_PLANNED_DELIV_DAYS" ,
    "CVA"."VENDOR_PRICE" ,
    "CVA"."VENDOR_ARTICLE_QUOTE_NO" ,
    "CVA"."VENDOR_ARTICLE_RETURN_AGREEMENT_CODE" ,
    "CVA"."VSR_CODE",
    ROW_NUMBER() OVER (ORDER BY "TIME_DIM_KEY" ASC NULLS FIRST) AS "rownumber"
  FROM SALES_W_VENDOR_PREP_TMP "slcal"
  LEFT JOIN EDW.VW_COMPANY_VENDOR_ARTICLE "CVA"
       ON ("slcal"."ARTICLE_NO" = "CVA"."ARTICLE_NO") AND ("slcal"."VENDOR_ID" = "CVA"."VENDOR_ID")
 WHERE "slcal"."YEAR_PERIOD" BETWEEN '202306'	AND   '202406';

<br> </br>

INSERT INTO  SALES_W_LIST_COST
(
    "STORE_NO"  ,
    "CO_CODE"  ,
    "STORE_DIM_KEY"  ,
    "TRANS_NO"  ,
    "TRANS_SEQ_NO"  ,
    "ARTICLE_NO"  ,
    "ARTICLE_DIM_KEY"  ,
    "CO_ARTICLE_DIM_KEY"  ,
    "TIME_DIM_KEY"  ,
    "DATE_PARSED"  ,
    "EMPL_DIM_KEY"  ,
    "TRANS_POSTAL_CODE"  ,
    "TRANS_TS"  ,
    "SUM_TYPE_CODE"  ,
    "VENDOR_ID"  ,
    "DC_NO"  ,
    "REPL_TYPE_CODE"  ,
    "PRICE_ZONE_CODE"  ,
    "CURRENT_VENDOR_ID"  ,
    "CURRENT_DC_NO"  ,
    "CURRENT_REPL_TYPE_CODE"  ,
    "SALE_REFUND_IND"  ,
    "PRICE_OVRD_FLAG"  ,
    "SCAN_ITEM_FLAG"  ,
    "PRICE_TYPE_CODE"  ,
    "EMPL_ID"  ,
    "CUST_EMPL_ID"  ,
    "EC_ID"  ,
    "DISC_RESN_CODE"  ,
    "OVRD_RESN_CODE"  ,
    "RETURN_RESN_CODE"  ,
    "TAX_EXEMPT_STATUS_CODE"  ,
    "TAX_TYPE_CODE"  ,
    "TRANS_TYPE_CODE"  ,
    "TERM_NO"  ,
    "UPC"  ,
    "PROMO_NO"  ,
    "TRANS_ARTICLE_COUNT"  ,
    "TRANS_LINE_COUNT"  ,
    "SALES_QTY"  ,
    "UNIT_PRICE"  ,
    "ORIG_UNIT_PRICE"  ,
    "UNIT_COST"  ,
    "SALES_AMT"  ,
    "COST_AMT"  ,
    "DISC_AMT"  ,
    "OVRD_AMT"  ,
    "TRANS_TAX_AMT"  ,
    "ORIG_TRANS_NO"  ,
    "TRANS_LINE_DESC"  ,
    "VENDOR_PART_NO"  ,
    "OMS_ORDER_NO"  ,
    "LOYALTY_ID"  ,
    "BUY_ONLINE_CODE"  ,
    "CUST_DIM_KEY"  ,
    "SAP_BP_ID"  ,
    "RECORD_CREATE_TS"  ,
    "DISC_CODE"  ,
    "CAL_DATE"  ,
    "MERCH_YEAR"  ,
    "ACCT_YEAR"  ,
    "YEAR_WEEK"  ,
    "YEAR_QUARTER"  ,
    "YEAR_PERIOD"  ,
    "CHAIN_PROD"  ,
    "ARTICLE_DESC"  ,
    "ARTICLE_FULL"  ,
    "ARTICLE_TYPE_NAME"  ,
    "ARTICLE_TYPE_CODE"  ,
    "ARTICLE_TYPE_FULL"  ,
    "LABEL_TYPE_CODE"  ,
    "UOM_CODE"  ,
    "UOM_DESC"  ,
    "UOM_FULL"  ,
    "PLANOGRAM_NO"  ,
    "PLANOGRAM_FACE"  ,
    "PLANOGRAM_SEQ"  ,
    "ARTICLE_CREATE_DATE"  ,
    "ACCT_POOL_CODE"  ,
    "ARTICLE_LENGTH"  ,
    "ARTICLE_WIDTH"  ,
    "ARTICLE_HEIGHT"  ,
    "ARTICLE_WEIGHT"  ,
    "ARTICLE_SIZE"  ,
    "ARTICLE_COUNT"  ,
    "ARTICLE_COLOR"  ,
    "LOC_TYPE_CODE"  ,
    "WORKSHEET_CYCLE"  ,
    "PARENT_ARTICLE_NO"  ,
    "PARENT_ARTICLE_DESC"  ,
    "PARENT_ARTICLE_FULL"  ,
    "POG_CAT_STRATEGY"  ,
    "POG_KPI_WT_SALES"  ,
    "POG_KPI_WT_PROFIT"  ,
    "POG_KPI_WT_UNIT_MV"  ,
    "PRIMARY_VENDOR_ID"  ,
    "ARTICLE_WTY_START_DATE"  ,
    "SPACE_PLANNER_NO"  ,
    "ARTICLE_CAT_CODE"  ,
    "ARTICLE_CAT_NAME"  ,
    "ARTICLE_CAT_FULL"  ,
    "DEPT_CODE"  ,
    "DEPT_NAME"  ,
    "DEPT_FULL"  ,
    "LOB_NO"  ,
    "LOB_DESC"  ,
    "LOB_FULL"  ,
    "MAJ_DEPT_NO"  ,
    "MAJ_DEPT_DESC"  ,
    "MAJ_DEPT_FULL"  ,
    "DISPLAY_ARTICLE_FLAG"  ,
    "SEASON_DESC" ,
    "ARTICLE_THEME_DESC"  ,
    "BRAND_NAME"  ,
    "PVT_LABEL_DESC"  ,
    "ARTICLE_FREIGHT_START_DATE"  ,
    "ARTICLE_FREIGHT_AMT"  ,
    "ADDL_ARTICLE_NO"  ,
    "ARTICLE_MIN_ADV_PRICE"  ,
    "OLD_ARTICLE_NO"  ,
    "MANUFACTURER_VENDOR_NAME"  ,
    "VENDOR_COID"  ,
    "VENDOR_NAME"  ,
    "VENDOR_FULL"  ,
    "VENDOR_CO_NAME"  ,
    "REGION_CODE"  ,
    "VENDOR_TYPE_CODE"  ,
    "VENDOR_BASE_SHIPPING_QTY" ,
    "VENDOR_PLANNED_DELIV_DAYS"  ,
    "VENDOR_PRICE"  ,
    "VENDOR_ARTICLE_QUOTE_NO"  ,
    "VENDOR_ARTICLE_RETURN_AGREEMENT_CODE"  ,
    "VSR_CODE" ,
    "rownumber"  ,
	"DISTB_CHAN_CODE" ,
	"Gross_ARTICLE_PRICE" 
)
 SELECT 
    "SLT"."STORE_NO" ,
    "SLT"."CO_CODE" ,
    "SLT"."STORE_DIM_KEY" ,
    "SLT"."TRANS_NO" ,
    "SLT"."TRANS_SEQ_NO" ,
    "SLT"."ARTICLE_NO" ,
    "SLT"."ARTICLE_DIM_KEY" ,
    "SLT"."CO_ARTICLE_DIM_KEY" ,
    "SLT"."TIME_DIM_KEY" ,
    "SLT"."DATE_PARSED" ,
    "SLT"."EMPL_DIM_KEY" ,
    "SLT"."TRANS_POSTAL_CODE" ,
    "SLT"."TRANS_TS" ,
    "SLT"."SUM_TYPE_CODE" ,
    "SLT"."VENDOR_ID" ,
    "SLT"."DC_NO" ,
    "SLT"."REPL_TYPE_CODE" ,
    "SLT"."PRICE_ZONE_CODE" ,
    "SLT"."CURRENT_VENDOR_ID" ,
    "SLT"."CURRENT_DC_NO" ,
    "SLT"."CURRENT_REPL_TYPE_CODE" ,
    "SLT"."SALE_REFUND_IND" ,
    "SLT"."PRICE_OVRD_FLAG" ,
    "SLT"."SCAN_ITEM_FLAG" ,
    "SLT"."PRICE_TYPE_CODE" ,
    "SLT"."EMPL_ID" ,
    "SLT"."CUST_EMPL_ID" ,
    "SLT"."EC_ID" ,
    "SLT"."DISC_RESN_CODE" ,
    "SLT"."OVRD_RESN_CODE" ,
    "SLT"."RETURN_RESN_CODE" ,
    "SLT"."TAX_EXEMPT_STATUS_CODE" ,
    "SLT"."TAX_TYPE_CODE" ,
    "SLT"."TRANS_TYPE_CODE" ,
    "SLT"."TERM_NO" ,
    "SLT"."UPC" ,
    "SLT"."PROMO_NO" ,
    "SLT"."TRANS_ARTICLE_COUNT" ,
    "SLT"."TRANS_LINE_COUNT" ,
    "SLT"."SALES_QTY" ,
    "SLT"."UNIT_PRICE" ,
    "SLT"."ORIG_UNIT_PRICE" ,
    "SLT"."UNIT_COST" ,
    "SLT"."SALES_AMT" ,
    "SLT"."COST_AMT" ,
    "SLT"."DISC_AMT" ,
    "SLT"."OVRD_AMT" ,
    "SLT"."TRANS_TAX_AMT" ,
    "SLT"."ORIG_TRANS_NO" ,
    "SLT"."TRANS_LINE_DESC" ,
    "SLT"."VENDOR_PART_NO" ,
    "SLT"."OMS_ORDER_NO" ,
    "SLT"."LOYALTY_ID" ,
    "SLT"."BUY_ONLINE_CODE" ,
    "SLT"."CUST_DIM_KEY" ,
    "SLT"."SAP_BP_ID" ,
    "SLT"."RECORD_CREATE_TS" ,
    "SLT"."DISC_CODE" ,
    "SLT"."CAL_DATE" ,
    "SLT"."MERCH_YEAR" ,
    "SLT"."ACCT_YEAR" ,
    "SLT"."YEAR_WEEK" ,
    "SLT"."YEAR_QUARTER" ,
    "SLT"."YEAR_PERIOD" ,
    "SLT"."CHAIN_PROD" ,
    "SLT"."ARTICLE_DESC" ,
    "SLT"."ARTICLE_FULL" ,
    "SLT"."ARTICLE_TYPE_NAME" ,
    "SLT"."ARTICLE_TYPE_CODE" ,
    "SLT"."ARTICLE_TYPE_FULL" ,
    "SLT"."LABEL_TYPE_CODE" ,
    "SLT"."UOM_CODE" ,
    "SLT"."UOM_DESC" ,
    "SLT"."UOM_FULL" ,
    "SLT"."PLANOGRAM_NO" ,
    "SLT"."PLANOGRAM_FACE" ,
    "SLT"."PLANOGRAM_SEQ" ,
    "SLT"."ARTICLE_CREATE_DATE" ,
    "SLT"."ACCT_POOL_CODE" ,
    "SLT"."ARTICLE_LENGTH" ,
    "SLT"."ARTICLE_WIDTH" ,
    "SLT"."ARTICLE_HEIGHT" ,
    "SLT"."ARTICLE_WEIGHT" ,
    "SLT"."ARTICLE_SIZE" ,
    "SLT"."ARTICLE_COUNT" ,
    "SLT"."ARTICLE_COLOR" ,
    "SLT"."LOC_TYPE_CODE" ,
    "SLT"."WORKSHEET_CYCLE" ,
    "SLT"."PARENT_ARTICLE_NO" ,
    "SLT"."PARENT_ARTICLE_DESC" ,
    "SLT"."PARENT_ARTICLE_FULL" ,
    "SLT"."POG_CAT_STRATEGY" ,
    "SLT"."POG_KPI_WT_SALES" ,
    "SLT"."POG_KPI_WT_PROFIT" ,
    "SLT"."POG_KPI_WT_UNIT_MV" ,
    "SLT"."PRIMARY_VENDOR_ID" ,
    "SLT"."ARTICLE_WTY_START_DATE" ,
    "SLT"."SPACE_PLANNER_NO" ,
    "SLT"."ARTICLE_CAT_CODE" ,
    "SLT"."ARTICLE_CAT_NAME" ,
    "SLT"."ARTICLE_CAT_FULL" ,
    "SLT"."DEPT_CODE" ,
    "SLT"."DEPT_NAME" ,
    "SLT"."DEPT_FULL" ,
    "SLT"."LOB_NO" ,
    "SLT"."LOB_DESC" ,
    "SLT"."LOB_FULL" ,
    "SLT"."MAJ_DEPT_NO" ,
    "SLT"."MAJ_DEPT_DESC" ,
    "SLT"."MAJ_DEPT_FULL" ,
    "SLT"."DISPLAY_ARTICLE_FLAG" ,
    "SLT"."SEASON_DESC",
    "SLT"."ARTICLE_THEME_DESC" ,
    "SLT"."BRAND_NAME" ,
    "SLT"."PVT_LABEL_DESC" ,
    "SLT"."ARTICLE_FREIGHT_START_DATE" ,
    "SLT"."ARTICLE_FREIGHT_AMT" ,
    "SLT"."ADDL_ARTICLE_NO" ,
    "SLT"."ARTICLE_MIN_ADV_PRICE" ,
    "SLT"."OLD_ARTICLE_NO" ,
    "SLT"."MANUFACTURER_VENDOR_NAME" ,
    "SLT"."VENDOR_COID" ,
    "SLT"."VENDOR_NAME" ,
    "SLT"."VENDOR_FULL" ,
    "SLT"."VENDOR_CO_NAME" ,
    "SLT"."REGION_CODE" ,
    "SLT"."VENDOR_TYPE_CODE" ,
    "SLT"."VENDOR_BASE_SHIPPING_QTY",
    "SLT"."VENDOR_PLANNED_DELIV_DAYS" ,
    "SLT"."VENDOR_PRICE" ,
    "SLT"."VENDOR_ARTICLE_QUOTE_NO" ,
    "SLT"."VENDOR_ARTICLE_RETURN_AGREEMENT_CODE" ,
    "SLT"."VSR_CODE",
    "SLT"."rownumber" 
    , S."DISTB_CHAN_CODE"
    , COALESCE (AP_3.ARTICLE_PRICE_AMT, AP_2.ARTICLE_PRICE_AMT, AP_1.ARTICLE_PRICE_AMT  ) AS "Gross_ARTICLE_PRICE"         

    FROM 
        SALES_W_LIST_COST_WINDOWS_STG SLT 
        LEFT OUTER JOIN EDW.VW_Store S on SLT.STORE_NO = S.STORE_NO
        LEFT OUTER JOIN EDW.VW_ARTICLE_PRICE AP_3 ON         
            SLT.Article_NO = AP_3.Article_NO 
            AND AP_3.price_type_code = 2
            AND AP_3."DISTB_CHAN_CODE" = S."DISTB_CHAN_CODE"
            AND SLT.DATE_PARSED BETWEEN AP_3."PRICE_START_DATE" and AP_3."PRICE_END_DATE"            
            AND SLT.STORE_NO = AP_3.PRICE_LOC_CODE            
            AND AP_3.PRICE_LEVEL_CODE = 3
        LEFT OUTER JOIN EDW.VW_ARTICLE_PRICE AP_2 ON         
            SLT.Article_NO = AP_2.Article_NO
            AND AP_2.price_type_code = 2
            AND AP_2."DISTB_CHAN_CODE" = S."DISTB_CHAN_CODE"
            AND SLT.DATE_PARSED BETWEEN AP_2."PRICE_START_DATE" and AP_2."PRICE_END_DATE"
            
            AND SLT.PRICE_ZONE_CODE = AP_2.PRICE_LOC_CODE            
            AND AP_2.PRICE_LEVEL_CODE = 2 
        LEFT OUTER JOIN EDW.VW_ARTICLE_PRICE AP_1 ON         
            SLT.Article_NO = AP_1.Article_NO 
            AND AP_1.price_type_code = 2
            AND AP_1."DISTB_CHAN_CODE" = S."DISTB_CHAN_CODE"
            AND SLT.DATE_PARSED BETWEEN AP_1."PRICE_START_DATE" and AP_1."PRICE_END_DATE"            
            AND AP_1.PRICE_LEVEL_CODE = 1 
 WHERE "SLT"."YEAR_PERIOD" BETWEEN '202306'	AND   '202406';
<br> </br>

INSERT INTO SALES_W_GROSS_SALES_PREPARED_STG_TMP
(
"STORE_NO"  ,
"CO_CODE"  ,
"STORE_DIM_KEY"  ,
"TRANS_NO"  ,
"TRANS_SEQ_NO"  ,
"ARTICLE_NO"  ,
"ARTICLE_DIM_KEY"  ,
"CO_ARTICLE_DIM_KEY"  ,
"TIME_DIM_KEY"  ,
"DATE_PARSED"  ,
"EMPL_DIM_KEY" ,
"TRANS_POSTAL_CODE"  ,
"TRANS_TS"  ,
"SUM_TYPE_CODE"  ,
"VENDOR_ID"  ,
"DC_NO" ,
"REPL_TYPE_CODE"  ,
"PRICE_ZONE_CODE" ,
"CURRENT_VENDOR_ID"  ,
"CURRENT_DC_NO"  ,
"CURRENT_REPL_TYPE_CODE"  ,
"SALE_REFUND_IND"  ,
"PRICE_OVRD_FLAG"  ,
"SCAN_ITEM_FLAG"  ,
"PRICE_TYPE_CODE"  ,
"EMPL_ID"  ,
"CUST_EMPL_ID"  ,
"EC_ID"  ,
"DISC_RESN_CODE"  ,
"OVRD_RESN_CODE"  ,
"RETURN_RESN_CODE"  ,
"TAX_EXEMPT_STATUS_CODE"  ,
"TAX_TYPE_CODE"  ,
"TRANS_TYPE_CODE"  ,
"TERM_NO"  ,
"UPC"  ,
"PROMO_NO"  ,
"TRANS_ARTICLE_COUNT"  ,
"TRANS_LINE_COUNT"  ,
"SALES_QTY"  ,
"UNIT_PRICE"  ,
"ORIG_UNIT_PRICE"  ,
"UNIT_COST"  ,
"SALES_AMT"  ,
"COST_AMT"  ,
"DISC_AMT"  ,
"OVRD_AMT"  ,
"TRANS_TAX_AMT"  ,
"ORIG_TRANS_NO"  ,
"TRANS_LINE_DESC"  ,
"VENDOR_PART_NO"  ,
"OMS_ORDER_NO" ,
"LOYALTY_ID"  ,
"BUY_ONLINE_CODE"  ,
"CUST_DIM_KEY"  ,
"SAP_BP_ID"  ,
"RECORD_CREATE_TS"  ,
"DISC_CODE"  ,
"CAL_DATE"  ,
"MERCH_YEAR"  ,
"ACCT_YEAR"  ,
"YEAR_WEEK"  ,
"YEAR_QUARTER"  ,
"YEAR_PERIOD"  ,
"CHAIN_PROD"  ,
"ARTICLE_DESC"  ,
"ARTICLE_FULL"  ,
"ARTICLE_TYPE_NAME"  ,
"ARTICLE_TYPE_CODE"  ,
"ARTICLE_TYPE_FULL"  ,
"LABEL_TYPE_CODE"  ,
"UOM_CODE"  ,
"UOM_DESC"  ,
"UOM_FULL"  ,
"PLANOGRAM_NO"  ,
"PLANOGRAM_FACE"  ,
"PLANOGRAM_SEQ"  ,
"ARTICLE_CREATE_DATE"  ,
"ACCT_POOL_CODE"  ,
"ARTICLE_LENGTH"  ,
"ARTICLE_WIDTH"  ,
"ARTICLE_HEIGHT"  ,
"ARTICLE_WEIGHT"  ,
"ARTICLE_SIZE"  ,
"ARTICLE_COUNT"  ,
"ARTICLE_COLOR"  ,
"LOC_TYPE_CODE"  ,
"WORKSHEET_CYCLE"  ,
"PARENT_ARTICLE_NO"  ,
"PARENT_ARTICLE_DESC"  ,
"PARENT_ARTICLE_FULL"  ,
"POG_CAT_STRATEGY"  ,
"POG_KPI_WT_SALES"  ,
"POG_KPI_WT_PROFIT"  ,
"POG_KPI_WT_UNIT_MV"  ,
"PRIMARY_VENDOR_ID"  ,
"ARTICLE_WTY_START_DATE"  ,
"SPACE_PLANNER_NO"  ,
"ARTICLE_CAT_CODE"  ,
"ARTICLE_CAT_NAME"  ,
"ARTICLE_CAT_FULL"  ,
"DEPT_CODE"  ,
"DEPT_NAME"  ,
"DEPT_FULL"  ,
"LOB_NO"  ,
"LOB_DESC"  ,
"LOB_FULL"  ,
"MAJ_DEPT_NO"  ,
"MAJ_DEPT_DESC"  ,
"MAJ_DEPT_FULL"  ,
"DISPLAY_ARTICLE_FLAG"  ,
"SEASON_DESC"  ,
"ARTICLE_THEME_DESC"  ,
"BRAND_NAME"  ,
"PVT_LABEL_DESC"  ,
"ARTICLE_FREIGHT_START_DATE"  ,
"ARTICLE_FREIGHT_AMT"  ,
"ADDL_ARTICLE_NO"  ,
"ARTICLE_MIN_ADV_PRICE"  ,
"OLD_ARTICLE_NO"  ,
"MANUFACTURER_VENDOR_NAME"  ,
"VENDOR_COID"  ,
"VENDOR_NAME"  ,
"VENDOR_FULL"  ,
"VENDOR_CO_NAME"  ,
"REGION_CODE"  ,
"VENDOR_TYPE_CODE"  ,
"VENDOR_BASE_SHIPPING_QTY"  ,
"VENDOR_PLANNED_DELIV_DAYS"  ,
"VENDOR_PRICE"  ,
"VENDOR_ARTICLE_QUOTE_NO"  ,
"VENDOR_ARTICLE_RETURN_AGREEMENT_CODE"  ,
"VSR_CODE"  ,
"rownumber"  ,
"DISTB_CHAN_CODE"  ,
"Gross_ARTICLE_PRICE"  ,
"RN"  ,
"gross_sales"  
)
SELECT  
"STORE_NO" ,
"CO_CODE" ,
"STORE_DIM_KEY" ,
"TRANS_NO" ,
"TRANS_SEQ_NO" ,
"ARTICLE_NO" ,
"ARTICLE_DIM_KEY" ,
"CO_ARTICLE_DIM_KEY" ,
"TIME_DIM_KEY" ,
"DATE_PARSED" ,
"EMPL_DIM_KEY",
"TRANS_POSTAL_CODE" ,
"TRANS_TS" ,
"SUM_TYPE_CODE" ,
"VENDOR_ID" ,
"DC_NO",
"REPL_TYPE_CODE" ,
"PRICE_ZONE_CODE",
"CURRENT_VENDOR_ID" ,
"CURRENT_DC_NO" ,
"CURRENT_REPL_TYPE_CODE" ,
"SALE_REFUND_IND" ,
"PRICE_OVRD_FLAG" ,
"SCAN_ITEM_FLAG" ,
"PRICE_TYPE_CODE" ,
"EMPL_ID" ,
"CUST_EMPL_ID" ,
"EC_ID" ,
"DISC_RESN_CODE" ,
"OVRD_RESN_CODE" ,
"RETURN_RESN_CODE" ,
"TAX_EXEMPT_STATUS_CODE" ,
"TAX_TYPE_CODE" ,
"TRANS_TYPE_CODE" ,
"TERM_NO" ,
"UPC" ,
"PROMO_NO" ,
"TRANS_ARTICLE_COUNT" ,
"TRANS_LINE_COUNT" ,
"SALES_QTY" ,
"UNIT_PRICE" ,
"ORIG_UNIT_PRICE" ,
"UNIT_COST" ,
"SALES_AMT" ,
"COST_AMT" ,
"DISC_AMT" ,
"OVRD_AMT" ,
"TRANS_TAX_AMT" ,
"ORIG_TRANS_NO" ,
"TRANS_LINE_DESC" ,
"VENDOR_PART_NO" ,
"OMS_ORDER_NO",
"LOYALTY_ID" ,
"BUY_ONLINE_CODE" ,
"CUST_DIM_KEY" ,
"SAP_BP_ID" ,
"RECORD_CREATE_TS" ,
"DISC_CODE" ,
"CAL_DATE" ,
"MERCH_YEAR" ,
"ACCT_YEAR" ,
"YEAR_WEEK" ,
"YEAR_QUARTER" ,
"YEAR_PERIOD" ,
"CHAIN_PROD" ,
"ARTICLE_DESC" ,
"ARTICLE_FULL" ,
"ARTICLE_TYPE_NAME" ,
"ARTICLE_TYPE_CODE" ,
"ARTICLE_TYPE_FULL" ,
"LABEL_TYPE_CODE" ,
"UOM_CODE" ,
"UOM_DESC" ,
"UOM_FULL" ,
"PLANOGRAM_NO" ,
"PLANOGRAM_FACE" ,
"PLANOGRAM_SEQ" ,
"ARTICLE_CREATE_DATE" ,
"ACCT_POOL_CODE" ,
"ARTICLE_LENGTH" ,
"ARTICLE_WIDTH" ,
"ARTICLE_HEIGHT" ,
"ARTICLE_WEIGHT" ,
"ARTICLE_SIZE" ,
"ARTICLE_COUNT" ,
"ARTICLE_COLOR" ,
"LOC_TYPE_CODE" ,
"WORKSHEET_CYCLE" ,
"PARENT_ARTICLE_NO" ,
"PARENT_ARTICLE_DESC" ,
"PARENT_ARTICLE_FULL" ,
"POG_CAT_STRATEGY" ,
"POG_KPI_WT_SALES" ,
"POG_KPI_WT_PROFIT" ,
"POG_KPI_WT_UNIT_MV" ,
"PRIMARY_VENDOR_ID" ,
"ARTICLE_WTY_START_DATE" ,
"SPACE_PLANNER_NO" ,
"ARTICLE_CAT_CODE" ,
"ARTICLE_CAT_NAME" ,
"ARTICLE_CAT_FULL" ,
"DEPT_CODE" ,
"DEPT_NAME" ,
"DEPT_FULL" ,
"LOB_NO" ,
"LOB_DESC" ,
"LOB_FULL" ,
"MAJ_DEPT_NO" ,
"MAJ_DEPT_DESC" ,
"MAJ_DEPT_FULL" ,
"DISPLAY_ARTICLE_FLAG" ,
"SEASON_DESC" ,
"ARTICLE_THEME_DESC" ,
"BRAND_NAME" ,
"PVT_LABEL_DESC" ,
"ARTICLE_FREIGHT_START_DATE" ,
"ARTICLE_FREIGHT_AMT" ,
"ADDL_ARTICLE_NO" ,
"ARTICLE_MIN_ADV_PRICE" ,
"OLD_ARTICLE_NO" ,
"MANUFACTURER_VENDOR_NAME" ,
 "VENDOR_COID" ,
"VENDOR_NAME" ,
"VENDOR_FULL" ,
"VENDOR_CO_NAME" ,
"REGION_CODE" ,
"VENDOR_TYPE_CODE" ,
"VENDOR_BASE_SHIPPING_QTY" ,
"VENDOR_PLANNED_DELIV_DAYS" ,
"VENDOR_PRICE" ,
"VENDOR_ARTICLE_QUOTE_NO" ,
"VENDOR_ARTICLE_RETURN_AGREEMENT_CODE" ,
"VSR_CODE" ,
"rownumber" ,
"DISTB_CHAN_CODE" ,
"Gross_ARTICLE_PRICE" ,
"RN" ,
COALESCE("SALES_QTY", 0) * "Gross_ARTICLE_PRICE" AS "gross_sales"
FROM 
  (            
  SELECT *
  , ROW_NUMBER() over ( partition by "rownumber" order by "rownumber"  ) AS RN 
  FROM SALES_W_LIST_COST
  WHERE  "YEAR_PERIOD" BETWEEN '202306'  AND '202406'
    
  )
  WHERE  RN = 1 ;
  
 <br> </br>
 
INSERT INTO SALES_AGGREGATED_WEEKLY 
(
"CO_CODE"  ,
"ARTICLE_NO"  ,
"SUM_TYPE_CODE"  ,
"VENDOR_ID"  ,
"PRICE_OVRD_FLAG"  ,
"SCAN_ITEM_FLAG"  ,
"PRICE_TYPE_CODE"  ,
"BUY_ONLINE_CODE"  ,
"MERCH_YEAR"  ,
"YEAR_WEEK"  ,
"YEAR_QUARTER"  ,
"YEAR_PERIOD"  ,
"ARTICLE_DESC"  ,
"ARTICLE_FULL"  ,
"ARTICLE_TYPE_NAME"  ,
"ARTICLE_TYPE_CODE"  ,
"ARTICLE_TYPE_FULL"  ,
"LABEL_TYPE_CODE"  ,
"UOM_CODE"  ,
"UOM_DESC"  ,
"UOM_FULL"  ,
"ARTICLE_LENGTH"  ,
"ARTICLE_WIDTH"  ,
"ARTICLE_HEIGHT"  ,
"ARTICLE_WEIGHT"  ,
"ARTICLE_SIZE"  ,
"ARTICLE_COUNT"  ,
"LOC_TYPE_CODE"  ,
"PRIMARY_VENDOR_ID"  ,
"ARTICLE_CAT_CODE"  ,
"ARTICLE_CAT_NAME"  ,
"ARTICLE_CAT_FULL"  ,
"DEPT_CODE"  ,
"DEPT_NAME"  ,
"DEPT_FULL"  ,
"LOB_NO"  ,
"LOB_DESC"  ,
"LOB_FULL"  ,
"MAJ_DEPT_NO"  ,
"MAJ_DEPT_DESC"  ,
"MAJ_DEPT_FULL"  ,
"BRAND_NAME"  ,
"PVT_LABEL_DESC"  ,
"VENDOR_NAME"  ,
"VENDOR_FULL"  ,
"VENDOR_CO_NAME"  ,
"REGION_CODE"  ,
"SALES_QTY"  ,
"SALES_AMT"  ,
"COST_AMT"  ,
"DISC_AMT"  ,
"OVRD_AMT"  ,
"TRANS_TAX_AMT"  ,
"gross_sales" 
)
    SELECT 
        "CO_CODE" AS "CO_CODE",
        "ARTICLE_NO" AS "ARTICLE_NO",
        "SUM_TYPE_CODE" AS "SUM_TYPE_CODE",
        "VENDOR_ID" AS "VENDOR_ID",
        "PRICE_OVRD_FLAG" AS "PRICE_OVRD_FLAG",
        "SCAN_ITEM_FLAG" AS "SCAN_ITEM_FLAG",
        "PRICE_TYPE_CODE" AS "PRICE_TYPE_CODE",
        "BUY_ONLINE_CODE" AS "BUY_ONLINE_CODE",
        "MERCH_YEAR" AS "MERCH_YEAR",
        "YEAR_WEEK" AS "YEAR_WEEK",
        "YEAR_QUARTER" AS "YEAR_QUARTER",
        "YEAR_PERIOD" AS "YEAR_PERIOD",
        "ARTICLE_DESC" AS "ARTICLE_DESC",
        "ARTICLE_FULL" AS "ARTICLE_FULL",
        "ARTICLE_TYPE_NAME" AS "ARTICLE_TYPE_NAME",
        "ARTICLE_TYPE_CODE" AS "ARTICLE_TYPE_CODE",
        "ARTICLE_TYPE_FULL" AS "ARTICLE_TYPE_FULL",
        "LABEL_TYPE_CODE" AS "LABEL_TYPE_CODE",
        "UOM_CODE" AS "UOM_CODE",
        "UOM_DESC" AS "UOM_DESC",
        "UOM_FULL" AS "UOM_FULL",
        "ARTICLE_LENGTH" AS "ARTICLE_LENGTH",
        "ARTICLE_WIDTH" AS "ARTICLE_WIDTH",
        "ARTICLE_HEIGHT" AS "ARTICLE_HEIGHT",
        "ARTICLE_WEIGHT" AS "ARTICLE_WEIGHT",
        "ARTICLE_SIZE" AS "ARTICLE_SIZE",
        "ARTICLE_COUNT" AS "ARTICLE_COUNT",
        "LOC_TYPE_CODE" AS "LOC_TYPE_CODE",
        "PRIMARY_VENDOR_ID" AS "PRIMARY_VENDOR_ID",
        "ARTICLE_CAT_CODE" AS "ARTICLE_CAT_CODE",
        "ARTICLE_CAT_NAME" AS "ARTICLE_CAT_NAME",
        "ARTICLE_CAT_FULL" AS "ARTICLE_CAT_FULL",
        "DEPT_CODE" AS "DEPT_CODE",
        "DEPT_NAME" AS "DEPT_NAME",
        "DEPT_FULL" AS "DEPT_FULL",
        "LOB_NO" AS "LOB_NO",
        "LOB_DESC" AS "LOB_DESC",
        "LOB_FULL" AS "LOB_FULL",
        "MAJ_DEPT_NO" AS "MAJ_DEPT_NO",
        "MAJ_DEPT_DESC" AS "MAJ_DEPT_DESC",
        "MAJ_DEPT_FULL" AS "MAJ_DEPT_FULL",
        "BRAND_NAME" AS "BRAND_NAME",
        "PVT_LABEL_DESC" AS "PVT_LABEL_DESC",
        "VENDOR_NAME" AS "VENDOR_NAME",
        "VENDOR_FULL" AS "VENDOR_FULL",
        "VENDOR_CO_NAME" AS "VENDOR_CO_NAME",
        "REGION_CODE" AS "REGION_CODE",
        SUM("SALES_QTY") AS "SALES_QTY",
        SUM("SALES_AMT") AS "SALES_AMT",
        SUM("COST_AMT") AS "COST_AMT",
        SUM("DISC_AMT") AS "DISC_AMT",
        SUM("OVRD_AMT") AS "OVRD_AMT",
        SUM("TRANS_TAX_AMT") AS "TRANS_TAX_AMT",
        SUM("gross_sales") AS "gross_sales"
      FROM (
        SELECT 
            "STORE_NO",
            "CO_CODE",
            "STORE_DIM_KEY",
            "TRANS_NO",
            "TRANS_SEQ_NO",
            "ARTICLE_NO",
            "ARTICLE_DIM_KEY",
            "CO_ARTICLE_DIM_KEY",
            "TIME_DIM_KEY",
            "DATE_PARSED",
            "EMPL_DIM_KEY",
            "TRANS_POSTAL_CODE",
            "TRANS_TS",
            "SUM_TYPE_CODE",
            "VENDOR_ID",
            "DC_NO",
            "REPL_TYPE_CODE",
            "PRICE_ZONE_CODE",
            "CURRENT_VENDOR_ID",
            "CURRENT_DC_NO",
            "CURRENT_REPL_TYPE_CODE",
            "SALE_REFUND_IND",
            "PRICE_OVRD_FLAG",
            "SCAN_ITEM_FLAG",
            "PRICE_TYPE_CODE",
            "EMPL_ID",
            "CUST_EMPL_ID",
            "EC_ID",
            "DISC_RESN_CODE",
            "OVRD_RESN_CODE",
            "RETURN_RESN_CODE",
            "TAX_EXEMPT_STATUS_CODE",
            "TAX_TYPE_CODE",
            "TRANS_TYPE_CODE",
            "TERM_NO",
            "UPC",
            "PROMO_NO",
            "TRANS_ARTICLE_COUNT",
            "TRANS_LINE_COUNT",
            "SALES_QTY",
            "UNIT_PRICE",
            "ORIG_UNIT_PRICE",
            "UNIT_COST",
            "SALES_AMT",
            "COST_AMT",
            "DISC_AMT",
            "OVRD_AMT",
            "TRANS_TAX_AMT",
            "ORIG_TRANS_NO",
            "TRANS_LINE_DESC",
            "VENDOR_PART_NO",
            "OMS_ORDER_NO",
            "LOYALTY_ID",
            "BUY_ONLINE_CODE",
            "CUST_DIM_KEY",
            "SAP_BP_ID",
            "RECORD_CREATE_TS",
            "DISC_CODE",
            "CAL_DATE",
            "MERCH_YEAR",
            "ACCT_YEAR",
            "YEAR_WEEK",
            "YEAR_QUARTER",
            "YEAR_PERIOD",
            "CHAIN_PROD",
            "ARTICLE_DESC",
            "ARTICLE_FULL",
            "ARTICLE_TYPE_NAME",
            "ARTICLE_TYPE_CODE",
            "ARTICLE_TYPE_FULL",
            "LABEL_TYPE_CODE",
            "UOM_CODE",
            "UOM_DESC",
            "UOM_FULL",
            "PLANOGRAM_NO",
            "PLANOGRAM_FACE",
            "PLANOGRAM_SEQ",
            "ARTICLE_CREATE_DATE",
            "ACCT_POOL_CODE",
            "ARTICLE_LENGTH",
            "ARTICLE_WIDTH",
            "ARTICLE_HEIGHT",
            "ARTICLE_WEIGHT",
            "ARTICLE_SIZE",
            "ARTICLE_COUNT",
            "ARTICLE_COLOR",
            "LOC_TYPE_CODE",
            "WORKSHEET_CYCLE",
            "PARENT_ARTICLE_NO",
            "PARENT_ARTICLE_DESC",
            "PARENT_ARTICLE_FULL",
            "POG_CAT_STRATEGY",
            "POG_KPI_WT_SALES",
            "POG_KPI_WT_PROFIT",
            "POG_KPI_WT_UNIT_MV",
            "PRIMARY_VENDOR_ID",
            "ARTICLE_WTY_START_DATE",
            "SPACE_PLANNER_NO",
            "ARTICLE_CAT_CODE",
            "ARTICLE_CAT_NAME",
            "ARTICLE_CAT_FULL",
            "DEPT_CODE",
            "DEPT_NAME",
            "DEPT_FULL",
            "LOB_NO",
            "LOB_DESC",
            "LOB_FULL",
            "MAJ_DEPT_NO",
            "MAJ_DEPT_DESC",
            "MAJ_DEPT_FULL",
            "DISPLAY_ARTICLE_FLAG",
            "SEASON_DESC",
            "ARTICLE_THEME_DESC",
            "BRAND_NAME",
            "PVT_LABEL_DESC",
            "ARTICLE_FREIGHT_START_DATE",
            "ARTICLE_FREIGHT_AMT",
            "ADDL_ARTICLE_NO",
            "ARTICLE_MIN_ADV_PRICE",
            "OLD_ARTICLE_NO",
            "MANUFACTURER_VENDOR_NAME",
            "VENDOR_COID",
            "VENDOR_NAME",
            "VENDOR_FULL",
            "VENDOR_CO_NAME",
            "REGION_CODE",
            "VENDOR_TYPE_CODE",
            "rownumber",
            "DISTB_CHAN_CODE",
            "gross_sales",
            "RN"
          FROM SALES_W_GROSS_SALES_PREPARED_STG_TMP
          WHERE ("CO_CODE" = 'TSC') AND ("STORE_NO" != 5509 OR "STORE_NO" IS NULL AND 5509 IS NOT NULL OR "STORE_NO" IS NOT NULL AND 5509 IS NULL) 
                  AND   "YEAR_PERIOD" BETWEEN '202306'  AND '202406'	  
        ) "dku__beforegrouping"
      GROUP BY "CO_CODE", "ARTICLE_NO", "SUM_TYPE_CODE", "VENDOR_ID", "PRICE_OVRD_FLAG", "SCAN_ITEM_FLAG", 
      "PRICE_TYPE_CODE", "BUY_ONLINE_CODE", "MERCH_YEAR", "YEAR_WEEK", "YEAR_QUARTER", "YEAR_PERIOD", 
      "ARTICLE_DESC", "ARTICLE_FULL", "ARTICLE_TYPE_NAME", "ARTICLE_TYPE_CODE", "ARTICLE_TYPE_FULL", 
      "LABEL_TYPE_CODE", "UOM_CODE", "UOM_DESC", "UOM_FULL", "ARTICLE_LENGTH", "ARTICLE_WIDTH", "ARTICLE_HEIGHT", 
      "ARTICLE_WEIGHT", "ARTICLE_SIZE", "ARTICLE_COUNT", "LOC_TYPE_CODE", "PRIMARY_VENDOR_ID", "ARTICLE_CAT_CODE", 
      "ARTICLE_CAT_NAME", "ARTICLE_CAT_FULL", "DEPT_CODE", "DEPT_NAME", "DEPT_FULL", "LOB_NO", "LOB_DESC", "LOB_FULL",
       "MAJ_DEPT_NO", "MAJ_DEPT_DESC", "MAJ_DEPT_FULL", "BRAND_NAME", "PVT_LABEL_DESC", "VENDOR_NAME", "VENDOR_FULL",
        "VENDOR_CO_NAME", "REGION_CODE";





